// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost3_wrt_DeltaRot_Nl10
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     position_vector: Matrix31
 *     Rot_init: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost3WrtDeltarotNl10(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot,
    const Eigen::Matrix<Scalar, 3, 1>& position_vector, const sym::Rot3<Scalar>& Rot_init,
    const Scalar epsilon) {
  // Total ops: 2061

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Rot_init = Rot_init.Data();

  // Intermediate terms (639)
  const Scalar _tmp0 = _DeltaRot[1] * _Rot_init[3];
  const Scalar _tmp1 = _DeltaRot[0] * _Rot_init[2];
  const Scalar _tmp2 = _DeltaRot[2] * _Rot_init[0];
  const Scalar _tmp3 = _DeltaRot[3] * _Rot_init[1];
  const Scalar _tmp4 = _tmp0 + _tmp1 - _tmp2 + _tmp3;
  const Scalar _tmp5 = -2 * std::pow(_tmp4, Scalar(2));
  const Scalar _tmp6 = _DeltaRot[1] * _Rot_init[0];
  const Scalar _tmp7 = _DeltaRot[0] * _Rot_init[1];
  const Scalar _tmp8 = _DeltaRot[2] * _Rot_init[3];
  const Scalar _tmp9 = _DeltaRot[3] * _Rot_init[2];
  const Scalar _tmp10 = _tmp6 - _tmp7 + _tmp8 + _tmp9;
  const Scalar _tmp11 = 1 - 2 * std::pow(_tmp10, Scalar(2));
  const Scalar _tmp12 = Scalar(0.20999999999999999) * _tmp11 + Scalar(0.20999999999999999) * _tmp5;
  const Scalar _tmp13 = -_tmp12;
  const Scalar _tmp14 = _DeltaRot[1] * _Rot_init[2];
  const Scalar _tmp15 = _DeltaRot[0] * _Rot_init[3];
  const Scalar _tmp16 = _DeltaRot[2] * _Rot_init[1];
  const Scalar _tmp17 = _DeltaRot[3] * _Rot_init[0];
  const Scalar _tmp18 = -_tmp14 + _tmp15 + _tmp16 + _tmp17;
  const Scalar _tmp19 = 2 * _tmp10 * _tmp18;
  const Scalar _tmp20 = _DeltaRot[1] * _Rot_init[1];
  const Scalar _tmp21 = _DeltaRot[0] * _Rot_init[0];
  const Scalar _tmp22 = _DeltaRot[2] * _Rot_init[2];
  const Scalar _tmp23 = _DeltaRot[3] * _Rot_init[3];
  const Scalar _tmp24 = -_tmp20 - _tmp21 - _tmp22 + _tmp23;
  const Scalar _tmp25 = 2 * _tmp24;
  const Scalar _tmp26 = _tmp25 * _tmp4;
  const Scalar _tmp27 =
      -Scalar(0.010999999999999999) * _tmp19 - Scalar(0.010999999999999999) * _tmp26;
  const Scalar _tmp28 = 2 * _tmp4;
  const Scalar _tmp29 = _tmp18 * _tmp28;
  const Scalar _tmp30 = _tmp10 * _tmp25;
  const Scalar _tmp31 = Scalar(0.20999999999999999) * _tmp29 - Scalar(0.20999999999999999) * _tmp30;
  const Scalar _tmp32 = _tmp27 - _tmp31;
  const Scalar _tmp33 = _tmp13 + _tmp32;
  const Scalar _tmp34 = Scalar(0.20999999999999999) * _tmp29 + Scalar(0.20999999999999999) * _tmp30;
  const Scalar _tmp35 = -_tmp34;
  const Scalar _tmp36 = _tmp10 * _tmp28;
  const Scalar _tmp37 = _tmp18 * _tmp25;
  const Scalar _tmp38 =
      -Scalar(0.010999999999999999) * _tmp36 + Scalar(0.010999999999999999) * _tmp37;
  const Scalar _tmp39 = -2 * std::pow(_tmp18, Scalar(2));
  const Scalar _tmp40 = Scalar(0.20999999999999999) * _tmp11 + Scalar(0.20999999999999999) * _tmp39;
  const Scalar _tmp41 = _tmp38 - _tmp40;
  const Scalar _tmp42 = _tmp35 + _tmp41;
  const Scalar _tmp43 = _tmp42 + position_vector(1, 0) + Scalar(8.3196563700000006);
  const Scalar _tmp44 = _tmp33 + position_vector(0, 0) + Scalar(1.9874742000000001);
  const Scalar _tmp45 = std::pow(_tmp43, Scalar(2)) + std::pow(_tmp44, Scalar(2));
  const Scalar _tmp46 = std::pow(_tmp45, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp47 = _tmp43 * _tmp46;
  const Scalar _tmp48 = _tmp44 * _tmp46;
  const Scalar _tmp49 = _tmp27 + _tmp31;
  const Scalar _tmp50 = _tmp13 + _tmp49;
  const Scalar _tmp51 = _tmp38 + _tmp40;
  const Scalar _tmp52 = _tmp35 + _tmp51;
  const Scalar _tmp53 = _tmp52 + position_vector(1, 0) + Scalar(-4.8333311099999996);
  const Scalar _tmp54 = _tmp50 + position_vector(0, 0) + Scalar(1.79662371);
  const Scalar _tmp55 = std::pow(_tmp54, Scalar(2));
  const Scalar _tmp56 = std::pow(_tmp53, Scalar(2)) + _tmp55;
  const Scalar _tmp57 = std::sqrt(_tmp56);
  const Scalar _tmp58 = Scalar(1.0) / (_tmp57);
  const Scalar _tmp59 = _tmp53 * _tmp58;
  const Scalar _tmp60 = _tmp52 * _tmp58;
  const Scalar _tmp61 = _tmp50 * _tmp59 - _tmp54 * _tmp60;
  const Scalar _tmp62 = Scalar(1.0) / (_tmp54);
  const Scalar _tmp63 = _tmp57 * _tmp62;
  const Scalar _tmp64 = _tmp61 * _tmp63;
  const Scalar _tmp65 = -_tmp33 * _tmp47 + _tmp42 * _tmp48 + _tmp48 * _tmp64;
  const Scalar _tmp66 = _tmp53 * _tmp62;
  const Scalar _tmp67 = -_tmp47 + _tmp48 * _tmp66;
  const Scalar _tmp68 = Scalar(1.0) / (_tmp67);
  const Scalar _tmp69 = Scalar(1.0) * _tmp68;
  const Scalar _tmp70 = Scalar(1.0) * _tmp52;
  const Scalar _tmp71 = _tmp42 - _tmp70;
  const Scalar _tmp72 = Scalar(1.0) / (_tmp71);
  const Scalar _tmp73 = Scalar(1.0) * _tmp50;
  const Scalar _tmp74 = -_tmp33 + _tmp73;
  const Scalar _tmp75 = _tmp72 * _tmp74;
  const Scalar _tmp76 = -Scalar(0.010999999999999999) * _tmp39 -
                        Scalar(0.010999999999999999) * _tmp5 + Scalar(-0.010999999999999999);
  const Scalar _tmp77 = Scalar(0.20999999999999999) * _tmp19 - Scalar(0.20999999999999999) * _tmp26;
  const Scalar _tmp78 = -_tmp77;
  const Scalar _tmp79 = Scalar(0.20999999999999999) * _tmp36 + Scalar(0.20999999999999999) * _tmp37;
  const Scalar _tmp80 = _tmp76 + _tmp78 - _tmp79;
  const Scalar _tmp81 = _tmp76 + _tmp79;
  const Scalar _tmp82 = _tmp78 + _tmp81;
  const Scalar _tmp83 = _tmp46 * _tmp82;
  const Scalar _tmp84 = _tmp44 * _tmp83;
  const Scalar _tmp85 = _tmp47 * _tmp80 - _tmp66 * _tmp84;
  const Scalar _tmp86 = _tmp69 * _tmp85;
  const Scalar _tmp87 = -_tmp48 * _tmp80 + _tmp84;
  const Scalar _tmp88 = -_tmp69 * _tmp87 + _tmp75 * _tmp86;
  const Scalar _tmp89 = _tmp34 + _tmp51;
  const Scalar _tmp90 = _tmp89 + position_vector(1, 0) + Scalar(-4.7752063900000001);
  const Scalar _tmp91 = _tmp12 + _tmp49;
  const Scalar _tmp92 = _tmp91 + position_vector(0, 0) + Scalar(-2.71799795);
  const Scalar _tmp93 = std::pow(_tmp90, Scalar(2)) + std::pow(_tmp92, Scalar(2));
  const Scalar _tmp94 = std::pow(_tmp93, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp95 = _tmp92 * _tmp94;
  const Scalar _tmp96 = _tmp82 * _tmp95;
  const Scalar _tmp97 = _tmp90 * _tmp94;
  const Scalar _tmp98 = _tmp66 * _tmp95 - _tmp97;
  const Scalar _tmp99 = _tmp68 * _tmp98;
  const Scalar _tmp100 = _tmp66 * _tmp82;
  const Scalar _tmp101 = _tmp77 + _tmp81;
  const Scalar _tmp102 = -_tmp100 * _tmp95 + _tmp101 * _tmp97 - _tmp85 * _tmp99;
  const Scalar _tmp103 = -_tmp101 * _tmp95 - _tmp102 * _tmp75 - _tmp87 * _tmp99 + _tmp96;
  const Scalar _tmp104 = Scalar(1.0) / (_tmp103);
  const Scalar _tmp105 = _tmp64 * _tmp95 - _tmp65 * _tmp99 + _tmp89 * _tmp95 - _tmp91 * _tmp97;
  const Scalar _tmp106 = _tmp104 * _tmp105;
  const Scalar _tmp107 = -_tmp106 * _tmp88 - _tmp65 * _tmp69;
  const Scalar _tmp108 = Scalar(1.0) / (_tmp105);
  const Scalar _tmp109 = _tmp103 * _tmp108;
  const Scalar _tmp110 = _tmp107 * _tmp109 + _tmp88;
  const Scalar _tmp111 = _tmp104 * _tmp98;
  const Scalar _tmp112 = -_tmp110 * _tmp111 + Scalar(1.0);
  const Scalar _tmp113 = _tmp48 * _tmp68;
  const Scalar _tmp114 = _tmp104 * _tmp110;
  const Scalar _tmp115 = _tmp112 * _tmp113 + _tmp114 * _tmp95;
  const Scalar _tmp116 = _tmp34 + _tmp41;
  const Scalar _tmp117 = _tmp116 + position_vector(1, 0) + Scalar(8.3888750099999996);
  const Scalar _tmp118 = _tmp12 + _tmp32;
  const Scalar _tmp119 = _tmp118 + position_vector(0, 0) + Scalar(-2.5202214700000001);
  const Scalar _tmp120 = std::pow(_tmp117, Scalar(2)) + std::pow(_tmp119, Scalar(2));
  const Scalar _tmp121 = std::pow(_tmp120, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp122 = _tmp117 * _tmp121;
  const Scalar _tmp123 = _tmp63 * fh1;
  const Scalar _tmp124 = _tmp122 * _tmp123;
  const Scalar _tmp125 = _tmp70 * _tmp75 + _tmp73;
  const Scalar _tmp126 = 0;
  const Scalar _tmp127 = _tmp104 * _tmp95;
  const Scalar _tmp128 = _tmp111 * _tmp126;
  const Scalar _tmp129 = -_tmp113 * _tmp128 + _tmp126 * _tmp127;
  const Scalar _tmp130 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp131 = _tmp130 * _tmp63;
  const Scalar _tmp132 = Scalar(1.0) * _tmp108;
  const Scalar _tmp133 = _tmp132 * _tmp99;
  const Scalar _tmp134 = _tmp132 * _tmp95 - _tmp133 * _tmp48;
  const Scalar _tmp135 = _tmp118 * _tmp121;
  const Scalar _tmp136 = _tmp119 * _tmp121;
  const Scalar _tmp137 = -_tmp116 * _tmp136 + _tmp117 * _tmp135;
  const Scalar _tmp138 = _tmp137 * fh1;
  const Scalar _tmp139 = _tmp138 * _tmp63;
  const Scalar _tmp140 = _tmp66 * _tmp68;
  const Scalar _tmp141 = _tmp100 + _tmp140 * _tmp85;
  const Scalar _tmp142 = _tmp140 * _tmp87 - _tmp141 * _tmp75 - _tmp82;
  const Scalar _tmp143 = -_tmp106 * _tmp142 + _tmp140 * _tmp65 - _tmp64;
  const Scalar _tmp144 = _tmp109 * _tmp143 + _tmp142;
  const Scalar _tmp145 = -_tmp111 * _tmp144 - _tmp66;
  const Scalar _tmp146 = _tmp104 * _tmp144;
  const Scalar _tmp147 = _tmp113 * _tmp145 + _tmp146 * _tmp95 + Scalar(1.0);
  const Scalar _tmp148 = _tmp123 * _tmp136;
  const Scalar _tmp149 =
      std::exp(_tmp115 * _tmp124 + _tmp129 * _tmp131 + _tmp134 * _tmp139 + _tmp147 * _tmp148);
  const Scalar _tmp150 = (Scalar(1) / Scalar(2)) * _tmp14;
  const Scalar _tmp151 = (Scalar(1) / Scalar(2)) * _tmp15;
  const Scalar _tmp152 = (Scalar(1) / Scalar(2)) * _tmp16;
  const Scalar _tmp153 = (Scalar(1) / Scalar(2)) * _tmp17;
  const Scalar _tmp154 = _tmp150 - _tmp151 - _tmp152 - _tmp153;
  const Scalar _tmp155 = Scalar(0.41999999999999998) * _tmp10;
  const Scalar _tmp156 = _tmp154 * _tmp155;
  const Scalar _tmp157 = -_tmp156;
  const Scalar _tmp158 = -Scalar(1) / Scalar(2) * _tmp20 - Scalar(1) / Scalar(2) * _tmp21 -
                         Scalar(1) / Scalar(2) * _tmp22 + (Scalar(1) / Scalar(2)) * _tmp23;
  const Scalar _tmp159 = Scalar(0.41999999999999998) * _tmp4;
  const Scalar _tmp160 = _tmp158 * _tmp159;
  const Scalar _tmp161 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp162 = (Scalar(1) / Scalar(2)) * _tmp1;
  const Scalar _tmp163 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp164 = (Scalar(1) / Scalar(2)) * _tmp3;
  const Scalar _tmp165 = -_tmp161 - _tmp162 + _tmp163 - _tmp164;
  const Scalar _tmp166 = Scalar(0.41999999999999998) * _tmp24;
  const Scalar _tmp167 = _tmp165 * _tmp166;
  const Scalar _tmp168 = -_tmp167;
  const Scalar _tmp169 = _tmp157 + _tmp160 + _tmp168;
  const Scalar _tmp170 = Scalar(0.83999999999999997) * _tmp10;
  const Scalar _tmp171 = _tmp165 * _tmp170;
  const Scalar _tmp172 = -_tmp171;
  const Scalar _tmp173 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp174 = (Scalar(1) / Scalar(2)) * _tmp7;
  const Scalar _tmp175 = (Scalar(1) / Scalar(2)) * _tmp8;
  const Scalar _tmp176 = (Scalar(1) / Scalar(2)) * _tmp9;
  const Scalar _tmp177 = _tmp173 - _tmp174 + _tmp175 + _tmp176;
  const Scalar _tmp178 = Scalar(0.41999999999999998) * _tmp18;
  const Scalar _tmp179 = _tmp177 * _tmp178;
  const Scalar _tmp180 = _tmp172 + _tmp179;
  const Scalar _tmp181 = Scalar(0.83999999999999997) * _tmp4;
  const Scalar _tmp182 = _tmp177 * _tmp181;
  const Scalar _tmp183 = Scalar(0.021999999999999999) * _tmp10;
  const Scalar _tmp184 = -_tmp158 * _tmp183;
  const Scalar _tmp185 = Scalar(0.021999999999999999) * _tmp4;
  const Scalar _tmp186 = Scalar(0.021999999999999999) * _tmp18;
  const Scalar _tmp187 = _tmp165 * _tmp186;
  const Scalar _tmp188 = Scalar(0.021999999999999999) * _tmp24;
  const Scalar _tmp189 = -_tmp154 * _tmp185 - _tmp177 * _tmp188 + _tmp184 - _tmp187;
  const Scalar _tmp190 = -_tmp182 + _tmp189;
  const Scalar _tmp191 = _tmp169 + _tmp180 + _tmp190;
  const Scalar _tmp192 = _tmp191 * _tmp94;
  const Scalar _tmp193 = -_tmp179;
  const Scalar _tmp194 = _tmp171 + _tmp193;
  const Scalar _tmp195 = -_tmp160;
  const Scalar _tmp196 = _tmp157 + _tmp195;
  const Scalar _tmp197 = _tmp168 + _tmp196;
  const Scalar _tmp198 = Scalar(0.83999999999999997) * _tmp18;
  const Scalar _tmp199 = _tmp158 * _tmp198;
  const Scalar _tmp200 = -_tmp165 * _tmp185;
  const Scalar _tmp201 = _tmp158 * _tmp188;
  const Scalar _tmp202 = _tmp154 * _tmp186 - _tmp177 * _tmp183 + _tmp200 + _tmp201;
  const Scalar _tmp203 = _tmp199 + _tmp202;
  const Scalar _tmp204 = _tmp194 + _tmp197 + _tmp203;
  const Scalar _tmp205 = 2 * _tmp43;
  const Scalar _tmp206 = _tmp182 + _tmp189;
  const Scalar _tmp207 = _tmp156 + _tmp167 + _tmp195;
  const Scalar _tmp208 = _tmp194 + _tmp206 + _tmp207;
  const Scalar _tmp209 = 2 * _tmp44;
  const Scalar _tmp210 = _tmp204 * _tmp205 + _tmp208 * _tmp209;
  const Scalar _tmp211 = std::pow(_tmp45, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp212 = (Scalar(1) / Scalar(2)) * _tmp211;
  const Scalar _tmp213 = _tmp212 * _tmp44;
  const Scalar _tmp214 = _tmp210 * _tmp213;
  const Scalar _tmp215 = _tmp112 * _tmp68;
  const Scalar _tmp216 = _tmp158 * _tmp181;
  const Scalar _tmp217 = Scalar(0.83999999999999997) * _tmp24;
  const Scalar _tmp218 = -_tmp154 * _tmp170 - _tmp165 * _tmp217 + _tmp177 * _tmp198 + _tmp216;
  const Scalar _tmp219 = _tmp102 * _tmp72;
  const Scalar _tmp220 = _tmp192 * _tmp82;
  const Scalar _tmp221 = -_tmp199 + _tmp202;
  const Scalar _tmp222 = _tmp156 + _tmp160;
  const Scalar _tmp223 = _tmp167 + _tmp222;
  const Scalar _tmp224 = _tmp180 + _tmp221 + _tmp223;
  const Scalar _tmp225 = 2 * _tmp90;
  const Scalar _tmp226 = 2 * _tmp92;
  const Scalar _tmp227 = _tmp191 * _tmp226 + _tmp224 * _tmp225;
  const Scalar _tmp228 = std::pow(_tmp93, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp229 = (Scalar(1) / Scalar(2)) * _tmp228;
  const Scalar _tmp230 = _tmp229 * _tmp90;
  const Scalar _tmp231 = _tmp227 * _tmp230;
  const Scalar _tmp232 = _tmp212 * _tmp43;
  const Scalar _tmp233 = _tmp210 * _tmp232;
  const Scalar _tmp234 = _tmp159 * _tmp165;
  const Scalar _tmp235 = _tmp158 * _tmp166;
  const Scalar _tmp236 = _tmp234 + _tmp235;
  const Scalar _tmp237 = _tmp155 * _tmp158;
  const Scalar _tmp238 = _tmp165 * _tmp178;
  const Scalar _tmp239 = -_tmp237 - _tmp238;
  const Scalar _tmp240 = _tmp236 + _tmp239;
  const Scalar _tmp241 = _tmp155 * _tmp177;
  const Scalar _tmp242 = _tmp154 * _tmp178;
  const Scalar _tmp243 = Scalar(0.043999999999999997) * _tmp4;
  const Scalar _tmp244 = _tmp177 * _tmp243;
  const Scalar _tmp245 = _tmp158 * _tmp18;
  const Scalar _tmp246 = Scalar(0.043999999999999997) * _tmp245;
  const Scalar _tmp247 = _tmp244 + _tmp246;
  const Scalar _tmp248 = _tmp241 + _tmp242 + _tmp247;
  const Scalar _tmp249 = _tmp154 * _tmp159;
  const Scalar _tmp250 = _tmp166 * _tmp177;
  const Scalar _tmp251 = _tmp249 + _tmp250;
  const Scalar _tmp252 = _tmp240 + _tmp248 + _tmp251;
  const Scalar _tmp253 = _tmp252 * _tmp66;
  const Scalar _tmp254 = _tmp208 * _tmp83;
  const Scalar _tmp255 = -_tmp242;
  const Scalar _tmp256 = -_tmp241 + _tmp255;
  const Scalar _tmp257 = -_tmp235;
  const Scalar _tmp258 = -_tmp234 + _tmp257;
  const Scalar _tmp259 = _tmp239 + _tmp258;
  const Scalar _tmp260 = _tmp247 + _tmp251 + _tmp256 + _tmp259;
  const Scalar _tmp261 = _tmp171 + _tmp179;
  const Scalar _tmp262 = _tmp169 + _tmp206 + _tmp261;
  const Scalar _tmp263 = Scalar(1.0) / (_tmp55);
  const Scalar _tmp264 = _tmp263 * _tmp53;
  const Scalar _tmp265 = _tmp262 * _tmp264;
  const Scalar _tmp266 = _tmp172 + _tmp193;
  const Scalar _tmp267 = _tmp197 + _tmp221 + _tmp266;
  const Scalar _tmp268 = _tmp267 * _tmp62;
  const Scalar _tmp269 = _tmp204 * _tmp46;
  const Scalar _tmp270 = _tmp100 * _tmp214 - _tmp233 * _tmp80 - _tmp253 * _tmp48 -
                         _tmp254 * _tmp66 + _tmp260 * _tmp47 + _tmp265 * _tmp84 - _tmp268 * _tmp84 +
                         _tmp269 * _tmp80;
  const Scalar _tmp271 = _tmp237 + _tmp238;
  const Scalar _tmp272 = _tmp236 + _tmp271;
  const Scalar _tmp273 = -_tmp249 - _tmp250;
  const Scalar _tmp274 = _tmp248 + _tmp272 + _tmp273;
  const Scalar _tmp275 = _tmp268 * _tmp82;
  const Scalar _tmp276 = _tmp224 * _tmp94;
  const Scalar _tmp277 = _tmp46 * _tmp66;
  const Scalar _tmp278 = _tmp208 * _tmp277 - _tmp214 * _tmp66 + _tmp233 - _tmp265 * _tmp48 +
                         _tmp268 * _tmp48 - _tmp269;
  const Scalar _tmp279 = std::pow(_tmp67, Scalar(-2));
  const Scalar _tmp280 = _tmp279 * _tmp85;
  const Scalar _tmp281 = _tmp280 * _tmp98;
  const Scalar _tmp282 = _tmp229 * _tmp92;
  const Scalar _tmp283 = _tmp227 * _tmp282;
  const Scalar _tmp284 =
      _tmp192 * _tmp66 + _tmp231 - _tmp265 * _tmp95 + _tmp268 * _tmp95 - _tmp276 - _tmp283 * _tmp66;
  const Scalar _tmp285 = _tmp284 * _tmp68;
  const Scalar _tmp286 = _tmp46 * _tmp80;
  const Scalar _tmp287 = -_tmp208 * _tmp286 + _tmp214 * _tmp80 - _tmp214 * _tmp82 +
                         _tmp252 * _tmp48 + _tmp254 - _tmp260 * _tmp48;
  const Scalar _tmp288 = Scalar(1.6799999999999999) * _tmp10;
  const Scalar _tmp289 = _tmp165 * _tmp288 + Scalar(1.6799999999999999) * _tmp245;
  const Scalar _tmp290 = _tmp74 / std::pow(_tmp71, Scalar(2));
  const Scalar _tmp291 = _tmp102 * _tmp290;
  const Scalar _tmp292 = _tmp279 * _tmp87;
  const Scalar _tmp293 = _tmp278 * _tmp292;
  const Scalar _tmp294 =
      -_tmp101 * _tmp192 + _tmp101 * _tmp283 - _tmp218 * _tmp219 + _tmp220 + _tmp252 * _tmp95 -
      _tmp274 * _tmp95 - _tmp283 * _tmp82 - _tmp285 * _tmp87 - _tmp287 * _tmp99 +
      _tmp289 * _tmp291 + _tmp293 * _tmp98 -
      _tmp75 * (_tmp100 * _tmp283 - _tmp101 * _tmp231 + _tmp101 * _tmp276 - _tmp220 * _tmp66 -
                _tmp253 * _tmp95 + _tmp265 * _tmp96 - _tmp270 * _tmp99 + _tmp274 * _tmp97 -
                _tmp275 * _tmp95 + _tmp278 * _tmp281 - _tmp285 * _tmp85);
  const Scalar _tmp295 = std::pow(_tmp103, Scalar(-2));
  const Scalar _tmp296 = _tmp294 * _tmp295;
  const Scalar _tmp297 = _tmp296 * _tmp95;
  const Scalar _tmp298 = _tmp282 * _tmp89;
  const Scalar _tmp299 = _tmp263 * _tmp57;
  const Scalar _tmp300 = _tmp299 * _tmp61;
  const Scalar _tmp301 = _tmp262 * _tmp300;
  const Scalar _tmp302 = _tmp42 * _tmp46;
  const Scalar _tmp303 = _tmp58 * _tmp62;
  const Scalar _tmp304 = _tmp303 * _tmp61;
  const Scalar _tmp305 = 2 * _tmp54;
  const Scalar _tmp306 = 2 * _tmp53;
  const Scalar _tmp307 =
      (Scalar(1) / Scalar(2)) * _tmp262 * _tmp305 + (Scalar(1) / Scalar(2)) * _tmp267 * _tmp306;
  const Scalar _tmp308 = _tmp304 * _tmp307;
  const Scalar _tmp309 = _tmp46 * _tmp64;
  const Scalar _tmp310 = _tmp54 * _tmp58;
  const Scalar _tmp311 = _tmp50 * _tmp53;
  const Scalar _tmp312 = std::pow(_tmp56, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp313 = _tmp307 * _tmp312;
  const Scalar _tmp314 = _tmp52 * _tmp54;
  const Scalar _tmp315 = _tmp50 * _tmp58;
  const Scalar _tmp316 = _tmp63 * (_tmp262 * _tmp59 - _tmp262 * _tmp60 - _tmp267 * _tmp310 +
                                   _tmp267 * _tmp315 - _tmp311 * _tmp313 + _tmp313 * _tmp314);
  const Scalar _tmp317 = _tmp208 * _tmp302 + _tmp208 * _tmp309 - _tmp208 * _tmp47 -
                         _tmp214 * _tmp42 - _tmp214 * _tmp64 + _tmp233 * _tmp33 - _tmp269 * _tmp33 +
                         _tmp269 * _tmp44 - _tmp301 * _tmp48 + _tmp308 * _tmp48 + _tmp316 * _tmp48;
  const Scalar _tmp318 = _tmp279 * _tmp65;
  const Scalar _tmp319 = _tmp318 * _tmp98;
  const Scalar _tmp320 = -_tmp191 * _tmp97 + _tmp192 * _tmp64 + _tmp192 * _tmp89 -
                         _tmp227 * _tmp298 + _tmp231 * _tmp91 - _tmp276 * _tmp91 +
                         _tmp276 * _tmp92 + _tmp278 * _tmp319 - _tmp283 * _tmp64 -
                         _tmp285 * _tmp65 - _tmp301 * _tmp95 + _tmp308 * _tmp95 + _tmp316 * _tmp95 -
                         _tmp317 * _tmp99;
  const Scalar _tmp321 = std::pow(_tmp105, Scalar(-2));
  const Scalar _tmp322 = _tmp103 * _tmp321;
  const Scalar _tmp323 = _tmp107 * _tmp322;
  const Scalar _tmp324 = _tmp104 * _tmp88;
  const Scalar _tmp325 = Scalar(1.0) * _tmp318;
  const Scalar _tmp326 = _tmp105 * _tmp88;
  const Scalar _tmp327 = Scalar(1.0) * _tmp280 * _tmp75;
  const Scalar _tmp328 = _tmp72 * _tmp86;
  const Scalar _tmp329 = _tmp290 * _tmp86;
  const Scalar _tmp330 = _tmp69 * _tmp75;
  const Scalar _tmp331 = _tmp218 * _tmp328 + _tmp270 * _tmp330 - _tmp278 * _tmp327 -
                         _tmp287 * _tmp69 - _tmp289 * _tmp329 + Scalar(1.0) * _tmp293;
  const Scalar _tmp332 = _tmp107 * _tmp108;
  const Scalar _tmp333 = _tmp109 * (-_tmp106 * _tmp331 + _tmp278 * _tmp325 + _tmp296 * _tmp326 -
                                    _tmp317 * _tmp69 - _tmp320 * _tmp324) +
                         _tmp294 * _tmp332 - _tmp320 * _tmp323 + _tmp331;
  const Scalar _tmp334 = _tmp46 * _tmp68;
  const Scalar _tmp335 = _tmp112 * _tmp334;
  const Scalar _tmp336 = _tmp279 * _tmp48;
  const Scalar _tmp337 = _tmp112 * _tmp336;
  const Scalar _tmp338 = _tmp295 * _tmp98;
  const Scalar _tmp339 = _tmp294 * _tmp338;
  const Scalar _tmp340 = _tmp110 * _tmp339 - _tmp111 * _tmp333 - _tmp114 * _tmp284;
  const Scalar _tmp341 = _tmp134 * _tmp138;
  const Scalar _tmp342 = _tmp299 * _tmp341;
  const Scalar _tmp343 = _tmp190 + _tmp207 + _tmp266;
  const Scalar _tmp344 = 2 * _tmp119;
  const Scalar _tmp345 = _tmp203 + _tmp223 + _tmp261;
  const Scalar _tmp346 = 2 * _tmp117;
  const Scalar _tmp347 = (Scalar(1) / Scalar(2)) / (_tmp120 * std::sqrt(_tmp120));
  const Scalar _tmp348 = _tmp347 * (_tmp343 * _tmp344 + _tmp345 * _tmp346);
  const Scalar _tmp349 = _tmp119 * _tmp348;
  const Scalar _tmp350 = _tmp123 * _tmp147;
  const Scalar _tmp351 = Scalar(1.0) * _tmp321;
  const Scalar _tmp352 = _tmp351 * _tmp95;
  const Scalar _tmp353 = _tmp132 * _tmp48;
  const Scalar _tmp354 = _tmp133 * _tmp46;
  const Scalar _tmp355 = _tmp48 * _tmp99;
  const Scalar _tmp356 = _tmp351 * _tmp355;
  const Scalar _tmp357 = Scalar(0.5) * _tmp108;
  const Scalar _tmp358 = _tmp211 * _tmp357 * _tmp44 * _tmp99;
  const Scalar _tmp359 = _tmp228 * _tmp357 * _tmp92;
  const Scalar _tmp360 = _tmp278 * _tmp336;
  const Scalar _tmp361 = _tmp132 * _tmp98;
  const Scalar _tmp362 = _tmp129 * _tmp130;
  const Scalar _tmp363 = _tmp299 * _tmp362;
  const Scalar _tmp364 = _tmp303 * _tmp362;
  const Scalar _tmp365 = _tmp121 * fh1;
  const Scalar _tmp366 = _tmp115 * _tmp63;
  const Scalar _tmp367 = _tmp365 * _tmp366;
  const Scalar _tmp368 = _tmp122 * fh1;
  const Scalar _tmp369 = _tmp115 * _tmp368;
  const Scalar _tmp370 = _tmp303 * _tmp369;
  const Scalar _tmp371 = _tmp128 * _tmp68;
  const Scalar _tmp372 = _tmp104 * _tmp126;
  const Scalar _tmp373 = _tmp372 * _tmp48;
  const Scalar _tmp374 = _tmp126 * _tmp355;
  const Scalar _tmp375 = _tmp128 * _tmp334;
  const Scalar _tmp376 = _tmp136 * fh1;
  const Scalar _tmp377 = _tmp147 * _tmp376;
  const Scalar _tmp378 = _tmp262 * _tmp299;
  const Scalar _tmp379 = _tmp303 * _tmp377;
  const Scalar _tmp380 = _tmp115 * _tmp123;
  const Scalar _tmp381 = _tmp117 * _tmp380;
  const Scalar _tmp382 = _tmp303 * _tmp341;
  const Scalar _tmp383 = _tmp343 * _tmp365;
  const Scalar _tmp384 = _tmp147 * _tmp63;
  const Scalar _tmp385 = _tmp116 * _tmp121;
  const Scalar _tmp386 = _tmp117 * _tmp118;
  const Scalar _tmp387 = _tmp116 * _tmp119;
  const Scalar _tmp388 = _tmp122 * _tmp343 + _tmp135 * _tmp345 - _tmp136 * _tmp345 -
                         _tmp343 * _tmp385 - _tmp348 * _tmp386 + _tmp348 * _tmp387;
  const Scalar _tmp389 = _tmp123 * _tmp134;
  const Scalar _tmp390 = _tmp145 * _tmp336;
  const Scalar _tmp391 = _tmp143 * _tmp322;
  const Scalar _tmp392 = _tmp108 * _tmp143;
  const Scalar _tmp393 = _tmp105 * _tmp142;
  const Scalar _tmp394 = _tmp141 * _tmp72;
  const Scalar _tmp395 = _tmp141 * _tmp290;
  const Scalar _tmp396 = _tmp68 * _tmp87;
  const Scalar _tmp397 = _tmp268 * _tmp68;
  const Scalar _tmp398 = _tmp280 * _tmp66;
  const Scalar _tmp399 = _tmp68 * _tmp85;
  const Scalar _tmp400 = _tmp258 + _tmp271;
  const Scalar _tmp401 =
      _tmp140 * _tmp287 - _tmp218 * _tmp394 - _tmp244 - _tmp246 + _tmp256 - _tmp265 * _tmp396 +
      _tmp273 + _tmp289 * _tmp395 - _tmp293 * _tmp66 + _tmp397 * _tmp87 + _tmp400 -
      _tmp75 * (_tmp140 * _tmp270 + _tmp253 - _tmp265 * _tmp399 - _tmp265 * _tmp82 + _tmp275 -
                _tmp278 * _tmp398 + _tmp397 * _tmp85);
  const Scalar _tmp402 = _tmp104 * _tmp142;
  const Scalar _tmp403 = _tmp318 * _tmp66;
  const Scalar _tmp404 = _tmp65 * _tmp68;
  const Scalar _tmp405 = _tmp109 * (-_tmp106 * _tmp401 + _tmp140 * _tmp317 - _tmp265 * _tmp404 -
                                    _tmp278 * _tmp403 + _tmp296 * _tmp393 + _tmp301 - _tmp308 -
                                    _tmp316 - _tmp320 * _tmp402 + _tmp397 * _tmp65) +
                         _tmp294 * _tmp392 - _tmp320 * _tmp391 + _tmp401;
  const Scalar _tmp406 =
      -_tmp111 * _tmp405 + _tmp144 * _tmp339 - _tmp146 * _tmp284 + _tmp265 - _tmp268;
  const Scalar _tmp407 = _tmp145 * _tmp68;
  const Scalar _tmp408 = _tmp145 * _tmp334;
  const Scalar _tmp409 = _tmp126 * _tmp130;
  const Scalar _tmp410 = _tmp111 * _tmp409;
  const Scalar _tmp411 = _tmp68 * fh1;
  const Scalar _tmp412 = _tmp136 * _tmp411;
  const Scalar _tmp413 = _tmp132 * fh1;
  const Scalar _tmp414 = _tmp137 * _tmp413;
  const Scalar _tmp415 = _tmp122 * _tmp411;
  const Scalar _tmp416 =
      std::exp(-_tmp112 * _tmp415 - _tmp145 * _tmp412 + _tmp410 * _tmp68 + _tmp414 * _tmp99);
  const Scalar _tmp417 = _tmp348 * _tmp411;
  const Scalar _tmp418 = _tmp112 * _tmp117;
  const Scalar _tmp419 = _tmp278 * _tmp279;
  const Scalar _tmp420 = _tmp119 * _tmp145;
  const Scalar _tmp421 = _tmp104 * _tmp409;
  const Scalar _tmp422 = _tmp215 * _tmp365;
  const Scalar _tmp423 = _tmp112 * _tmp368;
  const Scalar _tmp424 = _tmp414 * _tmp98;
  const Scalar _tmp425 = _tmp388 * _tmp413;
  const Scalar _tmp426 = _tmp296 * _tmp409;
  const Scalar _tmp427 = _tmp138 * _tmp351;
  const Scalar _tmp428 = _tmp320 * _tmp427;
  const Scalar _tmp429 = _tmp145 * _tmp376;
  const Scalar _tmp430 = std::exp(-_tmp114 * _tmp368 - _tmp146 * _tmp376 - _tmp414 - _tmp421);
  const Scalar _tmp431 = _tmp114 * _tmp365;
  const Scalar _tmp432 = _tmp104 * fh1;
  const Scalar _tmp433 = _tmp122 * _tmp432;
  const Scalar _tmp434 = _tmp144 * _tmp376;
  const Scalar _tmp435 = _tmp146 * fh1;
  const Scalar _tmp436 = _tmp110 * _tmp368;
  const Scalar _tmp437 = _tmp136 * _tmp432;
  const Scalar _tmp438 = _tmp114 * fh1;
  const Scalar _tmp439 = _tmp117 * _tmp438;
  const Scalar _tmp440 = -_tmp150 + _tmp151 + _tmp152 + _tmp153;
  const Scalar _tmp441 = _tmp170 * _tmp440;
  const Scalar _tmp442 = _tmp155 * _tmp165;
  const Scalar _tmp443 = _tmp166 * _tmp440;
  const Scalar _tmp444 = -_tmp442 - _tmp443;
  const Scalar _tmp445 = _tmp441 + _tmp444;
  const Scalar _tmp446 = -_tmp173 + _tmp174 - _tmp175 - _tmp176;
  const Scalar _tmp447 = _tmp159 * _tmp446;
  const Scalar _tmp448 = Scalar(0.41999999999999998) * _tmp245;
  const Scalar _tmp449 = _tmp447 + _tmp448;
  const Scalar _tmp450 = -_tmp183 * _tmp446 - _tmp186 * _tmp440 + _tmp200 - _tmp201;
  const Scalar _tmp451 = _tmp449 + _tmp450;
  const Scalar _tmp452 = _tmp216 + _tmp445 + _tmp451;
  const Scalar _tmp453 = _tmp299 * _tmp452;
  const Scalar _tmp454 = _tmp442 + _tmp443;
  const Scalar _tmp455 = _tmp441 + _tmp454;
  const Scalar _tmp456 = -_tmp448;
  const Scalar _tmp457 = -_tmp447;
  const Scalar _tmp458 = _tmp456 + _tmp457;
  const Scalar _tmp459 = _tmp450 + _tmp458;
  const Scalar _tmp460 = _tmp216 + _tmp455 + _tmp459;
  const Scalar _tmp461 = _tmp198 * _tmp446;
  const Scalar _tmp462 = _tmp184 - _tmp185 * _tmp440 + _tmp187 + _tmp188 * _tmp446;
  const Scalar _tmp463 = _tmp461 + _tmp462;
  const Scalar _tmp464 = _tmp445 + _tmp458 + _tmp463;
  const Scalar _tmp465 = _tmp205 * _tmp464 + _tmp209 * _tmp460;
  const Scalar _tmp466 = _tmp232 * _tmp465;
  const Scalar _tmp467 = _tmp264 * _tmp452;
  const Scalar _tmp468 = -_tmp441;
  const Scalar _tmp469 = _tmp444 + _tmp468;
  const Scalar _tmp470 = -_tmp461 + _tmp462;
  const Scalar _tmp471 = _tmp458 + _tmp469 + _tmp470;
  const Scalar _tmp472 = _tmp471 * _tmp62;
  const Scalar _tmp473 = _tmp46 * _tmp464;
  const Scalar _tmp474 = _tmp213 * _tmp465;
  const Scalar _tmp475 = _tmp277 * _tmp460 + _tmp466 - _tmp467 * _tmp48 + _tmp472 * _tmp48 -
                         _tmp473 - _tmp474 * _tmp66;
  const Scalar _tmp476 = _tmp454 + _tmp468;
  const Scalar _tmp477 = _tmp449 + _tmp470 + _tmp476;
  const Scalar _tmp478 = -_tmp216;
  const Scalar _tmp479 = _tmp451 + _tmp469 + _tmp478;
  const Scalar _tmp480 = _tmp225 * _tmp477 + _tmp226 * _tmp479;
  const Scalar _tmp481 = _tmp477 * _tmp94;
  const Scalar _tmp482 = _tmp230 * _tmp480;
  const Scalar _tmp483 =
      (Scalar(1) / Scalar(2)) * _tmp305 * _tmp452 + (Scalar(1) / Scalar(2)) * _tmp306 * _tmp471;
  const Scalar _tmp484 = _tmp312 * _tmp483;
  const Scalar _tmp485 = _tmp63 * (-_tmp310 * _tmp471 - _tmp311 * _tmp484 + _tmp314 * _tmp484 +
                                   _tmp315 * _tmp471 + _tmp452 * _tmp59 - _tmp452 * _tmp60);
  const Scalar _tmp486 = _tmp479 * _tmp94;
  const Scalar _tmp487 = _tmp282 * _tmp480;
  const Scalar _tmp488 = -_tmp467 * _tmp95 + _tmp472 * _tmp95 - _tmp481 + _tmp482 +
                         _tmp486 * _tmp66 - _tmp487 * _tmp66;
  const Scalar _tmp489 = _tmp488 * _tmp68;
  const Scalar _tmp490 = _tmp304 * _tmp483;
  const Scalar _tmp491 = _tmp300 * _tmp452;
  const Scalar _tmp492 = _tmp302 * _tmp460 + _tmp309 * _tmp460 + _tmp33 * _tmp466 -
                         _tmp33 * _tmp473 - _tmp42 * _tmp474 + _tmp44 * _tmp473 - _tmp460 * _tmp47 -
                         _tmp474 * _tmp64 + _tmp48 * _tmp485 + _tmp48 * _tmp490 - _tmp48 * _tmp491;
  const Scalar _tmp493 = -_tmp298 * _tmp480 + _tmp319 * _tmp475 - _tmp479 * _tmp97 -
                         _tmp481 * _tmp91 + _tmp481 * _tmp92 + _tmp482 * _tmp91 + _tmp485 * _tmp95 +
                         _tmp486 * _tmp64 + _tmp486 * _tmp89 - _tmp487 * _tmp64 - _tmp489 * _tmp65 +
                         _tmp490 * _tmp95 - _tmp491 * _tmp95 - _tmp492 * _tmp99;
  const Scalar _tmp494 = _tmp449 + _tmp455 + _tmp463;
  const Scalar _tmp495 = _tmp365 * _tmp494;
  const Scalar _tmp496 = _tmp128 * _tmp336;
  const Scalar _tmp497 = _tmp172 + _tmp181 * _tmp446 + _tmp199 - _tmp217 * _tmp440;
  const Scalar _tmp498 = _tmp292 * _tmp475;
  const Scalar _tmp499 = Scalar(1.6799999999999999) * _tmp18;
  const Scalar _tmp500 = _tmp288 * _tmp440 + _tmp446 * _tmp499;
  const Scalar _tmp501 = _tmp159 * _tmp440;
  const Scalar _tmp502 = _tmp158 * _tmp243;
  const Scalar _tmp503 = Scalar(0.043999999999999997) * _tmp18;
  const Scalar _tmp504 = _tmp446 * _tmp503;
  const Scalar _tmp505 = _tmp166 * _tmp446;
  const Scalar _tmp506 = _tmp501 + _tmp502 + _tmp504 + _tmp505;
  const Scalar _tmp507 = _tmp155 * _tmp446;
  const Scalar _tmp508 = _tmp178 * _tmp440;
  const Scalar _tmp509 = _tmp507 + _tmp508;
  const Scalar _tmp510 = _tmp400 + _tmp506 + _tmp509;
  const Scalar _tmp511 = -_tmp507;
  const Scalar _tmp512 = -_tmp508 + _tmp511;
  const Scalar _tmp513 = _tmp272 + _tmp506 + _tmp512;
  const Scalar _tmp514 = _tmp513 * _tmp95;
  const Scalar _tmp515 = -_tmp501 - _tmp505;
  const Scalar _tmp516 = _tmp240 + _tmp502 + _tmp504 + _tmp512 + _tmp515;
  const Scalar _tmp517 = _tmp48 * _tmp513;
  const Scalar _tmp518 = _tmp460 * _tmp83;
  const Scalar _tmp519 = _tmp100 * _tmp474 - _tmp466 * _tmp80 + _tmp467 * _tmp84 +
                         _tmp47 * _tmp516 - _tmp472 * _tmp84 + _tmp473 * _tmp80 - _tmp517 * _tmp66 -
                         _tmp518 * _tmp66;
  const Scalar _tmp520 = -_tmp286 * _tmp460 + _tmp474 * _tmp80 - _tmp474 * _tmp82 -
                         _tmp48 * _tmp516 + _tmp517 + _tmp518;
  const Scalar _tmp521 =
      -_tmp101 * _tmp486 + _tmp101 * _tmp487 - _tmp219 * _tmp497 + _tmp291 * _tmp500 +
      _tmp486 * _tmp82 - _tmp487 * _tmp82 - _tmp489 * _tmp87 + _tmp498 * _tmp98 - _tmp510 * _tmp95 +
      _tmp514 - _tmp520 * _tmp99 -
      _tmp75 * (-_tmp100 * _tmp486 + _tmp100 * _tmp487 + _tmp101 * _tmp481 - _tmp101 * _tmp482 +
                _tmp281 * _tmp475 + _tmp467 * _tmp96 - _tmp472 * _tmp96 - _tmp489 * _tmp85 +
                _tmp510 * _tmp97 - _tmp514 * _tmp66 - _tmp519 * _tmp99);
  const Scalar _tmp522 = _tmp295 * _tmp521;
  const Scalar _tmp523 = _tmp522 * _tmp95;
  const Scalar _tmp524 = _tmp334 * _tmp460;
  const Scalar _tmp525 = _tmp459 + _tmp476 + _tmp478;
  const Scalar _tmp526 = _tmp347 * (_tmp344 * _tmp525 + _tmp346 * _tmp494);
  const Scalar _tmp527 = _tmp119 * _tmp350;
  const Scalar _tmp528 = _tmp472 * _tmp68;
  const Scalar _tmp529 =
      _tmp140 * _tmp520 + _tmp259 - _tmp394 * _tmp497 + _tmp395 * _tmp500 - _tmp396 * _tmp467 -
      _tmp498 * _tmp66 - _tmp502 - _tmp504 + _tmp509 + _tmp515 + _tmp528 * _tmp87 -
      _tmp75 * (_tmp140 * _tmp519 - _tmp398 * _tmp475 - _tmp399 * _tmp467 - _tmp467 * _tmp82 +
                _tmp472 * _tmp82 + _tmp513 * _tmp66 + _tmp528 * _tmp85);
  const Scalar _tmp530 = _tmp322 * _tmp493;
  const Scalar _tmp531 = _tmp109 * (-_tmp106 * _tmp529 + _tmp140 * _tmp492 + _tmp393 * _tmp522 -
                                    _tmp402 * _tmp493 - _tmp403 * _tmp475 - _tmp404 * _tmp467 -
                                    _tmp485 - _tmp490 + _tmp491 + _tmp528 * _tmp65) -
                         _tmp143 * _tmp530 + _tmp392 * _tmp521 + _tmp529;
  const Scalar _tmp532 = _tmp338 * _tmp521;
  const Scalar _tmp533 =
      -_tmp111 * _tmp531 + _tmp144 * _tmp532 - _tmp146 * _tmp488 + _tmp467 - _tmp472;
  const Scalar _tmp534 = -_tmp327 * _tmp475 + _tmp328 * _tmp497 - _tmp329 * _tmp500 +
                         _tmp330 * _tmp519 + Scalar(1.0) * _tmp498 - _tmp520 * _tmp69;
  const Scalar _tmp535 = -_tmp107 * _tmp530 +
                         _tmp109 * (-_tmp106 * _tmp534 - _tmp324 * _tmp493 + _tmp325 * _tmp475 +
                                    _tmp326 * _tmp522 - _tmp492 * _tmp69) +
                         _tmp332 * _tmp521 + _tmp534;
  const Scalar _tmp536 = _tmp110 * _tmp532 - _tmp111 * _tmp535 - _tmp114 * _tmp488;
  const Scalar _tmp537 = _tmp122 * _tmp525 + _tmp135 * _tmp494 - _tmp136 * _tmp494 -
                         _tmp385 * _tmp525 - _tmp386 * _tmp526 + _tmp387 * _tmp526;
  const Scalar _tmp538 = _tmp117 * _tmp526;
  const Scalar _tmp539 = _tmp365 * _tmp525;
  const Scalar _tmp540 = _tmp411 * _tmp420;
  const Scalar _tmp541 = _tmp279 * _tmp475;
  const Scalar _tmp542 = _tmp427 * _tmp493;
  const Scalar _tmp543 = _tmp409 * _tmp522;
  const Scalar _tmp544 = _tmp413 * _tmp537;
  const Scalar _tmp545 = _tmp119 * _tmp435;
  const Scalar _tmp546 = _tmp161 + _tmp162 - _tmp163 + _tmp164;
  const Scalar _tmp547 = _tmp159 * _tmp546;
  const Scalar _tmp548 = _tmp255 - _tmp547;
  const Scalar _tmp549 = _tmp158 * _tmp170;
  const Scalar _tmp550 = _tmp257 + _tmp511;
  const Scalar _tmp551 = _tmp549 + _tmp550;
  const Scalar _tmp552 = _tmp198 * _tmp546;
  const Scalar _tmp553 =
      -_tmp154 * _tmp183 - _tmp158 * _tmp185 + _tmp186 * _tmp446 + _tmp188 * _tmp546;
  const Scalar _tmp554 = _tmp552 + _tmp553;
  const Scalar _tmp555 = _tmp548 + _tmp551 + _tmp554;
  const Scalar _tmp556 = _tmp235 + _tmp507;
  const Scalar _tmp557 = _tmp549 + _tmp556;
  const Scalar _tmp558 = _tmp154 * _tmp181;
  const Scalar _tmp559 = -_tmp154 * _tmp188 - _tmp183 * _tmp546 - _tmp185 * _tmp446 -
                         Scalar(0.021999999999999999) * _tmp245;
  const Scalar _tmp560 = _tmp558 + _tmp559;
  const Scalar _tmp561 = _tmp548 + _tmp557 + _tmp560;
  const Scalar _tmp562 = _tmp205 * _tmp555 + _tmp209 * _tmp561;
  const Scalar _tmp563 = _tmp213 * _tmp562;
  const Scalar _tmp564 = _tmp242 + _tmp547;
  const Scalar _tmp565 = _tmp551 + _tmp560 + _tmp564;
  const Scalar _tmp566 = _tmp264 * _tmp565;
  const Scalar _tmp567 = _tmp232 * _tmp562;
  const Scalar _tmp568 = -_tmp549;
  const Scalar _tmp569 = _tmp548 + _tmp568;
  const Scalar _tmp570 = -_tmp552 + _tmp553;
  const Scalar _tmp571 = _tmp550 + _tmp569 + _tmp570;
  const Scalar _tmp572 = _tmp571 * _tmp62;
  const Scalar _tmp573 = _tmp46 * _tmp555;
  const Scalar _tmp574 = _tmp277 * _tmp561 - _tmp48 * _tmp566 + _tmp48 * _tmp572 -
                         _tmp563 * _tmp66 + _tmp567 - _tmp573;
  const Scalar _tmp575 = _tmp574 * _tmp98;
  const Scalar _tmp576 = _tmp300 * _tmp565;
  const Scalar _tmp577 =
      (Scalar(1) / Scalar(2)) * _tmp305 * _tmp565 + (Scalar(1) / Scalar(2)) * _tmp306 * _tmp571;
  const Scalar _tmp578 = _tmp312 * _tmp577;
  const Scalar _tmp579 = _tmp63 * (-_tmp310 * _tmp571 - _tmp311 * _tmp578 + _tmp314 * _tmp578 +
                                   _tmp315 * _tmp571 + _tmp565 * _tmp59 - _tmp565 * _tmp60);
  const Scalar _tmp580 = _tmp304 * _tmp577;
  const Scalar _tmp581 = _tmp302 * _tmp561 + _tmp309 * _tmp561 + _tmp33 * _tmp567 -
                         _tmp33 * _tmp573 - _tmp42 * _tmp563 + _tmp44 * _tmp573 - _tmp47 * _tmp561 -
                         _tmp48 * _tmp576 + _tmp48 * _tmp579 + _tmp48 * _tmp580 - _tmp563 * _tmp64;
  const Scalar _tmp582 = _tmp564 + _tmp568;
  const Scalar _tmp583 = -_tmp558 + _tmp559;
  const Scalar _tmp584 = _tmp550 + _tmp582 + _tmp583;
  const Scalar _tmp585 = _tmp584 * _tmp94;
  const Scalar _tmp586 = _tmp556 + _tmp570 + _tmp582;
  const Scalar _tmp587 = _tmp586 * _tmp94;
  const Scalar _tmp588 = _tmp225 * _tmp586 + _tmp226 * _tmp584;
  const Scalar _tmp589 = _tmp230 * _tmp588;
  const Scalar _tmp590 = _tmp282 * _tmp588;
  const Scalar _tmp591 = -_tmp566 * _tmp95 + _tmp572 * _tmp95 + _tmp585 * _tmp66 - _tmp587 +
                         _tmp589 - _tmp590 * _tmp66;
  const Scalar _tmp592 = _tmp591 * _tmp68;
  const Scalar _tmp593 = _tmp318 * _tmp575 - _tmp576 * _tmp95 + _tmp579 * _tmp95 +
                         _tmp580 * _tmp95 - _tmp581 * _tmp99 - _tmp584 * _tmp97 + _tmp585 * _tmp64 +
                         _tmp585 * _tmp89 - _tmp587 * _tmp91 + _tmp587 * _tmp92 + _tmp589 * _tmp91 -
                         _tmp590 * _tmp64 - _tmp590 * _tmp89 - _tmp592 * _tmp65;
  const Scalar _tmp594 = _tmp556 + _tmp569 + _tmp583;
  const Scalar _tmp595 = _tmp365 * _tmp594;
  const Scalar _tmp596 = _tmp303 * _tmp577;
  const Scalar _tmp597 = _tmp154 * _tmp243;
  const Scalar _tmp598 = _tmp503 * _tmp546;
  const Scalar _tmp599 = _tmp597 + _tmp598;
  const Scalar _tmp600 = _tmp178 * _tmp446;
  const Scalar _tmp601 = _tmp166 * _tmp546;
  const Scalar _tmp602 = _tmp222 + _tmp600 + _tmp601;
  const Scalar _tmp603 = _tmp155 * _tmp546;
  const Scalar _tmp604 = _tmp154 * _tmp166;
  const Scalar _tmp605 = _tmp448 + _tmp457 + _tmp603 - _tmp604;
  const Scalar _tmp606 = _tmp599 + _tmp602 + _tmp605;
  const Scalar _tmp607 = _tmp447 + _tmp456 + _tmp599 - _tmp603 + _tmp604;
  const Scalar _tmp608 = _tmp602 + _tmp607;
  const Scalar _tmp609 =
      _tmp154 * _tmp198 - _tmp158 * _tmp217 - _tmp170 * _tmp446 + _tmp181 * _tmp546;
  const Scalar _tmp610 = _tmp196 - _tmp600 - _tmp601;
  const Scalar _tmp611 = _tmp607 + _tmp610;
  const Scalar _tmp612 = _tmp48 * _tmp608;
  const Scalar _tmp613 = _tmp561 * _tmp83;
  const Scalar _tmp614 = -_tmp286 * _tmp561 - _tmp48 * _tmp611 + _tmp563 * _tmp80 -
                         _tmp563 * _tmp82 + _tmp612 + _tmp613;
  const Scalar _tmp615 = _tmp100 * _tmp563 + _tmp47 * _tmp611 + _tmp566 * _tmp84 -
                         _tmp567 * _tmp80 - _tmp572 * _tmp84 + _tmp573 * _tmp80 - _tmp612 * _tmp66 -
                         _tmp613 * _tmp66;
  const Scalar _tmp616 = _tmp608 * _tmp66;
  const Scalar _tmp617 = _tmp572 * _tmp82;
  const Scalar _tmp618 = _tmp158 * _tmp288 + _tmp499 * _tmp546;
  const Scalar _tmp619 =
      -_tmp101 * _tmp585 + _tmp101 * _tmp590 - _tmp219 * _tmp609 + _tmp291 * _tmp618 +
      _tmp292 * _tmp575 + _tmp585 * _tmp82 - _tmp590 * _tmp82 - _tmp592 * _tmp87 -
      _tmp606 * _tmp95 + _tmp608 * _tmp95 - _tmp614 * _tmp99 -
      _tmp75 * (-_tmp100 * _tmp585 + _tmp100 * _tmp590 + _tmp101 * _tmp587 - _tmp101 * _tmp589 +
                _tmp280 * _tmp575 + _tmp566 * _tmp96 - _tmp592 * _tmp85 + _tmp606 * _tmp97 -
                _tmp615 * _tmp99 - _tmp616 * _tmp95 - _tmp617 * _tmp95);
  const Scalar _tmp620 = _tmp292 * _tmp574;
  const Scalar _tmp621 = -_tmp327 * _tmp574 + _tmp328 * _tmp609 - _tmp329 * _tmp618 +
                         _tmp330 * _tmp615 - _tmp614 * _tmp69 + Scalar(1.0) * _tmp620;
  const Scalar _tmp622 = _tmp295 * _tmp619;
  const Scalar _tmp623 = _tmp109 * (-_tmp106 * _tmp621 - _tmp324 * _tmp593 + _tmp325 * _tmp574 +
                                    _tmp326 * _tmp622 - _tmp581 * _tmp69) -
                         _tmp323 * _tmp593 + _tmp332 * _tmp619 + _tmp621;
  const Scalar _tmp624 = _tmp622 * _tmp95;
  const Scalar _tmp625 = _tmp338 * _tmp619;
  const Scalar _tmp626 = _tmp110 * _tmp625 - _tmp111 * _tmp623 - _tmp114 * _tmp591;
  const Scalar _tmp627 = _tmp572 * _tmp68;
  const Scalar _tmp628 = _tmp140 * _tmp614 - _tmp394 * _tmp609 + _tmp395 * _tmp618 -
                         _tmp396 * _tmp566 - _tmp597 - _tmp598 + _tmp605 + _tmp610 -
                         _tmp620 * _tmp66 + _tmp627 * _tmp87 -
                         _tmp75 * (_tmp140 * _tmp615 - _tmp398 * _tmp574 - _tmp399 * _tmp566 -
                                   _tmp566 * _tmp82 + _tmp616 + _tmp617 + _tmp627 * _tmp85);
  const Scalar _tmp629 = _tmp109 * (-_tmp106 * _tmp628 + _tmp140 * _tmp581 + _tmp393 * _tmp622 -
                                    _tmp402 * _tmp593 - _tmp403 * _tmp574 - _tmp404 * _tmp566 +
                                    _tmp576 - _tmp579 - _tmp580 + _tmp627 * _tmp65) -
                         _tmp391 * _tmp593 + _tmp392 * _tmp619 + _tmp628;
  const Scalar _tmp630 =
      -_tmp111 * _tmp629 + _tmp144 * _tmp625 - _tmp146 * _tmp591 + _tmp566 - _tmp572;
  const Scalar _tmp631 = _tmp554 + _tmp557 + _tmp564;
  const Scalar _tmp632 = _tmp347 * (_tmp344 * _tmp594 + _tmp346 * _tmp631);
  const Scalar _tmp633 = _tmp122 * _tmp594 + _tmp135 * _tmp631 - _tmp136 * _tmp631 -
                         _tmp385 * _tmp594 - _tmp386 * _tmp632 + _tmp387 * _tmp632;
  const Scalar _tmp634 = _tmp299 * _tmp565;
  const Scalar _tmp635 = _tmp279 * _tmp574;
  const Scalar _tmp636 = _tmp427 * _tmp593;
  const Scalar _tmp637 = _tmp409 * _tmp622;
  const Scalar _tmp638 = _tmp413 * _tmp633;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = 0;
  _res(1, 0) =
      -_tmp149 *
      (-_tmp124 * (-_tmp110 * _tmp297 + _tmp113 * _tmp340 + _tmp114 * _tmp192 - _tmp114 * _tmp283 +
                   _tmp127 * _tmp333 + _tmp208 * _tmp335 - _tmp214 * _tmp215 - _tmp278 * _tmp337) -
       _tmp131 * (-_tmp126 * _tmp297 + _tmp128 * _tmp360 + _tmp192 * _tmp372 - _tmp208 * _tmp375 +
                  _tmp214 * _tmp371 - _tmp283 * _tmp372 - _tmp285 * _tmp373 + _tmp296 * _tmp374) -
       _tmp139 * (_tmp132 * _tmp192 - _tmp208 * _tmp354 + _tmp210 * _tmp358 - _tmp227 * _tmp359 -
                  _tmp285 * _tmp353 - _tmp320 * _tmp352 + _tmp320 * _tmp356 + _tmp360 * _tmp361) -
       _tmp148 * (_tmp113 * _tmp406 + _tmp127 * _tmp405 - _tmp144 * _tmp297 + _tmp146 * _tmp192 -
                  _tmp146 * _tmp283 + _tmp208 * _tmp408 - _tmp214 * _tmp407 - _tmp278 * _tmp390) +
       _tmp262 * _tmp342 + _tmp262 * _tmp363 - _tmp307 * _tmp364 - _tmp307 * _tmp370 -
       _tmp307 * _tmp379 - _tmp307 * _tmp382 - _tmp345 * _tmp367 + _tmp348 * _tmp381 +
       _tmp349 * _tmp350 + _tmp369 * _tmp378 + _tmp377 * _tmp378 - _tmp383 * _tmp384 -
       _tmp388 * _tmp389);
  _res(2, 0) =
      -_tmp416 * (-_tmp285 * _tmp414 - _tmp285 * _tmp421 + _tmp340 * _tmp415 + _tmp345 * _tmp422 +
                  _tmp383 * _tmp407 + _tmp406 * _tmp412 + _tmp410 * _tmp419 - _tmp417 * _tmp418 -
                  _tmp417 * _tmp420 - _tmp419 * _tmp423 + _tmp419 * _tmp424 - _tmp419 * _tmp429 -
                  _tmp425 * _tmp99 + _tmp426 * _tmp99 + _tmp428 * _tmp99);
  _res(3, 0) = -_tmp430 * (_tmp146 * _tmp383 - _tmp296 * _tmp434 - _tmp296 * _tmp436 +
                           _tmp333 * _tmp433 + _tmp345 * _tmp431 - _tmp348 * _tmp439 -
                           _tmp349 * _tmp435 + _tmp405 * _tmp437 + _tmp425 - _tmp426 - _tmp428);
  _res(0, 1) = 0;
  _res(1, 1) =
      -_tmp149 *
      (-_tmp124 * (-_tmp110 * _tmp523 + _tmp112 * _tmp524 + _tmp113 * _tmp536 + _tmp114 * _tmp486 -
                   _tmp114 * _tmp487 + _tmp127 * _tmp535 - _tmp215 * _tmp474 - _tmp337 * _tmp475) -
       _tmp131 * (-_tmp126 * _tmp523 - _tmp128 * _tmp524 + _tmp371 * _tmp474 + _tmp372 * _tmp486 -
                  _tmp372 * _tmp487 - _tmp373 * _tmp489 + _tmp374 * _tmp522 + _tmp475 * _tmp496) -
       _tmp139 * (_tmp132 * _tmp486 + _tmp336 * _tmp361 * _tmp475 - _tmp352 * _tmp493 -
                  _tmp353 * _tmp489 - _tmp354 * _tmp460 + _tmp356 * _tmp493 + _tmp358 * _tmp465 -
                  _tmp359 * _tmp480) -
       _tmp148 * (_tmp113 * _tmp533 + _tmp127 * _tmp531 - _tmp144 * _tmp523 + _tmp145 * _tmp524 +
                  _tmp146 * _tmp486 - _tmp146 * _tmp487 - _tmp390 * _tmp475 - _tmp407 * _tmp474) +
       _tmp341 * _tmp453 + _tmp362 * _tmp453 - _tmp364 * _tmp483 - _tmp366 * _tmp495 +
       _tmp369 * _tmp453 - _tmp370 * _tmp483 + _tmp377 * _tmp453 - _tmp379 * _tmp483 +
       _tmp380 * _tmp538 - _tmp382 * _tmp483 - _tmp384 * _tmp539 - _tmp389 * _tmp537 +
       _tmp526 * _tmp527);
  _res(2, 1) =
      -_tmp416 * (-_tmp112 * _tmp411 * _tmp538 + _tmp215 * _tmp495 + _tmp407 * _tmp539 +
                  _tmp410 * _tmp541 + _tmp412 * _tmp533 - _tmp414 * _tmp489 + _tmp415 * _tmp536 -
                  _tmp421 * _tmp489 - _tmp423 * _tmp541 + _tmp424 * _tmp541 - _tmp429 * _tmp541 -
                  _tmp526 * _tmp540 + _tmp542 * _tmp99 + _tmp543 * _tmp99 - _tmp544 * _tmp99);
  _res(3, 1) = -_tmp430 * (_tmp146 * _tmp539 + _tmp431 * _tmp494 + _tmp433 * _tmp535 -
                           _tmp434 * _tmp522 - _tmp436 * _tmp522 + _tmp437 * _tmp531 -
                           _tmp438 * _tmp538 - _tmp526 * _tmp545 - _tmp542 - _tmp543 + _tmp544);
  _res(0, 2) = 0;
  _res(1, 2) =
      -_tmp149 *
      (-_tmp124 * (-_tmp110 * _tmp624 + _tmp113 * _tmp626 + _tmp114 * _tmp585 - _tmp114 * _tmp590 +
                   _tmp127 * _tmp623 - _tmp215 * _tmp563 + _tmp335 * _tmp561 - _tmp337 * _tmp574) -
       _tmp131 * (-_tmp126 * _tmp624 + _tmp371 * _tmp563 + _tmp372 * _tmp585 - _tmp372 * _tmp590 -
                  _tmp373 * _tmp592 + _tmp374 * _tmp622 - _tmp375 * _tmp561 + _tmp496 * _tmp574) -
       _tmp139 * (_tmp132 * _tmp336 * _tmp575 + _tmp132 * _tmp585 - _tmp352 * _tmp593 -
                  _tmp353 * _tmp592 - _tmp354 * _tmp561 + _tmp356 * _tmp593 + _tmp358 * _tmp562 -
                  _tmp359 * _tmp588) -
       _tmp148 * (_tmp113 * _tmp630 + _tmp127 * _tmp629 - _tmp144 * _tmp624 + _tmp146 * _tmp585 -
                  _tmp146 * _tmp590 - _tmp390 * _tmp574 - _tmp407 * _tmp563 + _tmp408 * _tmp561) +
       _tmp342 * _tmp565 + _tmp363 * _tmp565 - _tmp364 * _tmp577 - _tmp367 * _tmp631 -
       _tmp369 * _tmp596 + _tmp369 * _tmp634 - _tmp377 * _tmp596 + _tmp377 * _tmp634 +
       _tmp381 * _tmp632 - _tmp382 * _tmp577 - _tmp384 * _tmp595 - _tmp389 * _tmp633 +
       _tmp527 * _tmp632);
  _res(2, 2) = -_tmp416 * (_tmp279 * _tmp414 * _tmp575 + _tmp407 * _tmp595 + _tmp410 * _tmp635 -
                           _tmp411 * _tmp418 * _tmp632 + _tmp412 * _tmp630 - _tmp414 * _tmp592 +
                           _tmp415 * _tmp626 - _tmp421 * _tmp592 + _tmp422 * _tmp631 -
                           _tmp423 * _tmp635 - _tmp429 * _tmp635 - _tmp540 * _tmp632 +
                           _tmp636 * _tmp99 + _tmp637 * _tmp99 - _tmp638 * _tmp99);
  _res(3, 2) = -_tmp430 * (_tmp146 * _tmp595 + _tmp431 * _tmp631 + _tmp433 * _tmp623 -
                           _tmp434 * _tmp622 - _tmp436 * _tmp622 + _tmp437 * _tmp629 -
                           _tmp439 * _tmp632 - _tmp545 * _tmp632 - _tmp636 - _tmp637 + _tmp638);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
