// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_wrt_DeltaRot_Nl12
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     position_vector: Matrix31
 *     Rot_init: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost2WrtDeltarotNl12(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot,
    const Eigen::Matrix<Scalar, 3, 1>& position_vector, const sym::Rot3<Scalar>& Rot_init,
    const Scalar epsilon) {
  // Total ops: 3539

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Rot_init = Rot_init.Data();

  // Intermediate terms (1063)
  const Scalar _tmp0 = _DeltaRot[1] * _Rot_init[2];
  const Scalar _tmp1 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp2 = _DeltaRot[0] * _Rot_init[3];
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = _DeltaRot[2] * _Rot_init[1];
  const Scalar _tmp5 = (Scalar(1) / Scalar(2)) * _tmp4;
  const Scalar _tmp6 = _DeltaRot[3] * _Rot_init[0];
  const Scalar _tmp7 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp8 = _tmp1 - _tmp3 - _tmp5 - _tmp7;
  const Scalar _tmp9 = _DeltaRot[1] * _Rot_init[0];
  const Scalar _tmp10 = _DeltaRot[0] * _Rot_init[1];
  const Scalar _tmp11 = _DeltaRot[2] * _Rot_init[3];
  const Scalar _tmp12 = _DeltaRot[3] * _Rot_init[2];
  const Scalar _tmp13 = -_tmp10 + _tmp11 + _tmp12 + _tmp9;
  const Scalar _tmp14 = Scalar(0.41999999999999998) * _tmp13;
  const Scalar _tmp15 = _tmp14 * _tmp8;
  const Scalar _tmp16 = _DeltaRot[1] * _Rot_init[3];
  const Scalar _tmp17 = (Scalar(1) / Scalar(2)) * _tmp16;
  const Scalar _tmp18 = _DeltaRot[0] * _Rot_init[2];
  const Scalar _tmp19 = (Scalar(1) / Scalar(2)) * _tmp18;
  const Scalar _tmp20 = _DeltaRot[2] * _Rot_init[0];
  const Scalar _tmp21 = (Scalar(1) / Scalar(2)) * _tmp20;
  const Scalar _tmp22 = _DeltaRot[3] * _Rot_init[1];
  const Scalar _tmp23 = (Scalar(1) / Scalar(2)) * _tmp22;
  const Scalar _tmp24 = -_tmp17 - _tmp19 + _tmp21 - _tmp23;
  const Scalar _tmp25 = _DeltaRot[1] * _Rot_init[1];
  const Scalar _tmp26 = _DeltaRot[0] * _Rot_init[0];
  const Scalar _tmp27 = _DeltaRot[2] * _Rot_init[2];
  const Scalar _tmp28 = _DeltaRot[3] * _Rot_init[3];
  const Scalar _tmp29 = -_tmp25 - _tmp26 - _tmp27 + _tmp28;
  const Scalar _tmp30 = Scalar(0.41999999999999998) * _tmp29;
  const Scalar _tmp31 = _tmp24 * _tmp30;
  const Scalar _tmp32 = -Scalar(1) / Scalar(2) * _tmp25 - Scalar(1) / Scalar(2) * _tmp26 -
                        Scalar(1) / Scalar(2) * _tmp27 + (Scalar(1) / Scalar(2)) * _tmp28;
  const Scalar _tmp33 = _tmp16 + _tmp18 - _tmp20 + _tmp22;
  const Scalar _tmp34 = Scalar(0.41999999999999998) * _tmp33;
  const Scalar _tmp35 = _tmp32 * _tmp34;
  const Scalar _tmp36 = -_tmp35;
  const Scalar _tmp37 = (Scalar(1) / Scalar(2)) * _tmp9;
  const Scalar _tmp38 = (Scalar(1) / Scalar(2)) * _tmp10;
  const Scalar _tmp39 = (Scalar(1) / Scalar(2)) * _tmp11;
  const Scalar _tmp40 = (Scalar(1) / Scalar(2)) * _tmp12;
  const Scalar _tmp41 = _tmp37 - _tmp38 + _tmp39 + _tmp40;
  const Scalar _tmp42 = -_tmp0 + _tmp2 + _tmp4 + _tmp6;
  const Scalar _tmp43 = Scalar(0.41999999999999998) * _tmp42;
  const Scalar _tmp44 = _tmp41 * _tmp43;
  const Scalar _tmp45 = -_tmp44;
  const Scalar _tmp46 = _tmp15 + _tmp31 + _tmp36 + _tmp45;
  const Scalar _tmp47 = Scalar(0.83999999999999997) * _tmp13;
  const Scalar _tmp48 = _tmp24 * _tmp47;
  const Scalar _tmp49 = Scalar(0.83999999999999997) * _tmp33;
  const Scalar _tmp50 = _tmp41 * _tmp49;
  const Scalar _tmp51 = _tmp48 + _tmp50;
  const Scalar _tmp52 = Scalar(0.021999999999999999) * _tmp13;
  const Scalar _tmp53 = _tmp32 * _tmp52;
  const Scalar _tmp54 = Scalar(0.021999999999999999) * _tmp42;
  const Scalar _tmp55 = _tmp24 * _tmp54;
  const Scalar _tmp56 = Scalar(0.021999999999999999) * _tmp33;
  const Scalar _tmp57 = _tmp56 * _tmp8;
  const Scalar _tmp58 = Scalar(0.021999999999999999) * _tmp29;
  const Scalar _tmp59 = _tmp41 * _tmp58;
  const Scalar _tmp60 = _tmp53 + _tmp55 + _tmp57 + _tmp59;
  const Scalar _tmp61 = _tmp51 + _tmp60;
  const Scalar _tmp62 = 2 * _tmp33 * _tmp42;
  const Scalar _tmp63 = 2 * _tmp29;
  const Scalar _tmp64 = _tmp13 * _tmp63;
  const Scalar _tmp65 = Scalar(0.20999999999999999) * _tmp62 - Scalar(0.20999999999999999) * _tmp64;
  const Scalar _tmp66 = 2 * _tmp13;
  const Scalar _tmp67 = _tmp42 * _tmp66;
  const Scalar _tmp68 = _tmp33 * _tmp63;
  const Scalar _tmp69 = _tmp67 + _tmp68;
  const Scalar _tmp70 = -Scalar(0.010999999999999999) * _tmp69;
  const Scalar _tmp71 = -2 * std::pow(_tmp13, Scalar(2));
  const Scalar _tmp72 = 1 - 2 * std::pow(_tmp33, Scalar(2));
  const Scalar _tmp73 = Scalar(0.20999999999999999) * _tmp71 + Scalar(0.20999999999999999) * _tmp72;
  const Scalar _tmp74 = _tmp70 + _tmp73;
  const Scalar _tmp75 = _tmp65 + _tmp74;
  const Scalar _tmp76 = _tmp75 + position_vector(0, 0);
  const Scalar _tmp77 = Scalar(125.0) - _tmp76;
  const Scalar _tmp78 = 2 * _tmp77;
  const Scalar _tmp79 = _tmp24 * _tmp56;
  const Scalar _tmp80 = _tmp41 * _tmp52;
  const Scalar _tmp81 = _tmp54 * _tmp8;
  const Scalar _tmp82 = _tmp32 * _tmp58;
  const Scalar _tmp83 = -_tmp82;
  const Scalar _tmp84 = _tmp79 + _tmp80 - _tmp81 + _tmp83;
  const Scalar _tmp85 = Scalar(0.83999999999999997) * _tmp32;
  const Scalar _tmp86 = _tmp42 * _tmp85;
  const Scalar _tmp87 = _tmp48 + _tmp86;
  const Scalar _tmp88 = _tmp84 + _tmp87;
  const Scalar _tmp89 = -_tmp31;
  const Scalar _tmp90 = -_tmp15;
  const Scalar _tmp91 = _tmp36 + _tmp90;
  const Scalar _tmp92 = _tmp45 + _tmp89 + _tmp91;
  const Scalar _tmp93 = Scalar(0.20999999999999999) * _tmp62 + Scalar(0.20999999999999999) * _tmp64;
  const Scalar _tmp94 = _tmp33 * _tmp66;
  const Scalar _tmp95 = _tmp42 * _tmp63;
  const Scalar _tmp96 = _tmp94 - _tmp95;
  const Scalar _tmp97 = -Scalar(0.010999999999999999) * _tmp96;
  const Scalar _tmp98 = -2 * std::pow(_tmp42, Scalar(2));
  const Scalar _tmp99 = Scalar(0.20999999999999999) * _tmp71 +
                        Scalar(0.20999999999999999) * _tmp98 + Scalar(0.20999999999999999);
  const Scalar _tmp100 = _tmp97 + _tmp99;
  const Scalar _tmp101 = _tmp100 + _tmp93;
  const Scalar _tmp102 = _tmp101 + position_vector(1, 0);
  const Scalar _tmp103 = Scalar(110.0) - _tmp102;
  const Scalar _tmp104 = 2 * _tmp103;
  const Scalar _tmp105 = _tmp104 * (_tmp88 + _tmp92) + _tmp78 * (_tmp46 + _tmp61);
  const Scalar _tmp106 = Scalar(1.0) / (fh1);
  const Scalar _tmp107 = std::pow(_tmp103, Scalar(2)) + std::pow(_tmp77, Scalar(2));
  const Scalar _tmp108 = std::sqrt(_tmp107);
  const Scalar _tmp109 =
      Scalar(0.5) *
      std::cosh(Scalar(0.71007031138673404) * _tmp106 *
                (-_tmp108 - Scalar(1.4083112389913199) * fh1 * std::asinh(_tmp106 * fv1))) /
      _tmp108;
  const Scalar _tmp110 = _tmp34 * _tmp8;
  const Scalar _tmp111 = _tmp30 * _tmp41;
  const Scalar _tmp112 = _tmp14 * _tmp32;
  const Scalar _tmp113 = _tmp24 * _tmp43;
  const Scalar _tmp114 = -_tmp112 - _tmp113;
  const Scalar _tmp115 = _tmp110 + _tmp111 + _tmp114;
  const Scalar _tmp116 = _tmp14 * _tmp41;
  const Scalar _tmp117 = _tmp43 * _tmp8;
  const Scalar _tmp118 = -_tmp117;
  const Scalar _tmp119 = _tmp24 * _tmp34;
  const Scalar _tmp120 = _tmp30 * _tmp32;
  const Scalar _tmp121 = -_tmp120;
  const Scalar _tmp122 = -_tmp119 + _tmp121;
  const Scalar _tmp123 = -_tmp116 + _tmp118 + _tmp122;
  const Scalar _tmp124 = Scalar(0.043999999999999997) * _tmp33;
  const Scalar _tmp125 = _tmp124 * _tmp41;
  const Scalar _tmp126 = Scalar(0.043999999999999997) * _tmp42;
  const Scalar _tmp127 = _tmp126 * _tmp32;
  const Scalar _tmp128 = -_tmp125 - _tmp127;
  const Scalar _tmp129 = _tmp123 + _tmp128;
  const Scalar _tmp130 =
      Scalar(0.20999999999999999) * _tmp94 + Scalar(0.20999999999999999) * _tmp95;
  const Scalar _tmp131 =
      -Scalar(0.010999999999999999) * _tmp72 - Scalar(0.010999999999999999) * _tmp98;
  const Scalar _tmp132 =
      Scalar(0.20999999999999999) * _tmp67 - Scalar(0.20999999999999999) * _tmp68;
  const Scalar _tmp133 = _tmp131 + _tmp132;
  const Scalar _tmp134 = _tmp130 + _tmp133;
  const Scalar _tmp135 = -_tmp134 - position_vector(2, 0) + Scalar(48.0);
  const Scalar _tmp136 = 2 * _tmp135;
  const Scalar _tmp137 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp107 + std::pow(_tmp135, Scalar(2))));
  const Scalar _tmp138 = -_tmp55;
  const Scalar _tmp139 = -_tmp53;
  const Scalar _tmp140 = _tmp138 + _tmp139 - _tmp57 - _tmp59;
  const Scalar _tmp141 = _tmp140 + _tmp51;
  const Scalar _tmp142 = _tmp141 + _tmp46;
  const Scalar _tmp143 = -_tmp65;
  const Scalar _tmp144 = _tmp70 - _tmp73;
  const Scalar _tmp145 = _tmp143 + _tmp144;
  const Scalar _tmp146 = _tmp145 + position_vector(0, 0);
  const Scalar _tmp147 = _tmp146 + Scalar(125.0);
  const Scalar _tmp148 = 2 * _tmp147;
  const Scalar _tmp149 = -_tmp79;
  const Scalar _tmp150 = _tmp149 - _tmp80 + _tmp81 + _tmp82;
  const Scalar _tmp151 = _tmp150 + _tmp87;
  const Scalar _tmp152 = _tmp151 + _tmp92;
  const Scalar _tmp153 = -_tmp93;
  const Scalar _tmp154 = _tmp97 - _tmp99;
  const Scalar _tmp155 = _tmp153 + _tmp154;
  const Scalar _tmp156 = _tmp155 + position_vector(1, 0);
  const Scalar _tmp157 = _tmp156 + Scalar(110.0);
  const Scalar _tmp158 = 2 * _tmp157;
  const Scalar _tmp159 = _tmp142 * _tmp148 + _tmp152 * _tmp158;
  const Scalar _tmp160 = Scalar(1.0) / (_tmp147);
  const Scalar _tmp161 = std::pow(_tmp147, Scalar(2));
  const Scalar _tmp162 = std::pow(_tmp157, Scalar(2)) + _tmp161;
  const Scalar _tmp163 = std::sqrt(_tmp162);
  const Scalar _tmp164 = Scalar(1.0) / (_tmp163);
  const Scalar _tmp165 = (Scalar(1) / Scalar(2)) * _tmp160 * _tmp164;
  const Scalar _tmp166 = _tmp154 + _tmp93;
  const Scalar _tmp167 = _tmp166 + position_vector(1, 0);
  const Scalar _tmp168 = _tmp167 + Scalar(110.0);
  const Scalar _tmp169 = _tmp143 + _tmp74;
  const Scalar _tmp170 = _tmp169 + position_vector(0, 0);
  const Scalar _tmp171 = _tmp170 + Scalar(-125.0);
  const Scalar _tmp172 = std::pow(_tmp168, Scalar(2)) + std::pow(_tmp171, Scalar(2));
  const Scalar _tmp173 = std::pow(_tmp172, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp174 = _tmp171 * _tmp173;
  const Scalar _tmp175 = _tmp168 * _tmp173;
  const Scalar _tmp176 = _tmp157 * _tmp160;
  const Scalar _tmp177 = _tmp174 * _tmp176 - _tmp175;
  const Scalar _tmp178 = Scalar(1.0) / (_tmp177);
  const Scalar _tmp179 = _tmp145 * _tmp164;
  const Scalar _tmp180 = _tmp147 * _tmp164;
  const Scalar _tmp181 = -_tmp155 * _tmp180 + _tmp157 * _tmp179;
  const Scalar _tmp182 = _tmp160 * _tmp163;
  const Scalar _tmp183 = _tmp181 * _tmp182;
  const Scalar _tmp184 = _tmp166 * _tmp174 - _tmp169 * _tmp175 + _tmp174 * _tmp183;
  const Scalar _tmp185 = Scalar(1.0) * _tmp178;
  const Scalar _tmp186 = -_tmp130;
  const Scalar _tmp187 = _tmp133 + _tmp186;
  const Scalar _tmp188 = _tmp131 - _tmp132;
  const Scalar _tmp189 = _tmp186 + _tmp188;
  const Scalar _tmp190 = _tmp176 * _tmp189;
  const Scalar _tmp191 = -_tmp174 * _tmp190 + _tmp175 * _tmp187;
  const Scalar _tmp192 = _tmp178 * _tmp191;
  const Scalar _tmp193 = Scalar(1.0) * _tmp145;
  const Scalar _tmp194 = -_tmp169 + _tmp193;
  const Scalar _tmp195 = Scalar(1.0) * _tmp155;
  const Scalar _tmp196 = -_tmp195;
  const Scalar _tmp197 = _tmp166 + _tmp196;
  const Scalar _tmp198 = Scalar(1.0) / (_tmp197);
  const Scalar _tmp199 = Scalar(1.0) * _tmp198;
  const Scalar _tmp200 = _tmp194 * _tmp199;
  const Scalar _tmp201 = _tmp174 * _tmp189;
  const Scalar _tmp202 = -_tmp174 * _tmp187 + _tmp201;
  const Scalar _tmp203 = -_tmp185 * _tmp202 + _tmp192 * _tmp200;
  const Scalar _tmp204 = _tmp130 + _tmp188;
  const Scalar _tmp205 = _tmp144 + _tmp65;
  const Scalar _tmp206 = _tmp205 + position_vector(0, 0);
  const Scalar _tmp207 = _tmp206 + Scalar(125.0);
  const Scalar _tmp208 = _tmp100 + _tmp153;
  const Scalar _tmp209 = _tmp208 + position_vector(1, 0);
  const Scalar _tmp210 = _tmp209 + Scalar(-110.0);
  const Scalar _tmp211 = std::pow(_tmp207, Scalar(2)) + std::pow(_tmp210, Scalar(2));
  const Scalar _tmp212 = std::pow(_tmp211, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp213 = _tmp207 * _tmp212;
  const Scalar _tmp214 = _tmp210 * _tmp212;
  const Scalar _tmp215 = _tmp176 * _tmp213 - _tmp214;
  const Scalar _tmp216 = _tmp178 * _tmp215;
  const Scalar _tmp217 = -_tmp190 * _tmp213 - _tmp191 * _tmp216 + _tmp204 * _tmp214;
  const Scalar _tmp218 = _tmp194 * _tmp198;
  const Scalar _tmp219 = _tmp189 * _tmp213;
  const Scalar _tmp220 = -_tmp202 * _tmp216 - _tmp204 * _tmp213 - _tmp217 * _tmp218 + _tmp219;
  const Scalar _tmp221 = Scalar(1.0) / (_tmp220);
  const Scalar _tmp222 =
      _tmp183 * _tmp213 - _tmp184 * _tmp216 - _tmp205 * _tmp214 + _tmp208 * _tmp213;
  const Scalar _tmp223 = _tmp221 * _tmp222;
  const Scalar _tmp224 = -_tmp184 * _tmp185 - _tmp203 * _tmp223;
  const Scalar _tmp225 = Scalar(1.0) / (_tmp222);
  const Scalar _tmp226 = _tmp220 * _tmp225;
  const Scalar _tmp227 = _tmp224 * _tmp226;
  const Scalar _tmp228 = _tmp203 + _tmp227;
  const Scalar _tmp229 = _tmp215 * _tmp221;
  const Scalar _tmp230 = -_tmp228 * _tmp229 + Scalar(1.0);
  const Scalar _tmp231 = _tmp178 * _tmp230;
  const Scalar _tmp232 = _tmp221 * _tmp228;
  const Scalar _tmp233 = _tmp174 * _tmp231 + _tmp213 * _tmp232;
  const Scalar _tmp234 = _tmp102 + Scalar(-110.0);
  const Scalar _tmp235 = _tmp76 + Scalar(-125.0);
  const Scalar _tmp236 = std::pow(_tmp234, Scalar(2)) + std::pow(_tmp235, Scalar(2));
  const Scalar _tmp237 = std::pow(_tmp236, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp238 = _tmp234 * _tmp237;
  const Scalar _tmp239 = _tmp238 * fh1;
  const Scalar _tmp240 = _tmp233 * _tmp239;
  const Scalar _tmp241 = _tmp165 * _tmp240;
  const Scalar _tmp242 = Scalar(1.0) / (_tmp161);
  const Scalar _tmp243 = _tmp163 * _tmp242;
  const Scalar _tmp244 = _tmp142 * _tmp243;
  const Scalar _tmp245 = Scalar(1.0) * _tmp225;
  const Scalar _tmp246 = _tmp216 * _tmp245;
  const Scalar _tmp247 = -_tmp174 * _tmp246 + _tmp213 * _tmp245;
  const Scalar _tmp248 = _tmp101 * _tmp237;
  const Scalar _tmp249 = -_tmp235 * _tmp248 + _tmp238 * _tmp75;
  const Scalar _tmp250 = _tmp249 * fh1;
  const Scalar _tmp251 = _tmp247 * _tmp250;
  const Scalar _tmp252 = -_tmp48;
  const Scalar _tmp253 = _tmp252 - _tmp50;
  const Scalar _tmp254 = _tmp140 + _tmp253;
  const Scalar _tmp255 = _tmp254 + _tmp46;
  const Scalar _tmp256 = _tmp173 * _tmp255;
  const Scalar _tmp257 = 2 * _tmp171;
  const Scalar _tmp258 = _tmp15 + _tmp35;
  const Scalar _tmp259 = _tmp258 + _tmp31 + _tmp44;
  const Scalar _tmp260 = _tmp151 + _tmp259;
  const Scalar _tmp261 = 2 * _tmp168;
  const Scalar _tmp262 = _tmp255 * _tmp257 + _tmp260 * _tmp261;
  const Scalar _tmp263 = std::pow(_tmp172, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp264 = (Scalar(1) / Scalar(2)) * _tmp263;
  const Scalar _tmp265 = _tmp168 * _tmp264;
  const Scalar _tmp266 = _tmp262 * _tmp265;
  const Scalar _tmp267 = _tmp157 * _tmp242;
  const Scalar _tmp268 = _tmp142 * _tmp267;
  const Scalar _tmp269 = _tmp171 * _tmp264;
  const Scalar _tmp270 = _tmp262 * _tmp269;
  const Scalar _tmp271 = _tmp173 * _tmp260;
  const Scalar _tmp272 = _tmp152 * _tmp160;
  const Scalar _tmp273 = -_tmp174 * _tmp268 + _tmp174 * _tmp272 + _tmp176 * _tmp256 -
                         _tmp176 * _tmp270 + _tmp266 - _tmp271;
  const Scalar _tmp274 = _tmp178 * _tmp184;
  const Scalar _tmp275 = _tmp178 * _tmp202;
  const Scalar _tmp276 = _tmp176 * _tmp192 + _tmp190;
  const Scalar _tmp277 = _tmp198 * _tmp276;
  const Scalar _tmp278 = _tmp176 * _tmp275 - _tmp189 - _tmp194 * _tmp277;
  const Scalar _tmp279 = _tmp221 * _tmp278;
  const Scalar _tmp280 = _tmp176 * _tmp274 - _tmp183 - _tmp222 * _tmp279;
  const Scalar _tmp281 = _tmp226 * _tmp280;
  const Scalar _tmp282 = _tmp278 + _tmp281;
  const Scalar _tmp283 = -_tmp176 - _tmp229 * _tmp282;
  const Scalar _tmp284 = std::pow(_tmp177, Scalar(-2));
  const Scalar _tmp285 = _tmp174 * _tmp284;
  const Scalar _tmp286 = _tmp283 * _tmp285;
  const Scalar _tmp287 = Scalar(1.6799999999999999) * _tmp33;
  const Scalar _tmp288 = Scalar(1.6799999999999999) * _tmp13;
  const Scalar _tmp289 = _tmp24 * _tmp288;
  const Scalar _tmp290 = _tmp287 * _tmp41 + _tmp289;
  const Scalar _tmp291 = _tmp198 * _tmp290;
  const Scalar _tmp292 = _tmp35 + _tmp44 + _tmp89 + _tmp90;
  const Scalar _tmp293 = _tmp141 + _tmp292;
  const Scalar _tmp294 = _tmp212 * _tmp293;
  const Scalar _tmp295 = 2 * _tmp207;
  const Scalar _tmp296 = -_tmp86;
  const Scalar _tmp297 = _tmp252 + _tmp296;
  const Scalar _tmp298 = _tmp297 + _tmp92;
  const Scalar _tmp299 = _tmp150 + _tmp298;
  const Scalar _tmp300 = 2 * _tmp210;
  const Scalar _tmp301 = _tmp293 * _tmp295 + _tmp299 * _tmp300;
  const Scalar _tmp302 = std::pow(_tmp211, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp303 = (Scalar(1) / Scalar(2)) * _tmp302;
  const Scalar _tmp304 = _tmp207 * _tmp303;
  const Scalar _tmp305 = _tmp301 * _tmp304;
  const Scalar _tmp306 = _tmp173 * _tmp187;
  const Scalar _tmp307 = _tmp125 + _tmp127;
  const Scalar _tmp308 = _tmp123 + _tmp307;
  const Scalar _tmp309 = _tmp112 + _tmp113;
  const Scalar _tmp310 = -_tmp110 - _tmp111 + _tmp309;
  const Scalar _tmp311 = _tmp308 + _tmp310;
  const Scalar _tmp312 = _tmp115 + _tmp308;
  const Scalar _tmp313 = _tmp174 * _tmp312;
  const Scalar _tmp314 = _tmp187 * _tmp269;
  const Scalar _tmp315 = _tmp173 * _tmp189;
  const Scalar _tmp316 = _tmp189 * _tmp269;
  const Scalar _tmp317 = -_tmp174 * _tmp311 - _tmp255 * _tmp306 + _tmp255 * _tmp315 +
                         _tmp262 * _tmp314 - _tmp262 * _tmp316 + _tmp313;
  const Scalar _tmp318 = std::pow(_tmp197, Scalar(-2));
  const Scalar _tmp319 = _tmp33 * _tmp85;
  const Scalar _tmp320 = Scalar(0.83999999999999997) * _tmp42;
  const Scalar _tmp321 = _tmp320 * _tmp41;
  const Scalar _tmp322 = Scalar(0.83999999999999997) * _tmp29;
  const Scalar _tmp323 = _tmp24 * _tmp322 + _tmp47 * _tmp8;
  const Scalar _tmp324 = _tmp319 + _tmp321 + _tmp323;
  const Scalar _tmp325 = _tmp318 * _tmp324;
  const Scalar _tmp326 = _tmp194 * _tmp217;
  const Scalar _tmp327 = _tmp213 * _tmp312;
  const Scalar _tmp328 = _tmp119 + _tmp120;
  const Scalar _tmp329 = _tmp116 + _tmp117 + _tmp328;
  const Scalar _tmp330 = _tmp115 + _tmp329;
  const Scalar _tmp331 = _tmp307 + _tmp330;
  const Scalar _tmp332 = _tmp210 * _tmp303;
  const Scalar _tmp333 = _tmp301 * _tmp332;
  const Scalar _tmp334 = _tmp189 * _tmp272;
  const Scalar _tmp335 = -_tmp174 * _tmp334 + _tmp175 * _tmp311 - _tmp176 * _tmp313 -
                         _tmp187 * _tmp266 + _tmp187 * _tmp271 - _tmp190 * _tmp256 +
                         _tmp190 * _tmp270 + _tmp201 * _tmp268;
  const Scalar _tmp336 = _tmp212 * _tmp299;
  const Scalar _tmp337 = _tmp176 * _tmp294 - _tmp176 * _tmp305 - _tmp213 * _tmp268 +
                         _tmp213 * _tmp272 + _tmp333 - _tmp336;
  const Scalar _tmp338 = _tmp215 * _tmp284;
  const Scalar _tmp339 = _tmp191 * _tmp338;
  const Scalar _tmp340 = -_tmp176 * _tmp327 - _tmp190 * _tmp294 + _tmp190 * _tmp305 -
                         _tmp192 * _tmp337 - _tmp204 * _tmp333 + _tmp204 * _tmp336 -
                         _tmp213 * _tmp334 + _tmp214 * _tmp331 - _tmp216 * _tmp335 +
                         _tmp219 * _tmp268 + _tmp273 * _tmp339;
  const Scalar _tmp341 = _tmp202 * _tmp273;
  const Scalar _tmp342 = _tmp189 * _tmp294 - _tmp189 * _tmp305 - _tmp204 * _tmp294 +
                         _tmp204 * _tmp305 - _tmp213 * _tmp331 - _tmp216 * _tmp317 -
                         _tmp217 * _tmp291 - _tmp218 * _tmp340 - _tmp275 * _tmp337 +
                         _tmp325 * _tmp326 + _tmp327 + _tmp338 * _tmp341;
  const Scalar _tmp343 = std::pow(_tmp220, Scalar(-2));
  const Scalar _tmp344 = _tmp342 * _tmp343;
  const Scalar _tmp345 = _tmp213 * _tmp344;
  const Scalar _tmp346 = _tmp178 * _tmp283;
  const Scalar _tmp347 = _tmp221 * _tmp282;
  const Scalar _tmp348 = _tmp215 * _tmp343;
  const Scalar _tmp349 = _tmp342 * _tmp348;
  const Scalar _tmp350 = _tmp157 * _tmp164;
  const Scalar _tmp351 = _tmp155 * _tmp164;
  const Scalar _tmp352 = _tmp145 * _tmp157;
  const Scalar _tmp353 = (Scalar(1) / Scalar(2)) / (_tmp162 * std::sqrt(_tmp162));
  const Scalar _tmp354 = _tmp159 * _tmp353;
  const Scalar _tmp355 = _tmp147 * _tmp155;
  const Scalar _tmp356 = _tmp182 * (_tmp142 * _tmp350 - _tmp142 * _tmp351 + _tmp152 * _tmp179 -
                                    _tmp152 * _tmp180 - _tmp352 * _tmp354 + _tmp354 * _tmp355);
  const Scalar _tmp357 = _tmp165 * _tmp181;
  const Scalar _tmp358 = _tmp159 * _tmp357;
  const Scalar _tmp359 = _tmp181 * _tmp243;
  const Scalar _tmp360 = _tmp142 * _tmp359;
  const Scalar _tmp361 = _tmp166 * _tmp173;
  const Scalar _tmp362 = _tmp166 * _tmp269;
  const Scalar _tmp363 = _tmp169 * _tmp266 - _tmp169 * _tmp271 + _tmp171 * _tmp271 +
                         _tmp174 * _tmp356 + _tmp174 * _tmp358 - _tmp174 * _tmp360 -
                         _tmp175 * _tmp255 + _tmp183 * _tmp256 - _tmp183 * _tmp270 +
                         _tmp255 * _tmp361 - _tmp262 * _tmp362;
  const Scalar _tmp364 = _tmp184 * _tmp338;
  const Scalar _tmp365 = _tmp183 * _tmp294 - _tmp183 * _tmp305 + _tmp205 * _tmp333 -
                         _tmp205 * _tmp336 + _tmp207 * _tmp336 + _tmp208 * _tmp294 -
                         _tmp208 * _tmp305 + _tmp213 * _tmp356 + _tmp213 * _tmp358 -
                         _tmp213 * _tmp360 - _tmp214 * _tmp293 - _tmp216 * _tmp363 +
                         _tmp273 * _tmp364 - _tmp274 * _tmp337;
  const Scalar _tmp366 = std::pow(_tmp222, Scalar(-2));
  const Scalar _tmp367 = _tmp220 * _tmp366;
  const Scalar _tmp368 = _tmp280 * _tmp367;
  const Scalar _tmp369 = _tmp365 * _tmp368;
  const Scalar _tmp370 = _tmp176 * _tmp284;
  const Scalar _tmp371 = _tmp273 * _tmp370;
  const Scalar _tmp372 = _tmp176 * _tmp178;
  const Scalar _tmp373 = _tmp222 * _tmp278;
  const Scalar _tmp374 = _tmp194 * _tmp276;
  const Scalar _tmp375 = _tmp176 * _tmp312 - _tmp189 * _tmp268 - _tmp191 * _tmp371 -
                         _tmp192 * _tmp268 + _tmp192 * _tmp272 + _tmp334 + _tmp335 * _tmp372;
  const Scalar _tmp376 = _tmp310 + _tmp329;
  const Scalar _tmp377 = _tmp128 + _tmp376;
  const Scalar _tmp378 = -_tmp218 * _tmp375 - _tmp268 * _tmp275 + _tmp272 * _tmp275 -
                         _tmp277 * _tmp290 + _tmp317 * _tmp372 + _tmp325 * _tmp374 -
                         _tmp341 * _tmp370 + _tmp377;
  const Scalar _tmp379 = _tmp226 * (-_tmp184 * _tmp371 - _tmp223 * _tmp378 - _tmp268 * _tmp274 +
                                    _tmp272 * _tmp274 - _tmp279 * _tmp365 + _tmp344 * _tmp373 -
                                    _tmp356 - _tmp358 + _tmp360 + _tmp363 * _tmp372);
  const Scalar _tmp380 = _tmp225 * _tmp342;
  const Scalar _tmp381 = _tmp280 * _tmp380;
  const Scalar _tmp382 = -_tmp369 + _tmp378 + _tmp379 + _tmp381;
  const Scalar _tmp383 =
      -_tmp229 * _tmp382 + _tmp268 - _tmp272 + _tmp282 * _tmp349 - _tmp337 * _tmp347;
  const Scalar _tmp384 = _tmp174 * _tmp178;
  const Scalar _tmp385 = _tmp213 * _tmp221;
  const Scalar _tmp386 = _tmp269 * _tmp346;
  const Scalar _tmp387 = _tmp235 * _tmp237;
  const Scalar _tmp388 = _tmp387 * fh1;
  const Scalar _tmp389 = _tmp182 * _tmp388;
  const Scalar _tmp390 = _tmp230 * _tmp285;
  const Scalar _tmp391 = _tmp224 * _tmp367;
  const Scalar _tmp392 = _tmp365 * _tmp391;
  const Scalar _tmp393 = _tmp192 * _tmp199;
  const Scalar _tmp394 = _tmp185 * _tmp191;
  const Scalar _tmp395 = _tmp194 * _tmp394;
  const Scalar _tmp396 = _tmp178 * _tmp200;
  const Scalar _tmp397 = Scalar(1.0) * _tmp284;
  const Scalar _tmp398 = _tmp191 * _tmp200;
  const Scalar _tmp399 = _tmp273 * _tmp284;
  const Scalar _tmp400 = -_tmp185 * _tmp317 + _tmp290 * _tmp393 - _tmp325 * _tmp395 +
                         _tmp335 * _tmp396 + _tmp341 * _tmp397 - _tmp398 * _tmp399;
  const Scalar _tmp401 = _tmp184 * _tmp397;
  const Scalar _tmp402 = _tmp203 * _tmp222;
  const Scalar _tmp403 = _tmp203 * _tmp221;
  const Scalar _tmp404 = _tmp226 * (-_tmp185 * _tmp363 - _tmp223 * _tmp400 + _tmp273 * _tmp401 +
                                    _tmp344 * _tmp402 - _tmp365 * _tmp403);
  const Scalar _tmp405 = _tmp224 * _tmp380;
  const Scalar _tmp406 = -_tmp392 + _tmp400 + _tmp404 + _tmp405;
  const Scalar _tmp407 = _tmp228 * _tmp349 - _tmp229 * _tmp406 - _tmp232 * _tmp337;
  const Scalar _tmp408 = _tmp182 * _tmp239;
  const Scalar _tmp409 = _tmp165 * _tmp251;
  const Scalar _tmp410 = _tmp174 * _tmp245;
  const Scalar _tmp411 = _tmp273 * _tmp338;
  const Scalar _tmp412 = Scalar(1.0) * _tmp366;
  const Scalar _tmp413 = _tmp213 * _tmp412;
  const Scalar _tmp414 = _tmp174 * _tmp216;
  const Scalar _tmp415 = _tmp412 * _tmp414;
  const Scalar _tmp416 = _tmp185 * _tmp225;
  const Scalar _tmp417 = _tmp174 * _tmp416;
  const Scalar _tmp418 = Scalar(0.5) * _tmp225;
  const Scalar _tmp419 = _tmp171 * _tmp216 * _tmp263 * _tmp418;
  const Scalar _tmp420 = _tmp207 * _tmp302 * _tmp418;
  const Scalar _tmp421 = _tmp182 * _tmp250;
  const Scalar _tmp422 = _tmp259 + _tmp297;
  const Scalar _tmp423 = _tmp150 + _tmp422;
  const Scalar _tmp424 = 2 * _tmp234;
  const Scalar _tmp425 = _tmp254 + _tmp292;
  const Scalar _tmp426 = 2 * _tmp235;
  const Scalar _tmp427 = _tmp423 * _tmp424 + _tmp425 * _tmp426;
  const Scalar _tmp428 = std::pow(_tmp236, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp429 = (Scalar(1) / Scalar(2)) * _tmp428;
  const Scalar _tmp430 = _tmp427 * _tmp429;
  const Scalar _tmp431 = _tmp213 * _tmp347 + _tmp283 * _tmp384 + Scalar(1.0);
  const Scalar _tmp432 = _tmp182 * _tmp431;
  const Scalar _tmp433 = _tmp235 * fh1;
  const Scalar _tmp434 = _tmp432 * _tmp433;
  const Scalar _tmp435 = _tmp237 * _tmp423;
  const Scalar _tmp436 = _tmp101 * _tmp235;
  const Scalar _tmp437 = _tmp234 * _tmp75;
  const Scalar _tmp438 = fh1 * (-_tmp235 * _tmp435 + _tmp238 * _tmp425 - _tmp248 * _tmp425 +
                                _tmp430 * _tmp436 - _tmp430 * _tmp437 + _tmp435 * _tmp75);
  const Scalar _tmp439 = _tmp182 * _tmp247;
  const Scalar _tmp440 = _tmp193 + _tmp195 * _tmp218;
  const Scalar _tmp441 = 0;
  const Scalar _tmp442 = _tmp221 * _tmp441;
  const Scalar _tmp443 = _tmp229 * _tmp441;
  const Scalar _tmp444 = _tmp285 * _tmp443;
  const Scalar _tmp445 = _tmp384 * _tmp442;
  const Scalar _tmp446 = _tmp414 * _tmp441;
  const Scalar _tmp447 = _tmp178 * _tmp229;
  const Scalar _tmp448 = _tmp441 * _tmp447;
  const Scalar _tmp449 = Scalar(333.54000000000002) - fv1;
  const Scalar _tmp450 = _tmp182 * _tmp449;
  const Scalar _tmp451 = _tmp213 * _tmp442 - _tmp384 * _tmp443;
  const Scalar _tmp452 = _tmp449 * _tmp451;
  const Scalar _tmp453 = _tmp165 * _tmp452;
  const Scalar _tmp454 = _tmp182 * _tmp233;
  const Scalar _tmp455 = _tmp234 * fh1;
  const Scalar _tmp456 = _tmp454 * _tmp455;
  const Scalar _tmp457 = _tmp388 * _tmp431;
  const Scalar _tmp458 = _tmp237 * fh1;
  const Scalar _tmp459 = _tmp425 * _tmp458;
  const Scalar _tmp460 = _tmp435 * fh1;
  const Scalar _tmp461 = _tmp165 * _tmp457;
  const Scalar _tmp462 =
      -_tmp159 * _tmp241 - _tmp159 * _tmp409 - _tmp159 * _tmp453 - _tmp159 * _tmp461 +
      _tmp240 * _tmp244 + _tmp244 * _tmp251 + _tmp244 * _tmp452 + _tmp244 * _tmp457 -
      _tmp389 * (_tmp256 * _tmp346 - _tmp262 * _tmp386 - _tmp273 * _tmp286 - _tmp282 * _tmp345 +
                 _tmp294 * _tmp347 - _tmp305 * _tmp347 + _tmp382 * _tmp385 + _tmp383 * _tmp384) -
      _tmp408 * (-_tmp228 * _tmp345 + _tmp231 * _tmp256 - _tmp231 * _tmp270 + _tmp232 * _tmp294 -
                 _tmp232 * _tmp305 - _tmp273 * _tmp390 + _tmp384 * _tmp407 + _tmp385 * _tmp406) -
      _tmp421 * (_tmp245 * _tmp294 - _tmp246 * _tmp256 + _tmp262 * _tmp419 - _tmp301 * _tmp420 -
                 _tmp337 * _tmp417 - _tmp365 * _tmp413 + _tmp365 * _tmp415 + _tmp410 * _tmp411) +
      _tmp430 * _tmp434 + _tmp430 * _tmp456 - _tmp432 * _tmp459 - _tmp438 * _tmp439 -
      _tmp450 * (-_tmp256 * _tmp448 + _tmp270 * _tmp448 + _tmp273 * _tmp444 + _tmp294 * _tmp442 -
                 _tmp305 * _tmp442 - _tmp337 * _tmp445 + _tmp344 * _tmp446 - _tmp345 * _tmp441) -
      _tmp454 * _tmp460;
  const Scalar _tmp463 = -_tmp156 + Scalar(-110.0);
  const Scalar _tmp464 = -_tmp146 + Scalar(-125.0);
  const Scalar _tmp465 = std::pow(_tmp463, Scalar(2)) + std::pow(_tmp464, Scalar(2));
  const Scalar _tmp466 = std::sqrt(_tmp465);
  const Scalar _tmp467 =
      -_tmp239 * _tmp454 - _tmp247 * _tmp421 - _tmp388 * _tmp432 - _tmp450 * _tmp451;
  const Scalar _tmp468 = Scalar(1.0) / (_tmp467);
  const Scalar _tmp469 = _tmp196 + _tmp208;
  const Scalar _tmp470 = _tmp218 * _tmp469;
  const Scalar _tmp471 = _tmp193 - _tmp205 - _tmp470;
  const Scalar _tmp472 = Scalar(1.0) / (_tmp471);
  const Scalar _tmp473 = _tmp469 * _tmp472;
  const Scalar _tmp474 = -_tmp217 * _tmp232 + _tmp227 * _tmp473 - _tmp394;
  const Scalar _tmp475 = Scalar(1.0) * _tmp472;
  const Scalar _tmp476 = -_tmp199 * _tmp474 + _tmp227 * _tmp475;
  const Scalar _tmp477 = Scalar(1.0) * _tmp239;
  const Scalar _tmp478 = _tmp226 * _tmp475;
  const Scalar _tmp479 = -_tmp217 * _tmp245 + _tmp469 * _tmp478;
  const Scalar _tmp480 = -Scalar(1.0) * _tmp199 * _tmp479 + Scalar(1.0) * _tmp478;
  const Scalar _tmp481 = _tmp217 * _tmp221;
  const Scalar _tmp482 = _tmp196 - _tmp440 * _tmp473 - _tmp441 * _tmp481;
  const Scalar _tmp483 = Scalar(1.0) * _tmp449;
  const Scalar _tmp484 = _tmp134 * fh1;
  const Scalar _tmp485 = -_tmp101 * fv1 - _tmp238 * _tmp484 - Scalar(40.024799999999999) * _tmp96;
  const Scalar _tmp486 = _tmp218 * _tmp475;
  const Scalar _tmp487 = _tmp470 * _tmp475 + Scalar(1.0);
  const Scalar _tmp488 = -Scalar(1.0) * _tmp199 * _tmp487 + Scalar(1.0) * _tmp486;
  const Scalar _tmp489 = _tmp276 + _tmp281 * _tmp473 - _tmp282 * _tmp481;
  const Scalar _tmp490 = -_tmp199 * _tmp489 + _tmp281 * _tmp475;
  const Scalar _tmp491 = Scalar(1.0) * _tmp388;
  const Scalar _tmp492 = _tmp387 * _tmp484 + Scalar(40.024799999999999) * _tmp69 + _tmp75 * fv1;
  const Scalar _tmp493 = _tmp198 * _tmp475;
  const Scalar _tmp494 = Scalar(1.0) * _tmp469 * _tmp493 - Scalar(1.0) * _tmp475;
  const Scalar _tmp495 = _tmp250 * _tmp480 + _tmp476 * _tmp477 +
                         _tmp483 * (-_tmp199 * _tmp482 - _tmp440 * _tmp475 + Scalar(1.0)) +
                         _tmp485 * _tmp488 + _tmp490 * _tmp491 + _tmp492 * _tmp494;
  const Scalar _tmp496 = std::asinh(_tmp468 * _tmp495);
  const Scalar _tmp497 = Scalar(1.4083112389913199) * _tmp467;
  const Scalar _tmp498 = -_tmp466 - _tmp496 * _tmp497;
  const Scalar _tmp499 = Scalar(0.71007031138673404) * _tmp468;
  const Scalar _tmp500 = _tmp498 * _tmp499;
  const Scalar _tmp501 = Scalar(1.0) * _tmp496;
  const Scalar _tmp502 = -Scalar(1.4083112389913199) * std::sinh(_tmp500) -
                         Scalar(1.4083112389913199) * std::sinh(_tmp501);
  const Scalar _tmp503 = std::cosh(_tmp500);
  const Scalar _tmp504 = std::pow(_tmp467, Scalar(-2));
  const Scalar _tmp505 = Scalar(0.71007031138673404) * _tmp498 * _tmp504;
  const Scalar _tmp506 = Scalar(1.4083112389913199) * _tmp496;
  const Scalar _tmp507 =
      std::pow(Scalar(std::pow(_tmp495, Scalar(2)) * _tmp504 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp508 = Scalar(1.0) * _tmp490;
  const Scalar _tmp509 = Scalar(0.5) * _tmp428;
  const Scalar _tmp510 = _tmp427 * _tmp509;
  const Scalar _tmp511 = _tmp433 * _tmp490;
  const Scalar _tmp512 = _tmp194 * _tmp469;
  const Scalar _tmp513 = _tmp325 * _tmp512;
  const Scalar _tmp514 = _tmp291 * _tmp469;
  const Scalar _tmp515 = Scalar(1.6799999999999999) * _tmp42;
  const Scalar _tmp516 = -_tmp289 - _tmp32 * _tmp515;
  const Scalar _tmp517 = _tmp218 * _tmp516;
  const Scalar _tmp518 = std::pow(_tmp471, Scalar(-2));
  const Scalar _tmp519 = -_tmp319;
  const Scalar _tmp520 = -_tmp321 + _tmp323 + _tmp513 - _tmp514 - _tmp517 + _tmp519;
  const Scalar _tmp521 = _tmp518 * _tmp520;
  const Scalar _tmp522 = _tmp200 * _tmp521;
  const Scalar _tmp523 =
      -_tmp469 * _tmp522 - _tmp475 * _tmp513 + _tmp475 * _tmp514 + _tmp475 * _tmp517;
  const Scalar _tmp524 = _tmp194 * _tmp475;
  const Scalar _tmp525 = _tmp325 * _tmp524;
  const Scalar _tmp526 = Scalar(1.0) * _tmp318;
  const Scalar _tmp527 = _tmp487 * _tmp526;
  const Scalar _tmp528 = Scalar(1.0) * _tmp485;
  const Scalar _tmp529 = _tmp324 * _tmp482;
  const Scalar _tmp530 = _tmp194 * _tmp195;
  const Scalar _tmp531 = _tmp142 + _tmp152 * _tmp200 + _tmp195 * _tmp291 - _tmp325 * _tmp530;
  const Scalar _tmp532 = _tmp440 * _tmp518;
  const Scalar _tmp533 = _tmp469 * _tmp532;
  const Scalar _tmp534 = _tmp217 * _tmp343;
  const Scalar _tmp535 = _tmp441 * _tmp534;
  const Scalar _tmp536 = _tmp440 * _tmp472;
  const Scalar _tmp537 = _tmp422 + _tmp84;
  const Scalar _tmp538 = -_tmp340 * _tmp442 + _tmp342 * _tmp535 - _tmp473 * _tmp531 -
                         _tmp516 * _tmp536 + _tmp520 * _tmp533 + _tmp537;
  const Scalar _tmp539 = Scalar(1.0) * _tmp518;
  const Scalar _tmp540 = _tmp520 * _tmp539;
  const Scalar _tmp541 = Scalar(1.0) * _tmp476;
  const Scalar _tmp542 = _tmp455 * _tmp476;
  const Scalar _tmp543 = _tmp228 * _tmp534;
  const Scalar _tmp544 = _tmp227 * _tmp469;
  const Scalar _tmp545 = _tmp191 * _tmp397;
  const Scalar _tmp546 = _tmp227 * _tmp472;
  const Scalar _tmp547 = -_tmp185 * _tmp335 - _tmp232 * _tmp340 + _tmp273 * _tmp545 +
                         _tmp342 * _tmp543 - _tmp392 * _tmp473 + _tmp404 * _tmp473 +
                         _tmp405 * _tmp473 - _tmp406 * _tmp481 + _tmp516 * _tmp546 -
                         _tmp521 * _tmp544;
  const Scalar _tmp548 = _tmp474 * _tmp526;
  const Scalar _tmp549 = _tmp282 * _tmp534;
  const Scalar _tmp550 = _tmp281 * _tmp469;
  const Scalar _tmp551 = _tmp281 * _tmp472;
  const Scalar _tmp552 = -_tmp340 * _tmp347 + _tmp342 * _tmp549 - _tmp369 * _tmp473 + _tmp375 +
                         _tmp379 * _tmp473 + _tmp381 * _tmp473 - _tmp382 * _tmp481 +
                         _tmp516 * _tmp551 - _tmp521 * _tmp550;
  const Scalar _tmp553 = _tmp489 * _tmp526;
  const Scalar _tmp554 = Scalar(80.049599999999998) * _tmp33;
  const Scalar _tmp555 = Scalar(80.049599999999998) * _tmp13;
  const Scalar _tmp556 = _tmp32 * _tmp555;
  const Scalar _tmp557 = Scalar(80.049599999999998) * _tmp42;
  const Scalar _tmp558 = _tmp24 * _tmp557;
  const Scalar _tmp559 = _tmp235 * _tmp484;
  const Scalar _tmp560 = fh1 * (_tmp307 + _tmp376);
  const Scalar _tmp561 = Scalar(80.049599999999998) * _tmp29;
  const Scalar _tmp562 = _tmp237 * _tmp484;
  const Scalar _tmp563 = _tmp387 * _tmp560 + _tmp41 * _tmp561 + _tmp425 * _tmp562 + _tmp425 * fv1 -
                         _tmp430 * _tmp559 + _tmp554 * _tmp8 + _tmp556 + _tmp558;
  const Scalar _tmp564 = _tmp469 * _tmp475;
  const Scalar _tmp565 = _tmp199 * _tmp469;
  const Scalar _tmp566 = _tmp521 * _tmp565;
  const Scalar _tmp567 = Scalar(1.0) * _tmp492;
  const Scalar _tmp568 = _tmp217 * _tmp412;
  const Scalar _tmp569 = _tmp380 * _tmp475;
  const Scalar _tmp570 = _tmp226 * _tmp540;
  const Scalar _tmp571 = _tmp367 * _tmp564;
  const Scalar _tmp572 = -_tmp245 * _tmp340 + _tmp365 * _tmp568 - _tmp365 * _tmp571 +
                         _tmp469 * _tmp569 - _tmp469 * _tmp570 + _tmp478 * _tmp516;
  const Scalar _tmp573 = _tmp479 * _tmp526;
  const Scalar _tmp574 = _tmp367 * _tmp475;
  const Scalar _tmp575 = _tmp365 * _tmp574;
  const Scalar _tmp576 = Scalar(1.0) * _tmp250;
  const Scalar _tmp577 = _tmp24 * _tmp554;
  const Scalar _tmp578 = _tmp234 * _tmp484;
  const Scalar _tmp579 = _tmp32 * _tmp561;
  const Scalar _tmp580 = -_tmp238 * _tmp560 - _tmp41 * _tmp555 - _tmp423 * fv1 + _tmp430 * _tmp578 -
                         _tmp435 * _tmp484 + _tmp557 * _tmp8 - _tmp577 + _tmp579;
  const Scalar _tmp581 = _tmp495 * _tmp504;
  const Scalar _tmp582 =
      _tmp507 *
      (-_tmp462 * _tmp581 +
       _tmp468 *
           (_tmp438 * _tmp480 + _tmp459 * _tmp508 + _tmp460 * _tmp541 +
            _tmp477 * (-_tmp199 * _tmp547 - _tmp227 * _tmp540 + _tmp324 * _tmp548 -
                       _tmp392 * _tmp475 + _tmp404 * _tmp475 + _tmp405 * _tmp475) +
            _tmp483 *
                (-_tmp199 * _tmp538 + _tmp440 * _tmp540 - _tmp475 * _tmp531 + _tmp526 * _tmp529) +
            _tmp488 * _tmp580 +
            _tmp491 * (-_tmp199 * _tmp552 - _tmp281 * _tmp540 + _tmp324 * _tmp553 -
                       _tmp369 * _tmp475 + _tmp379 * _tmp475 + _tmp381 * _tmp475) +
            _tmp494 * _tmp563 - _tmp510 * _tmp511 - _tmp510 * _tmp542 +
            _tmp528 *
                (-_tmp199 * _tmp523 + _tmp291 * _tmp475 + _tmp324 * _tmp527 - _tmp522 - _tmp525) +
            _tmp567 * (-_tmp325 * _tmp564 + _tmp493 * _tmp516 + _tmp540 - _tmp566) +
            _tmp576 * (-_tmp199 * _tmp572 + _tmp324 * _tmp573 + _tmp569 - _tmp570 - _tmp575)));
  const Scalar _tmp583 = _tmp253 + _tmp60;
  const Scalar _tmp584 = 2 * _tmp464;
  const Scalar _tmp585 = 2 * _tmp463;
  const Scalar _tmp586 = _tmp537 * _tmp585 + _tmp584 * (_tmp292 + _tmp583);
  const Scalar _tmp587 = (Scalar(1) / Scalar(2)) / _tmp466;
  const Scalar _tmp588 = Scalar(1.0) * std::cosh(_tmp501);
  const Scalar _tmp589 = -_tmp189 - position_vector(2, 0) + Scalar(48.0);
  const Scalar _tmp590 = 2 * _tmp589;
  const Scalar _tmp591 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp465 + std::pow(_tmp589, Scalar(2))));
  const Scalar _tmp592 = _tmp250 * _tmp416;
  const Scalar _tmp593 = _tmp245 * _tmp438;
  const Scalar _tmp594 = _tmp346 * _tmp433;
  const Scalar _tmp595 = _tmp283 * _tmp388;
  const Scalar _tmp596 = _tmp178 * _tmp239;
  const Scalar _tmp597 = _tmp441 * _tmp449;
  const Scalar _tmp598 = _tmp344 * _tmp597;
  const Scalar _tmp599 = _tmp230 * _tmp239;
  const Scalar _tmp600 = _tmp366 * _tmp576;
  const Scalar _tmp601 = _tmp365 * _tmp600;
  const Scalar _tmp602 = _tmp178 * _tmp388;
  const Scalar _tmp603 = _tmp245 * _tmp250;
  const Scalar _tmp604 = _tmp229 * _tmp597;
  const Scalar _tmp605 = _tmp442 * _tmp449;
  const Scalar _tmp606 = _tmp178 * _tmp605;
  const Scalar _tmp607 = _tmp231 * _tmp455;
  const Scalar _tmp608 = -_tmp216 * _tmp593 + _tmp216 * _tmp598 + _tmp216 * _tmp601 +
                         _tmp231 * _tmp460 - _tmp337 * _tmp592 - _tmp337 * _tmp606 +
                         _tmp346 * _tmp459 + _tmp383 * _tmp602 - _tmp399 * _tmp595 -
                         _tmp399 * _tmp599 + _tmp399 * _tmp604 + _tmp407 * _tmp596 +
                         _tmp411 * _tmp603 - _tmp430 * _tmp594 - _tmp430 * _tmp607;
  const Scalar _tmp609 = _tmp198 * fh1;
  const Scalar _tmp610 = _tmp238 * _tmp609;
  const Scalar _tmp611 = _tmp475 * _tmp492;
  const Scalar _tmp612 = _tmp198 * _tmp469;
  const Scalar _tmp613 = _tmp387 * _tmp609;
  const Scalar _tmp614 = _tmp198 * _tmp487;
  const Scalar _tmp615 = _tmp198 * _tmp449;
  const Scalar _tmp616 = _tmp479 * _tmp609;
  const Scalar _tmp617 = _tmp249 * _tmp616 + _tmp474 * _tmp610 + _tmp482 * _tmp615 +
                         _tmp485 * _tmp614 + _tmp489 * _tmp613 - _tmp611 * _tmp612;
  const Scalar _tmp618 =
      -_tmp216 * _tmp603 + _tmp231 * _tmp239 + _tmp346 * _tmp388 - _tmp447 * _tmp597;
  const Scalar _tmp619 = std::pow(_tmp618, Scalar(-2));
  const Scalar _tmp620 = _tmp617 * _tmp619;
  const Scalar _tmp621 = _tmp239 * _tmp474;
  const Scalar _tmp622 = _tmp489 * _tmp609;
  const Scalar _tmp623 = _tmp237 * _tmp622;
  const Scalar _tmp624 = _tmp235 * _tmp622;
  const Scalar _tmp625 = _tmp474 * _tmp609;
  const Scalar _tmp626 = _tmp234 * _tmp625;
  const Scalar _tmp627 = _tmp250 * _tmp479;
  const Scalar _tmp628 = _tmp198 * _tmp611;
  const Scalar _tmp629 = _tmp469 * _tmp611;
  const Scalar _tmp630 = _tmp485 * _tmp487;
  const Scalar _tmp631 = _tmp475 * _tmp563;
  const Scalar _tmp632 = _tmp388 * _tmp489;
  const Scalar _tmp633 = _tmp198 * _tmp485;
  const Scalar _tmp634 = _tmp249 * _tmp609;
  const Scalar _tmp635 = _tmp318 * _tmp449;
  const Scalar _tmp636 = Scalar(1.0) / (_tmp618);
  const Scalar _tmp637 =
      -_tmp608 * _tmp620 +
      _tmp636 *
          (_tmp198 * _tmp438 * _tmp479 - _tmp325 * _tmp621 - _tmp325 * _tmp627 + _tmp325 * _tmp629 -
           _tmp325 * _tmp630 - _tmp325 * _tmp632 + _tmp425 * _tmp623 - _tmp430 * _tmp624 -
           _tmp430 * _tmp626 + _tmp435 * _tmp625 + _tmp492 * _tmp566 - _tmp516 * _tmp628 +
           _tmp523 * _tmp633 - _tmp529 * _tmp635 + _tmp538 * _tmp615 + _tmp547 * _tmp610 +
           _tmp552 * _tmp613 + _tmp572 * _tmp634 + _tmp580 * _tmp614 - _tmp612 * _tmp631);
  const Scalar _tmp638 =
      std::pow(Scalar(std::pow(_tmp617, Scalar(2)) * _tmp619 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp639 = std::asinh(_tmp617 * _tmp636);
  const Scalar _tmp640 = Scalar(1.0) * _tmp639;
  const Scalar _tmp641 = Scalar(1.0) * _tmp638 * std::cosh(_tmp640);
  const Scalar _tmp642 = Scalar(125.0) - _tmp170;
  const Scalar _tmp643 = 2 * _tmp642;
  const Scalar _tmp644 = -_tmp167 + Scalar(-110.0);
  const Scalar _tmp645 = 2 * _tmp644;
  const Scalar _tmp646 = _tmp643 * (_tmp292 + _tmp61) + _tmp645 * (_tmp298 + _tmp84);
  const Scalar _tmp647 = std::pow(_tmp642, Scalar(2)) + std::pow(_tmp644, Scalar(2));
  const Scalar _tmp648 = std::sqrt(_tmp647);
  const Scalar _tmp649 = (Scalar(1) / Scalar(2)) / _tmp648;
  const Scalar _tmp650 = Scalar(1.4083112389913199) * _tmp608;
  const Scalar _tmp651 = Scalar(1.4083112389913199) * _tmp618;
  const Scalar _tmp652 = _tmp638 * _tmp651;
  const Scalar _tmp653 = Scalar(0.71007031138673404) * _tmp636;
  const Scalar _tmp654 = -_tmp639 * _tmp651 - _tmp648;
  const Scalar _tmp655 = Scalar(0.71007031138673404) * _tmp619 * _tmp654;
  const Scalar _tmp656 = _tmp653 * _tmp654;
  const Scalar _tmp657 = std::cosh(_tmp656);
  const Scalar _tmp658 = -_tmp187 - position_vector(2, 0) + Scalar(48.0);
  const Scalar _tmp659 = 2 * _tmp658;
  const Scalar _tmp660 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp647 + std::pow(_tmp658, Scalar(2))));
  const Scalar _tmp661 = -std::sinh(_tmp640) - std::sinh(_tmp656);
  const Scalar _tmp662 = _tmp347 * _tmp433;
  const Scalar _tmp663 = _tmp232 * _tmp455;
  const Scalar _tmp664 = _tmp228 * _tmp239;
  const Scalar _tmp665 = _tmp221 * _tmp239;
  const Scalar _tmp666 = _tmp282 * _tmp388;
  const Scalar _tmp667 = _tmp221 * _tmp388;
  const Scalar _tmp668 = _tmp232 * _tmp460 - _tmp344 * _tmp664 - _tmp344 * _tmp666 +
                         _tmp347 * _tmp459 + _tmp382 * _tmp667 + _tmp406 * _tmp665 -
                         _tmp430 * _tmp662 - _tmp430 * _tmp663 + _tmp593 - _tmp598 - _tmp601;
  const Scalar _tmp669 = _tmp449 * _tmp472;
  const Scalar _tmp670 = -_tmp239 * _tmp546 - _tmp250 * _tmp478 - _tmp388 * _tmp551 +
                         _tmp440 * _tmp669 - _tmp485 * _tmp486 + _tmp611;
  const Scalar _tmp671 = _tmp232 * _tmp239 + _tmp347 * _tmp388 + _tmp603 + _tmp605;
  const Scalar _tmp672 = Scalar(1.0) / (_tmp671);
  const Scalar _tmp673 = std::asinh(_tmp670 * _tmp672);
  const Scalar _tmp674 = Scalar(1.0) * _tmp673;
  const Scalar _tmp675 = -_tmp206 + Scalar(-125.0);
  const Scalar _tmp676 = Scalar(110.0) - _tmp209;
  const Scalar _tmp677 = std::pow(_tmp675, Scalar(2)) + std::pow(_tmp676, Scalar(2));
  const Scalar _tmp678 = std::sqrt(_tmp677);
  const Scalar _tmp679 = Scalar(1.4083112389913199) * _tmp671;
  const Scalar _tmp680 = -_tmp673 * _tmp679 - _tmp678;
  const Scalar _tmp681 = Scalar(0.71007031138673404) * _tmp672;
  const Scalar _tmp682 = _tmp680 * _tmp681;
  const Scalar _tmp683 = -Scalar(1.4083112389913199) * std::sinh(_tmp674) -
                         Scalar(1.4083112389913199) * std::sinh(_tmp682);
  const Scalar _tmp684 = _tmp388 * _tmp472;
  const Scalar _tmp685 = _tmp239 * _tmp472;
  const Scalar _tmp686 = _tmp475 * _tmp633;
  const Scalar _tmp687 = _tmp433 * _tmp551;
  const Scalar _tmp688 = _tmp227 * _tmp239;
  const Scalar _tmp689 = _tmp281 * _tmp388;
  const Scalar _tmp690 = _tmp449 * _tmp532;
  const Scalar _tmp691 = _tmp518 * _tmp567;
  const Scalar _tmp692 = _tmp455 * _tmp546;
  const Scalar _tmp693 = std::pow(_tmp671, Scalar(-2));
  const Scalar _tmp694 = _tmp670 * _tmp693;
  const Scalar _tmp695 =
      -_tmp668 * _tmp694 +
      _tmp672 * (-_tmp250 * _tmp569 + _tmp250 * _tmp570 + _tmp250 * _tmp575 - _tmp290 * _tmp686 +
                 _tmp369 * _tmp684 - _tmp379 * _tmp684 - _tmp381 * _tmp684 + _tmp392 * _tmp685 -
                 _tmp404 * _tmp685 - _tmp405 * _tmp685 + _tmp430 * _tmp687 + _tmp430 * _tmp692 -
                 _tmp438 * _tmp478 - _tmp459 * _tmp551 - _tmp460 * _tmp546 + _tmp485 * _tmp522 +
                 _tmp485 * _tmp525 - _tmp486 * _tmp580 - _tmp520 * _tmp690 - _tmp520 * _tmp691 +
                 _tmp521 * _tmp688 + _tmp521 * _tmp689 + _tmp531 * _tmp669 + _tmp631);
  const Scalar _tmp696 =
      std::pow(Scalar(std::pow(_tmp670, Scalar(2)) * _tmp693 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp697 = Scalar(1.0) * _tmp696 * std::cosh(_tmp674);
  const Scalar _tmp698 = Scalar(1.4083112389913199) * _tmp673;
  const Scalar _tmp699 = _tmp679 * _tmp696;
  const Scalar _tmp700 = 2 * _tmp676;
  const Scalar _tmp701 = 2 * _tmp675;
  const Scalar _tmp702 = _tmp700 * (_tmp259 + _tmp88) + _tmp701 * (_tmp46 + _tmp583);
  const Scalar _tmp703 = (Scalar(1) / Scalar(2)) / _tmp678;
  const Scalar _tmp704 = Scalar(0.71007031138673404) * _tmp680 * _tmp693;
  const Scalar _tmp705 = std::cosh(_tmp682);
  const Scalar _tmp706 = -_tmp204 - position_vector(2, 0) + Scalar(48.0);
  const Scalar _tmp707 = 2 * _tmp706;
  const Scalar _tmp708 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp677 + std::pow(_tmp706, Scalar(2))));
  const Scalar _tmp709 = -_tmp37 + _tmp38 - _tmp39 - _tmp40;
  const Scalar _tmp710 = Scalar(0.021999999999999999) * _tmp709;
  const Scalar _tmp711 = _tmp13 * _tmp710;
  const Scalar _tmp712 = -_tmp1 + _tmp3 + _tmp5 + _tmp7;
  const Scalar _tmp713 = _tmp54 * _tmp712;
  const Scalar _tmp714 = _tmp711 + _tmp713 + _tmp79 + _tmp82;
  const Scalar _tmp715 = _tmp47 * _tmp712;
  const Scalar _tmp716 = _tmp319 + _tmp715;
  const Scalar _tmp717 = _tmp14 * _tmp24;
  const Scalar _tmp718 = _tmp30 * _tmp712;
  const Scalar _tmp719 = _tmp717 + _tmp718;
  const Scalar _tmp720 = Scalar(0.41999999999999998) * _tmp709;
  const Scalar _tmp721 = _tmp33 * _tmp720;
  const Scalar _tmp722 = -_tmp721;
  const Scalar _tmp723 = _tmp32 * _tmp43;
  const Scalar _tmp724 = -_tmp723;
  const Scalar _tmp725 = _tmp722 + _tmp724;
  const Scalar _tmp726 = _tmp719 + _tmp725;
  const Scalar _tmp727 = _tmp716 + _tmp726;
  const Scalar _tmp728 = _tmp320 * _tmp709;
  const Scalar _tmp729 = _tmp715 + _tmp728;
  const Scalar _tmp730 = _tmp33 * _tmp712;
  const Scalar _tmp731 = Scalar(0.021999999999999999) * _tmp730;
  const Scalar _tmp732 = _tmp29 * _tmp710;
  const Scalar _tmp733 = _tmp138 + _tmp53 + _tmp731 - _tmp732;
  const Scalar _tmp734 = _tmp729 + _tmp733;
  const Scalar _tmp735 = -_tmp717 - _tmp718;
  const Scalar _tmp736 = _tmp725 + _tmp735;
  const Scalar _tmp737 = _tmp104 * (_tmp734 + _tmp736) + _tmp78 * (_tmp714 + _tmp727);
  const Scalar _tmp738 = _tmp124 * _tmp32;
  const Scalar _tmp739 = _tmp126 * _tmp709;
  const Scalar _tmp740 = -_tmp738 - _tmp739;
  const Scalar _tmp741 = Scalar(0.41999999999999998) * _tmp730;
  const Scalar _tmp742 = _tmp29 * _tmp720;
  const Scalar _tmp743 = _tmp114 - _tmp741 - _tmp742;
  const Scalar _tmp744 = _tmp13 * _tmp720;
  const Scalar _tmp745 = -_tmp744;
  const Scalar _tmp746 = _tmp43 * _tmp712;
  const Scalar _tmp747 = _tmp328 + _tmp745 - _tmp746;
  const Scalar _tmp748 = _tmp743 + _tmp747;
  const Scalar _tmp749 = _tmp122 + _tmp744 + _tmp746;
  const Scalar _tmp750 = _tmp740 + _tmp749;
  const Scalar _tmp751 = _tmp309 + _tmp741 + _tmp742;
  const Scalar _tmp752 = _tmp750 + _tmp751;
  const Scalar _tmp753 = _tmp721 + _tmp723;
  const Scalar _tmp754 = _tmp719 + _tmp753;
  const Scalar _tmp755 = -_tmp715;
  const Scalar _tmp756 = -_tmp728 + _tmp755;
  const Scalar _tmp757 = _tmp733 + _tmp754 + _tmp756;
  const Scalar _tmp758 = _tmp735 + _tmp753;
  const Scalar _tmp759 = _tmp519 + _tmp755;
  const Scalar _tmp760 = _tmp758 + _tmp759;
  const Scalar _tmp761 = _tmp584 * (_tmp714 + _tmp760) + _tmp585 * _tmp757;
  const Scalar _tmp762 = _tmp149 - _tmp711 - _tmp713 + _tmp83;
  const Scalar _tmp763 = _tmp727 + _tmp762;
  const Scalar _tmp764 = _tmp243 * _tmp452;
  const Scalar _tmp765 = _tmp716 + _tmp758;
  const Scalar _tmp766 = _tmp762 + _tmp765;
  const Scalar _tmp767 = _tmp212 * _tmp766;
  const Scalar _tmp768 = _tmp139 + _tmp55 - _tmp731 + _tmp732;
  const Scalar _tmp769 = _tmp736 + _tmp756;
  const Scalar _tmp770 = _tmp768 + _tmp769;
  const Scalar _tmp771 = _tmp212 * _tmp770;
  const Scalar _tmp772 = _tmp267 * _tmp763;
  const Scalar _tmp773 = _tmp729 + _tmp736 + _tmp768;
  const Scalar _tmp774 = _tmp160 * _tmp773;
  const Scalar _tmp775 = _tmp295 * _tmp766 + _tmp300 * _tmp770;
  const Scalar _tmp776 = _tmp332 * _tmp775;
  const Scalar _tmp777 = _tmp304 * _tmp775;
  const Scalar _tmp778 = _tmp176 * _tmp767 - _tmp176 * _tmp777 - _tmp213 * _tmp772 +
                         _tmp213 * _tmp774 - _tmp771 + _tmp776;
  const Scalar _tmp779 = _tmp754 + _tmp768;
  const Scalar _tmp780 = _tmp729 + _tmp779;
  const Scalar _tmp781 = _tmp173 * _tmp780;
  const Scalar _tmp782 = _tmp726 + _tmp759;
  const Scalar _tmp783 = _tmp762 + _tmp782;
  const Scalar _tmp784 = _tmp257 * _tmp783 + _tmp261 * _tmp780;
  const Scalar _tmp785 = _tmp269 * _tmp784;
  const Scalar _tmp786 = _tmp173 * _tmp783;
  const Scalar _tmp787 = _tmp265 * _tmp784;
  const Scalar _tmp788 = -_tmp174 * _tmp772 + _tmp174 * _tmp774 - _tmp176 * _tmp785 +
                         _tmp176 * _tmp786 - _tmp781 + _tmp787;
  const Scalar _tmp789 = _tmp202 * _tmp788;
  const Scalar _tmp790 = _tmp738 + _tmp739;
  const Scalar _tmp791 = _tmp748 + _tmp790;
  const Scalar _tmp792 = _tmp747 + _tmp751;
  const Scalar _tmp793 = _tmp790 + _tmp792;
  const Scalar _tmp794 = _tmp49 * _tmp709;
  const Scalar _tmp795 = _tmp322 * _tmp712 + _tmp48;
  const Scalar _tmp796 = _tmp794 + _tmp795 + _tmp86;
  const Scalar _tmp797 = _tmp318 * _tmp796;
  const Scalar _tmp798 = _tmp288 * _tmp712;
  const Scalar _tmp799 = _tmp287 * _tmp32 + _tmp798;
  const Scalar _tmp800 = _tmp198 * _tmp799;
  const Scalar _tmp801 = _tmp749 + _tmp790;
  const Scalar _tmp802 = _tmp743 + _tmp801;
  const Scalar _tmp803 = _tmp174 * _tmp791;
  const Scalar _tmp804 = _tmp178 * (-_tmp174 * _tmp802 - _tmp306 * _tmp783 + _tmp314 * _tmp784 +
                                    _tmp315 * _tmp783 - _tmp316 * _tmp784 + _tmp803);
  const Scalar _tmp805 = _tmp189 * _tmp767;
  const Scalar _tmp806 = _tmp176 * _tmp791;
  const Scalar _tmp807 = _tmp175 * _tmp802 - _tmp176 * _tmp803 + _tmp187 * _tmp781 -
                         _tmp187 * _tmp787 + _tmp190 * _tmp785 - _tmp190 * _tmp786 +
                         _tmp201 * _tmp772 - _tmp201 * _tmp774;
  const Scalar _tmp808 = -_tmp176 * _tmp805 + _tmp190 * _tmp777 - _tmp192 * _tmp778 +
                         _tmp204 * _tmp771 - _tmp204 * _tmp776 - _tmp213 * _tmp806 +
                         _tmp214 * _tmp793 - _tmp216 * _tmp807 + _tmp219 * _tmp772 -
                         _tmp219 * _tmp774 + _tmp339 * _tmp788;
  const Scalar _tmp809 = -_tmp189 * _tmp777 - _tmp204 * _tmp767 + _tmp204 * _tmp777 +
                         _tmp213 * _tmp791 - _tmp213 * _tmp793 - _tmp215 * _tmp804 -
                         _tmp217 * _tmp800 - _tmp218 * _tmp808 - _tmp275 * _tmp778 +
                         _tmp326 * _tmp797 + _tmp338 * _tmp789 + _tmp805;
  const Scalar _tmp810 = _tmp343 * _tmp809;
  const Scalar _tmp811 = _tmp213 * _tmp810;
  const Scalar _tmp812 = _tmp148 * _tmp763 + _tmp158 * _tmp773;
  const Scalar _tmp813 = _tmp357 * _tmp812;
  const Scalar _tmp814 = _tmp353 * _tmp812;
  const Scalar _tmp815 = _tmp182 * (_tmp179 * _tmp773 - _tmp180 * _tmp773 + _tmp350 * _tmp763 -
                                    _tmp351 * _tmp763 - _tmp352 * _tmp814 + _tmp355 * _tmp814);
  const Scalar _tmp816 = _tmp359 * _tmp763;
  const Scalar _tmp817 = -_tmp169 * _tmp781 + _tmp169 * _tmp787 + _tmp171 * _tmp781 +
                         _tmp174 * _tmp813 + _tmp174 * _tmp815 - _tmp174 * _tmp816 -
                         _tmp175 * _tmp783 - _tmp183 * _tmp785 + _tmp183 * _tmp786 +
                         _tmp361 * _tmp783 - _tmp362 * _tmp784;
  const Scalar _tmp818 = _tmp183 * _tmp767 - _tmp183 * _tmp777 - _tmp205 * _tmp771 +
                         _tmp205 * _tmp776 + _tmp207 * _tmp771 + _tmp208 * _tmp767 -
                         _tmp208 * _tmp777 + _tmp213 * _tmp813 + _tmp213 * _tmp815 -
                         _tmp213 * _tmp816 - _tmp214 * _tmp766 - _tmp216 * _tmp817 -
                         _tmp274 * _tmp778 + _tmp364 * _tmp788;
  const Scalar _tmp819 = _tmp284 * _tmp788;
  const Scalar _tmp820 = _tmp393 * _tmp799 - _tmp395 * _tmp797 + _tmp396 * _tmp807 +
                         _tmp397 * _tmp789 - _tmp398 * _tmp819 - Scalar(1.0) * _tmp804;
  const Scalar _tmp821 = _tmp226 * (-_tmp185 * _tmp817 - _tmp223 * _tmp820 + _tmp401 * _tmp788 +
                                    _tmp402 * _tmp810 - _tmp403 * _tmp818);
  const Scalar _tmp822 = _tmp224 * _tmp225;
  const Scalar _tmp823 = _tmp809 * _tmp822;
  const Scalar _tmp824 = _tmp391 * _tmp818;
  const Scalar _tmp825 = _tmp820 + _tmp821 + _tmp823 - _tmp824;
  const Scalar _tmp826 = _tmp348 * _tmp809;
  const Scalar _tmp827 = _tmp228 * _tmp826 - _tmp229 * _tmp825 - _tmp232 * _tmp778;
  const Scalar _tmp828 = _tmp243 * _tmp763;
  const Scalar _tmp829 = _tmp756 + _tmp779;
  const Scalar _tmp830 = _tmp760 + _tmp762;
  const Scalar _tmp831 = _tmp424 * _tmp829 + _tmp426 * _tmp830;
  const Scalar _tmp832 = _tmp429 * _tmp831;
  const Scalar _tmp833 = _tmp237 * _tmp830;
  const Scalar _tmp834 = _tmp833 * fh1;
  const Scalar _tmp835 = _tmp368 * _tmp818;
  const Scalar _tmp836 = _tmp191 * _tmp370;
  const Scalar _tmp837 = -_tmp189 * _tmp772 + _tmp189 * _tmp774 - _tmp192 * _tmp772 +
                         _tmp192 * _tmp774 + _tmp372 * _tmp807 - _tmp788 * _tmp836 + _tmp806;
  const Scalar _tmp838 = _tmp176 * _tmp804 - _tmp218 * _tmp837 - _tmp275 * _tmp772 +
                         _tmp275 * _tmp774 - _tmp277 * _tmp799 - _tmp370 * _tmp789 +
                         _tmp374 * _tmp797 + _tmp752;
  const Scalar _tmp839 = _tmp184 * _tmp370;
  const Scalar _tmp840 = _tmp226 * (-_tmp223 * _tmp838 - _tmp274 * _tmp772 + _tmp274 * _tmp774 -
                                    _tmp279 * _tmp818 + _tmp372 * _tmp817 + _tmp373 * _tmp810 -
                                    _tmp788 * _tmp839 - _tmp813 - _tmp815 + _tmp816);
  const Scalar _tmp841 = _tmp225 * _tmp280;
  const Scalar _tmp842 = _tmp809 * _tmp841;
  const Scalar _tmp843 = -_tmp835 + _tmp838 + _tmp840 + _tmp842;
  const Scalar _tmp844 =
      -_tmp229 * _tmp843 + _tmp282 * _tmp826 - _tmp347 * _tmp778 + _tmp772 - _tmp774;
  const Scalar _tmp845 = _tmp338 * _tmp788;
  const Scalar _tmp846 = _tmp458 * _tmp829;
  const Scalar _tmp847 = _tmp237 * _tmp75;
  const Scalar _tmp848 = _tmp238 * _tmp830 - _tmp248 * _tmp830 - _tmp387 * _tmp829 +
                         _tmp436 * _tmp832 - _tmp437 * _tmp832 + _tmp829 * _tmp847;
  const Scalar _tmp849 = _tmp848 * fh1;
  const Scalar _tmp850 =
      _tmp240 * _tmp828 - _tmp241 * _tmp812 + _tmp251 * _tmp828 -
      _tmp389 * (-_tmp282 * _tmp811 - _tmp286 * _tmp788 + _tmp346 * _tmp786 + _tmp347 * _tmp767 -
                 _tmp347 * _tmp777 + _tmp384 * _tmp844 + _tmp385 * _tmp843 - _tmp386 * _tmp784) -
      _tmp408 * (-_tmp228 * _tmp811 - _tmp231 * _tmp785 + _tmp231 * _tmp786 + _tmp232 * _tmp767 -
                 _tmp232 * _tmp777 + _tmp384 * _tmp827 + _tmp385 * _tmp825 - _tmp390 * _tmp788) -
      _tmp409 * _tmp812 -
      _tmp421 * (_tmp245 * _tmp767 - _tmp246 * _tmp786 + _tmp410 * _tmp845 - _tmp413 * _tmp818 +
                 _tmp415 * _tmp818 - _tmp417 * _tmp778 + _tmp419 * _tmp784 - _tmp420 * _tmp775) -
      _tmp432 * _tmp834 + _tmp434 * _tmp832 - _tmp439 * _tmp849 -
      _tmp450 * (-_tmp441 * _tmp811 + _tmp442 * _tmp767 - _tmp442 * _tmp777 + _tmp444 * _tmp788 -
                 _tmp445 * _tmp778 + _tmp446 * _tmp810 + _tmp448 * _tmp785 - _tmp448 * _tmp786) -
      _tmp453 * _tmp812 - _tmp454 * _tmp846 + _tmp456 * _tmp832 + _tmp457 * _tmp828 -
      _tmp461 * _tmp812 + _tmp763 * _tmp764;
  const Scalar _tmp851 = fh1 * (_tmp751 + _tmp801);
  const Scalar _tmp852 = _tmp484 * _tmp832;
  const Scalar _tmp853 = -_tmp235 * _tmp852 + _tmp387 * _tmp851 + _tmp555 * _tmp709 +
                         _tmp557 * _tmp712 + _tmp562 * _tmp830 + _tmp577 + _tmp579 + _tmp830 * fv1;
  const Scalar _tmp854 = _tmp234 * _tmp852 - _tmp238 * _tmp851 - _tmp556 + _tmp558 +
                         _tmp561 * _tmp709 - _tmp562 * _tmp829 -
                         Scalar(80.049599999999998) * _tmp730 - _tmp829 * fv1;
  const Scalar _tmp855 = _tmp574 * _tmp818;
  const Scalar _tmp856 = _tmp512 * _tmp797;
  const Scalar _tmp857 = _tmp469 * _tmp800;
  const Scalar _tmp858 = -_tmp515 * _tmp709 - _tmp798;
  const Scalar _tmp859 = _tmp218 * _tmp858;
  const Scalar _tmp860 = _tmp296 - _tmp794 + _tmp795 + _tmp856 - _tmp857 - _tmp859;
  const Scalar _tmp861 = _tmp539 * _tmp860;
  const Scalar _tmp862 = _tmp226 * _tmp861;
  const Scalar _tmp863 = _tmp225 * _tmp475;
  const Scalar _tmp864 = _tmp809 * _tmp863;
  const Scalar _tmp865 = -_tmp245 * _tmp808 - _tmp469 * _tmp862 + _tmp469 * _tmp864 +
                         _tmp478 * _tmp858 + _tmp568 * _tmp818 - _tmp571 * _tmp818;
  const Scalar _tmp866 = _tmp195 * _tmp800 + _tmp200 * _tmp773 - _tmp530 * _tmp797 + _tmp763;
  const Scalar _tmp867 = -_tmp442 * _tmp808 - _tmp473 * _tmp866 + _tmp533 * _tmp860 +
                         _tmp535 * _tmp809 - _tmp536 * _tmp858 + _tmp757;
  const Scalar _tmp868 = _tmp482 * _tmp796;
  const Scalar _tmp869 = _tmp518 * _tmp860;
  const Scalar _tmp870 = -_tmp347 * _tmp808 - _tmp473 * _tmp835 + _tmp473 * _tmp840 +
                         _tmp473 * _tmp842 - _tmp481 * _tmp843 + _tmp549 * _tmp809 -
                         _tmp550 * _tmp869 + _tmp551 * _tmp858 + _tmp837;
  const Scalar _tmp871 = _tmp200 * _tmp869;
  const Scalar _tmp872 = _tmp524 * _tmp797;
  const Scalar _tmp873 = _tmp475 * _tmp800;
  const Scalar _tmp874 =
      -_tmp469 * _tmp871 - _tmp475 * _tmp856 + _tmp475 * _tmp857 + _tmp475 * _tmp859;
  const Scalar _tmp875 = _tmp480 * fh1;
  const Scalar _tmp876 = -_tmp185 * _tmp807 - _tmp232 * _tmp808 + _tmp473 * _tmp821 +
                         _tmp473 * _tmp823 - _tmp473 * _tmp824 - _tmp481 * _tmp825 +
                         _tmp543 * _tmp809 - _tmp544 * _tmp869 + _tmp545 * _tmp788 +
                         _tmp546 * _tmp858;
  const Scalar _tmp877 = _tmp509 * _tmp831;
  const Scalar _tmp878 = _tmp565 * _tmp869;
  const Scalar _tmp879 =
      _tmp507 *
      (_tmp468 * (_tmp477 * (-_tmp199 * _tmp876 - _tmp227 * _tmp861 + _tmp475 * _tmp821 +
                             _tmp475 * _tmp823 - _tmp475 * _tmp824 + _tmp548 * _tmp796) +
                  _tmp483 * (-_tmp199 * _tmp867 + _tmp440 * _tmp861 - _tmp475 * _tmp866 +
                             _tmp526 * _tmp868) +
                  _tmp488 * _tmp854 +
                  _tmp491 * (-_tmp199 * _tmp870 - _tmp281 * _tmp861 - _tmp475 * _tmp835 +
                             _tmp475 * _tmp840 + _tmp475 * _tmp842 + _tmp553 * _tmp796) +
                  _tmp494 * _tmp853 + _tmp508 * _tmp834 - _tmp511 * _tmp877 +
                  _tmp528 * (-_tmp199 * _tmp874 + _tmp527 * _tmp796 - _tmp871 - _tmp872 + _tmp873) +
                  _tmp541 * _tmp846 - _tmp542 * _tmp877 +
                  _tmp567 * (_tmp493 * _tmp858 - _tmp564 * _tmp797 + _tmp861 - _tmp878) +
                  _tmp576 * (-_tmp199 * _tmp865 + _tmp573 * _tmp796 - _tmp855 - _tmp862 + _tmp864) +
                  _tmp848 * _tmp875) -
       _tmp581 * _tmp850);
  const Scalar _tmp880 = _tmp643 * (_tmp714 + _tmp765) + _tmp645 * (_tmp733 + _tmp769);
  const Scalar _tmp881 = _tmp600 * _tmp818;
  const Scalar _tmp882 = _tmp245 * fh1;
  const Scalar _tmp883 = _tmp848 * _tmp882;
  const Scalar _tmp884 = _tmp597 * _tmp810;
  const Scalar _tmp885 = _tmp216 * _tmp881 - _tmp216 * _tmp883 + _tmp216 * _tmp884 +
                         _tmp231 * _tmp846 + _tmp346 * _tmp834 - _tmp592 * _tmp778 -
                         _tmp594 * _tmp832 - _tmp595 * _tmp819 + _tmp596 * _tmp827 -
                         _tmp599 * _tmp819 + _tmp602 * _tmp844 + _tmp603 * _tmp845 +
                         _tmp604 * _tmp819 - _tmp606 * _tmp778 - _tmp607 * _tmp832;
  const Scalar _tmp886 = _tmp475 * _tmp853;
  const Scalar _tmp887 =
      -_tmp620 * _tmp885 +
      _tmp636 *
          (_tmp237 * _tmp625 * _tmp829 + _tmp492 * _tmp878 + _tmp610 * _tmp876 - _tmp612 * _tmp886 +
           _tmp613 * _tmp870 + _tmp614 * _tmp854 + _tmp615 * _tmp867 + _tmp616 * _tmp848 -
           _tmp621 * _tmp797 + _tmp622 * _tmp833 - _tmp624 * _tmp832 - _tmp626 * _tmp832 -
           _tmp627 * _tmp797 - _tmp628 * _tmp858 + _tmp629 * _tmp797 - _tmp630 * _tmp797 -
           _tmp632 * _tmp797 + _tmp633 * _tmp874 + _tmp634 * _tmp865 - _tmp635 * _tmp868);
  const Scalar _tmp888 = Scalar(1.4083112389913199) * _tmp885;
  const Scalar _tmp889 = _tmp700 * (_tmp734 + _tmp754) + _tmp701 * (_tmp714 + _tmp782);
  const Scalar _tmp890 = _tmp232 * _tmp846 + _tmp347 * _tmp834 - _tmp662 * _tmp832 -
                         _tmp663 * _tmp832 - _tmp664 * _tmp810 + _tmp665 * _tmp825 -
                         _tmp666 * _tmp810 + _tmp667 * _tmp843 - _tmp881 + _tmp883 - _tmp884;
  const Scalar _tmp891 =
      _tmp672 * (_tmp250 * _tmp855 + _tmp250 * _tmp862 - _tmp250 * _tmp864 - _tmp478 * _tmp849 +
                 _tmp485 * _tmp871 + _tmp485 * _tmp872 - _tmp485 * _tmp873 - _tmp486 * _tmp854 -
                 _tmp546 * _tmp846 - _tmp551 * _tmp834 + _tmp669 * _tmp866 + _tmp684 * _tmp835 -
                 _tmp684 * _tmp840 - _tmp684 * _tmp842 - _tmp685 * _tmp821 - _tmp685 * _tmp823 +
                 _tmp685 * _tmp824 + _tmp687 * _tmp832 + _tmp688 * _tmp869 + _tmp689 * _tmp869 -
                 _tmp690 * _tmp860 - _tmp691 * _tmp860 + _tmp692 * _tmp832 + _tmp886) -
      _tmp694 * _tmp890;
  const Scalar _tmp892 = _tmp32 * _tmp56;
  const Scalar _tmp893 = _tmp52 * _tmp8;
  const Scalar _tmp894 = _tmp42 * _tmp710;
  const Scalar _tmp895 = _tmp17 + _tmp19 - _tmp21 + _tmp23;
  const Scalar _tmp896 = _tmp58 * _tmp895;
  const Scalar _tmp897 = _tmp892 + _tmp893 - _tmp894 - _tmp896;
  const Scalar _tmp898 = _tmp121 + _tmp745;
  const Scalar _tmp899 = _tmp34 * _tmp895;
  const Scalar _tmp900 = _tmp118 - _tmp899;
  const Scalar _tmp901 = _tmp898 + _tmp900;
  const Scalar _tmp902 = _tmp13 * _tmp85;
  const Scalar _tmp903 = _tmp320 * _tmp895;
  const Scalar _tmp904 = _tmp902 + _tmp903;
  const Scalar _tmp905 = _tmp901 + _tmp904;
  const Scalar _tmp906 = _tmp49 * _tmp8;
  const Scalar _tmp907 = _tmp902 + _tmp906;
  const Scalar _tmp908 = _tmp56 * _tmp709;
  const Scalar _tmp909 = _tmp52 * _tmp895;
  const Scalar _tmp910 = _tmp32 * _tmp54;
  const Scalar _tmp911 = _tmp58 * _tmp8;
  const Scalar _tmp912 = _tmp908 + _tmp909 + _tmp910 + _tmp911;
  const Scalar _tmp913 = _tmp120 + _tmp744;
  const Scalar _tmp914 = _tmp900 + _tmp913;
  const Scalar _tmp915 = _tmp912 + _tmp914;
  const Scalar _tmp916 = _tmp104 * (_tmp897 + _tmp905) + _tmp78 * (_tmp907 + _tmp915);
  const Scalar _tmp917 = _tmp124 * _tmp8;
  const Scalar _tmp918 = _tmp126 * _tmp895;
  const Scalar _tmp919 = -_tmp917 - _tmp918;
  const Scalar _tmp920 = _tmp42 * _tmp720;
  const Scalar _tmp921 = _tmp30 * _tmp895;
  const Scalar _tmp922 = _tmp91 - _tmp920 - _tmp921;
  const Scalar _tmp923 = _tmp919 + _tmp922;
  const Scalar _tmp924 = _tmp14 * _tmp895;
  const Scalar _tmp925 = _tmp30 * _tmp8;
  const Scalar _tmp926 = _tmp721 + _tmp724 - _tmp924 + _tmp925;
  const Scalar _tmp927 = -_tmp908 - _tmp909 - _tmp910 - _tmp911;
  const Scalar _tmp928 = _tmp914 + _tmp927;
  const Scalar _tmp929 = _tmp907 + _tmp928;
  const Scalar _tmp930 = _tmp243 * _tmp929;
  const Scalar _tmp931 = -_tmp892 - _tmp893 + _tmp894 + _tmp896;
  const Scalar _tmp932 = _tmp905 + _tmp931;
  const Scalar _tmp933 = _tmp148 * _tmp929 + _tmp158 * _tmp932;
  const Scalar _tmp934 = -_tmp902;
  const Scalar _tmp935 = -_tmp903 + _tmp934;
  const Scalar _tmp936 = _tmp117 + _tmp899;
  const Scalar _tmp937 = _tmp913 + _tmp936;
  const Scalar _tmp938 = _tmp935 + _tmp937;
  const Scalar _tmp939 = _tmp931 + _tmp938;
  const Scalar _tmp940 = _tmp237 * _tmp939;
  const Scalar _tmp941 = _tmp940 * fh1;
  const Scalar _tmp942 = _tmp898 + _tmp936;
  const Scalar _tmp943 = -_tmp906 + _tmp934;
  const Scalar _tmp944 = _tmp942 + _tmp943;
  const Scalar _tmp945 = _tmp927 + _tmp944;
  const Scalar _tmp946 = _tmp424 * _tmp939 + _tmp426 * _tmp945;
  const Scalar _tmp947 = _tmp429 * _tmp946;
  const Scalar _tmp948 = _tmp904 + _tmp937;
  const Scalar _tmp949 = _tmp931 + _tmp948;
  const Scalar _tmp950 = _tmp173 * _tmp949;
  const Scalar _tmp951 = _tmp928 + _tmp943;
  const Scalar _tmp952 = _tmp173 * _tmp951;
  const Scalar _tmp953 = _tmp267 * _tmp929;
  const Scalar _tmp954 = _tmp257 * _tmp951 + _tmp261 * _tmp949;
  const Scalar _tmp955 = _tmp269 * _tmp954;
  const Scalar _tmp956 = _tmp160 * _tmp932;
  const Scalar _tmp957 = _tmp265 * _tmp954;
  const Scalar _tmp958 = -_tmp174 * _tmp953 + _tmp174 * _tmp956 + _tmp176 * _tmp952 -
                         _tmp176 * _tmp955 - _tmp950 + _tmp957;
  const Scalar _tmp959 = _tmp338 * _tmp958;
  const Scalar _tmp960 = _tmp907 + _tmp942;
  const Scalar _tmp961 = _tmp927 + _tmp960;
  const Scalar _tmp962 = _tmp901 + _tmp935;
  const Scalar _tmp963 = _tmp931 + _tmp962;
  const Scalar _tmp964 = _tmp295 * _tmp961 + _tmp300 * _tmp963;
  const Scalar _tmp965 = _tmp212 * _tmp961;
  const Scalar _tmp966 = _tmp332 * _tmp964;
  const Scalar _tmp967 = _tmp304 * _tmp964;
  const Scalar _tmp968 = _tmp212 * _tmp963;
  const Scalar _tmp969 = _tmp176 * _tmp965 - _tmp176 * _tmp967 - _tmp213 * _tmp953 +
                         _tmp213 * _tmp956 + _tmp966 - _tmp968;
  const Scalar _tmp970 = _tmp353 * _tmp933;
  const Scalar _tmp971 = _tmp182 * (_tmp179 * _tmp932 - _tmp180 * _tmp932 + _tmp350 * _tmp929 -
                                    _tmp351 * _tmp929 - _tmp352 * _tmp970 + _tmp355 * _tmp970);
  const Scalar _tmp972 = _tmp359 * _tmp929;
  const Scalar _tmp973 = _tmp357 * _tmp933;
  const Scalar _tmp974 = -_tmp169 * _tmp950 + _tmp169 * _tmp957 + _tmp171 * _tmp950 +
                         _tmp174 * _tmp971 - _tmp174 * _tmp972 + _tmp174 * _tmp973 -
                         _tmp175 * _tmp951 + _tmp183 * _tmp952 - _tmp183 * _tmp955 +
                         _tmp361 * _tmp951 - _tmp362 * _tmp954;
  const Scalar _tmp975 = _tmp183 * _tmp965 - _tmp183 * _tmp967 + _tmp205 * _tmp966 -
                         _tmp205 * _tmp968 + _tmp207 * _tmp968 + _tmp208 * _tmp965 -
                         _tmp208 * _tmp967 + _tmp213 * _tmp971 - _tmp213 * _tmp972 +
                         _tmp213 * _tmp973 - _tmp214 * _tmp961 - _tmp216 * _tmp974 -
                         _tmp274 * _tmp969 + _tmp364 * _tmp958;
  const Scalar _tmp976 = _tmp238 * _tmp945 - _tmp248 * _tmp945 - _tmp387 * _tmp939 +
                         _tmp436 * _tmp947 - _tmp437 * _tmp947 + _tmp847 * _tmp939;
  const Scalar _tmp977 = _tmp976 * fh1;
  const Scalar _tmp978 = _tmp49 * _tmp895;
  const Scalar _tmp979 = _tmp320 * _tmp8;
  const Scalar _tmp980 = _tmp29 * _tmp85 + _tmp47 * _tmp709;
  const Scalar _tmp981 = _tmp978 + _tmp979 + _tmp980;
  const Scalar _tmp982 = _tmp318 * _tmp981;
  const Scalar _tmp983 = _tmp202 * _tmp958;
  const Scalar _tmp984 = _tmp288 * _tmp32;
  const Scalar _tmp985 = _tmp287 * _tmp8 + _tmp984;
  const Scalar _tmp986 = _tmp198 * _tmp985;
  const Scalar _tmp987 = _tmp722 + _tmp723 + _tmp924 - _tmp925;
  const Scalar _tmp988 = _tmp917 + _tmp918;
  const Scalar _tmp989 = _tmp987 + _tmp988;
  const Scalar _tmp990 = _tmp922 + _tmp989;
  const Scalar _tmp991 = _tmp926 + _tmp988;
  const Scalar _tmp992 = _tmp922 + _tmp991;
  const Scalar _tmp993 = -_tmp174 * _tmp990 + _tmp174 * _tmp992 - _tmp306 * _tmp951 +
                         _tmp314 * _tmp954 + _tmp315 * _tmp951 - _tmp316 * _tmp954;
  const Scalar _tmp994 = _tmp189 * _tmp956;
  const Scalar _tmp995 = _tmp176 * _tmp992;
  const Scalar _tmp996 = _tmp258 + _tmp920 + _tmp921;
  const Scalar _tmp997 = _tmp991 + _tmp996;
  const Scalar _tmp998 = -_tmp174 * _tmp994 - _tmp174 * _tmp995 + _tmp175 * _tmp990 +
                         _tmp187 * _tmp950 - _tmp187 * _tmp957 - _tmp190 * _tmp952 +
                         _tmp190 * _tmp955 + _tmp201 * _tmp953;
  const Scalar _tmp999 = -_tmp190 * _tmp965 + _tmp190 * _tmp967 - _tmp192 * _tmp969 -
                         _tmp204 * _tmp966 + _tmp204 * _tmp968 - _tmp213 * _tmp994 -
                         _tmp213 * _tmp995 + _tmp214 * _tmp997 - _tmp216 * _tmp998 +
                         _tmp219 * _tmp953 + _tmp339 * _tmp958;
  const Scalar _tmp1000 = _tmp189 * _tmp965 - _tmp189 * _tmp967 - _tmp204 * _tmp965 +
                          _tmp204 * _tmp967 + _tmp213 * _tmp992 - _tmp213 * _tmp997 -
                          _tmp216 * _tmp993 - _tmp217 * _tmp986 - _tmp218 * _tmp999 -
                          _tmp275 * _tmp969 + _tmp326 * _tmp982 + _tmp338 * _tmp983;
  const Scalar _tmp1001 = _tmp1000 * _tmp343;
  const Scalar _tmp1002 = _tmp1001 * _tmp213;
  const Scalar _tmp1003 = _tmp458 * _tmp945;
  const Scalar _tmp1004 = _tmp1000 * _tmp841;
  const Scalar _tmp1005 = -_tmp189 * _tmp953 - _tmp192 * _tmp953 + _tmp192 * _tmp956 +
                          _tmp372 * _tmp998 - _tmp836 * _tmp958 + _tmp994 + _tmp995;
  const Scalar _tmp1006 = _tmp919 + _tmp996;
  const Scalar _tmp1007 = _tmp1006 + _tmp987;
  const Scalar _tmp1008 = -_tmp1005 * _tmp218 + _tmp1007 - _tmp275 * _tmp953 + _tmp275 * _tmp956 -
                          _tmp277 * _tmp985 - _tmp370 * _tmp983 + _tmp372 * _tmp993 +
                          _tmp374 * _tmp982;
  const Scalar _tmp1009 = _tmp226 * (_tmp1001 * _tmp373 - _tmp1008 * _tmp223 - _tmp274 * _tmp953 +
                                     _tmp274 * _tmp956 - _tmp279 * _tmp975 + _tmp372 * _tmp974 -
                                     _tmp839 * _tmp958 - _tmp971 + _tmp972 - _tmp973);
  const Scalar _tmp1010 = _tmp367 * _tmp975;
  const Scalar _tmp1011 = _tmp1010 * _tmp280;
  const Scalar _tmp1012 = _tmp1004 + _tmp1008 + _tmp1009 - _tmp1011;
  const Scalar _tmp1013 =
      _tmp1000 * _tmp282 * _tmp348 - _tmp1012 * _tmp229 - _tmp347 * _tmp969 + _tmp953 - _tmp956;
  const Scalar _tmp1014 = _tmp1000 * _tmp822;
  const Scalar _tmp1015 = _tmp1010 * _tmp224;
  const Scalar _tmp1016 = _tmp284 * _tmp958;
  const Scalar _tmp1017 = -_tmp1016 * _tmp398 - _tmp185 * _tmp993 + _tmp393 * _tmp985 -
                          _tmp395 * _tmp982 + _tmp396 * _tmp998 + _tmp397 * _tmp983;
  const Scalar _tmp1018 = _tmp226 * (_tmp1001 * _tmp402 - _tmp1017 * _tmp223 - _tmp185 * _tmp974 +
                                     _tmp401 * _tmp958 - _tmp403 * _tmp975);
  const Scalar _tmp1019 = _tmp1014 - _tmp1015 + _tmp1017 + _tmp1018;
  const Scalar _tmp1020 = _tmp1000 * _tmp228;
  const Scalar _tmp1021 = -_tmp1019 * _tmp229 + _tmp1020 * _tmp348 - _tmp232 * _tmp969;
  const Scalar _tmp1022 = _tmp1020 * _tmp343;
  const Scalar _tmp1023 =
      -_tmp1003 * _tmp432 + _tmp240 * _tmp930 - _tmp241 * _tmp933 + _tmp251 * _tmp930 -
      _tmp389 * (-_tmp1002 * _tmp282 + _tmp1012 * _tmp385 + _tmp1013 * _tmp384 - _tmp286 * _tmp958 +
                 _tmp346 * _tmp952 + _tmp347 * _tmp965 - _tmp347 * _tmp967 - _tmp386 * _tmp954) -
      _tmp408 * (_tmp1019 * _tmp385 + _tmp1021 * _tmp384 - _tmp1022 * _tmp213 + _tmp231 * _tmp952 -
                 _tmp231 * _tmp955 + _tmp232 * _tmp965 - _tmp232 * _tmp967 - _tmp390 * _tmp958) -
      _tmp409 * _tmp933 -
      _tmp421 * (_tmp245 * _tmp965 - _tmp246 * _tmp952 + _tmp410 * _tmp959 - _tmp413 * _tmp975 +
                 _tmp415 * _tmp975 - _tmp417 * _tmp969 + _tmp419 * _tmp954 - _tmp420 * _tmp964) +
      _tmp434 * _tmp947 - _tmp439 * _tmp977 -
      _tmp450 * (_tmp1001 * _tmp446 - _tmp1002 * _tmp441 + _tmp442 * _tmp965 - _tmp442 * _tmp967 +
                 _tmp444 * _tmp958 - _tmp445 * _tmp969 - _tmp448 * _tmp952 + _tmp448 * _tmp955) -
      _tmp453 * _tmp933 - _tmp454 * _tmp941 + _tmp456 * _tmp947 + _tmp457 * _tmp930 -
      _tmp461 * _tmp933 + _tmp764 * _tmp929;
  const Scalar _tmp1024 = _tmp897 + _tmp938;
  const Scalar _tmp1025 = _tmp1024 * _tmp585 + _tmp584 * (_tmp912 + _tmp944);
  const Scalar _tmp1026 = _tmp469 * _tmp986;
  const Scalar _tmp1027 = -_tmp515 * _tmp895 - _tmp984;
  const Scalar _tmp1028 = _tmp1027 * _tmp218;
  const Scalar _tmp1029 = _tmp512 * _tmp982;
  const Scalar _tmp1030 = -_tmp1026 - _tmp1028 + _tmp1029 - _tmp978 - _tmp979 + _tmp980;
  const Scalar _tmp1031 = _tmp1030 * _tmp539;
  const Scalar _tmp1032 = _tmp1030 * _tmp518;
  const Scalar _tmp1033 = _tmp1032 * _tmp565;
  const Scalar _tmp1034 = _tmp526 * _tmp981;
  const Scalar _tmp1035 = _tmp221 * _tmp999;
  const Scalar _tmp1036 = _tmp195 * _tmp986 + _tmp200 * _tmp932 - _tmp530 * _tmp982 + _tmp929;
  const Scalar _tmp1037 = _tmp1000 * _tmp535 + _tmp1024 - _tmp1027 * _tmp536 + _tmp1030 * _tmp533 -
                          _tmp1035 * _tmp441 - _tmp1036 * _tmp473;
  const Scalar _tmp1038 = _tmp509 * _tmp946;
  const Scalar _tmp1039 = fh1 * (_tmp989 + _tmp996);
  const Scalar _tmp1040 = _tmp1039 * _tmp387 + _tmp32 * _tmp557 + _tmp554 * _tmp709 +
                          _tmp555 * _tmp895 - _tmp559 * _tmp947 + _tmp561 * _tmp8 +
                          _tmp562 * _tmp945 + _tmp945 * fv1;
  const Scalar _tmp1041 = _tmp1032 * _tmp200;
  const Scalar _tmp1042 =
      _tmp1026 * _tmp475 + _tmp1028 * _tmp475 - _tmp1029 * _tmp475 - _tmp1041 * _tmp469;
  const Scalar _tmp1043 = _tmp524 * _tmp982;
  const Scalar _tmp1044 = _tmp1031 * _tmp226;
  const Scalar _tmp1045 = _tmp1000 * _tmp863;
  const Scalar _tmp1046 = _tmp1010 * _tmp475;
  const Scalar _tmp1047 = -_tmp1010 * _tmp564 + _tmp1027 * _tmp478 - _tmp1044 * _tmp469 +
                          _tmp1045 * _tmp469 - _tmp245 * _tmp999 + _tmp568 * _tmp975;
  const Scalar _tmp1048 = -_tmp1039 * _tmp238 - _tmp32 * _tmp554 - _tmp484 * _tmp940 -
                          _tmp555 * _tmp8 + _tmp557 * _tmp709 + _tmp561 * _tmp895 +
                          _tmp578 * _tmp947 - _tmp939 * fv1;
  const Scalar _tmp1049 = _tmp1014 * _tmp473 - _tmp1015 * _tmp473 + _tmp1018 * _tmp473 -
                          _tmp1019 * _tmp481 + _tmp1020 * _tmp534 + _tmp1027 * _tmp546 -
                          _tmp1032 * _tmp544 - _tmp185 * _tmp998 - _tmp232 * _tmp999 +
                          _tmp545 * _tmp958;
  const Scalar _tmp1050 = _tmp1000 * _tmp549 + _tmp1004 * _tmp473 + _tmp1005 + _tmp1009 * _tmp473 -
                          _tmp1011 * _tmp473 - _tmp1012 * _tmp481 + _tmp1027 * _tmp551 -
                          _tmp1032 * _tmp550 - _tmp1035 * _tmp282;
  const Scalar _tmp1051 =
      _tmp507 *
      (-_tmp1023 * _tmp581 +
       _tmp468 *
           (_tmp1003 * _tmp508 - _tmp1038 * _tmp511 - _tmp1038 * _tmp542 + _tmp1040 * _tmp494 +
            _tmp1048 * _tmp488 +
            _tmp477 * (_tmp1014 * _tmp475 - _tmp1015 * _tmp475 + _tmp1018 * _tmp475 -
                       _tmp1031 * _tmp227 + _tmp1034 * _tmp474 - _tmp1049 * _tmp199) +
            _tmp483 * (_tmp1031 * _tmp440 + _tmp1034 * _tmp482 - _tmp1036 * _tmp475 -
                       _tmp1037 * _tmp199) +
            _tmp491 * (_tmp1004 * _tmp475 + _tmp1009 * _tmp475 - _tmp1011 * _tmp475 -
                       _tmp1031 * _tmp281 + _tmp1034 * _tmp489 - _tmp1050 * _tmp199) +
            _tmp528 * (_tmp1034 * _tmp487 - _tmp1041 - _tmp1042 * _tmp199 - _tmp1043 +
                       _tmp475 * _tmp986) +
            _tmp541 * _tmp941 +
            _tmp567 * (_tmp1027 * _tmp493 + _tmp1031 - _tmp1033 - _tmp564 * _tmp982) +
            _tmp576 * (_tmp1034 * _tmp479 - _tmp1044 + _tmp1045 - _tmp1046 - _tmp1047 * _tmp199) +
            _tmp875 * _tmp976));
  const Scalar _tmp1052 = _tmp882 * _tmp976;
  const Scalar _tmp1053 = _tmp600 * _tmp975;
  const Scalar _tmp1054 = _tmp1001 * _tmp597;
  const Scalar _tmp1055 = _tmp1003 * _tmp346 + _tmp1013 * _tmp602 - _tmp1016 * _tmp595 -
                          _tmp1016 * _tmp599 + _tmp1016 * _tmp604 + _tmp1021 * _tmp596 -
                          _tmp1052 * _tmp216 + _tmp1053 * _tmp216 + _tmp1054 * _tmp216 +
                          _tmp231 * _tmp941 - _tmp592 * _tmp969 - _tmp594 * _tmp947 +
                          _tmp603 * _tmp959 - _tmp606 * _tmp969 - _tmp607 * _tmp947;
  const Scalar _tmp1056 = _tmp1040 * _tmp475;
  const Scalar _tmp1057 =
      -_tmp1055 * _tmp620 +
      _tmp636 * (-_tmp1027 * _tmp628 + _tmp1033 * _tmp492 + _tmp1037 * _tmp615 +
                 _tmp1042 * _tmp633 + _tmp1047 * _tmp634 + _tmp1048 * _tmp614 + _tmp1049 * _tmp610 +
                 _tmp1050 * _tmp613 - _tmp1056 * _tmp612 - _tmp482 * _tmp635 * _tmp981 +
                 _tmp616 * _tmp976 - _tmp621 * _tmp982 + _tmp623 * _tmp945 - _tmp624 * _tmp947 +
                 _tmp625 * _tmp940 - _tmp626 * _tmp947 - _tmp627 * _tmp982 + _tmp629 * _tmp982 -
                 _tmp630 * _tmp982 - _tmp632 * _tmp982);
  const Scalar _tmp1058 = Scalar(1.4083112389913199) * _tmp1055;
  const Scalar _tmp1059 = _tmp643 * (_tmp912 + _tmp960) + _tmp645 * (_tmp897 + _tmp962);
  const Scalar _tmp1060 = -_tmp1001 * _tmp666 + _tmp1003 * _tmp347 + _tmp1012 * _tmp667 +
                          _tmp1019 * _tmp665 - _tmp1022 * _tmp239 + _tmp1052 - _tmp1053 - _tmp1054 +
                          _tmp232 * _tmp941 - _tmp662 * _tmp947 - _tmp663 * _tmp947;
  const Scalar _tmp1061 =
      -_tmp1060 * _tmp694 +
      _tmp672 *
          (-_tmp1003 * _tmp551 - _tmp1004 * _tmp684 - _tmp1009 * _tmp684 + _tmp1011 * _tmp684 -
           _tmp1014 * _tmp685 + _tmp1015 * _tmp685 - _tmp1018 * _tmp685 - _tmp1030 * _tmp690 -
           _tmp1030 * _tmp691 + _tmp1032 * _tmp688 + _tmp1032 * _tmp689 + _tmp1036 * _tmp669 +
           _tmp1041 * _tmp485 + _tmp1043 * _tmp485 + _tmp1044 * _tmp250 - _tmp1045 * _tmp250 +
           _tmp1046 * _tmp250 - _tmp1048 * _tmp486 + _tmp1056 - _tmp478 * _tmp977 -
           _tmp546 * _tmp941 - _tmp686 * _tmp985 + _tmp687 * _tmp947 + _tmp692 * _tmp947);
  const Scalar _tmp1062 = _tmp700 * (_tmp897 + _tmp948) + _tmp701 * (_tmp915 + _tmp943);

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = _tmp105 * _tmp109 - _tmp137 * (_tmp105 + _tmp136 * (_tmp115 + _tmp129));
  _res(1, 0) =
      _tmp462 * _tmp502 +
      _tmp497 *
          (-_tmp503 * (-_tmp462 * _tmp505 +
                       _tmp499 * (-_tmp462 * _tmp506 - _tmp497 * _tmp582 - _tmp586 * _tmp587)) -
           _tmp582 * _tmp588) -
      _tmp591 * (_tmp377 * _tmp590 + _tmp586);
  _res(2, 0) =
      _tmp650 * _tmp661 +
      _tmp651 * (-_tmp637 * _tmp641 -
                 _tmp657 * (-_tmp608 * _tmp655 + _tmp653 * (-_tmp637 * _tmp652 - _tmp639 * _tmp650 -
                                                            _tmp646 * _tmp649))) -
      _tmp660 * (_tmp646 + _tmp659 * (_tmp128 + _tmp330));
  _res(3, 0) =
      _tmp668 * _tmp683 +
      _tmp679 * (-_tmp695 * _tmp697 -
                 _tmp705 * (-_tmp668 * _tmp704 + _tmp681 * (-_tmp668 * _tmp698 - _tmp695 * _tmp699 -
                                                            _tmp702 * _tmp703))) -
      _tmp708 * (_tmp702 + _tmp707 * (_tmp129 + _tmp310));
  _res(0, 1) = _tmp109 * _tmp737 - _tmp137 * (_tmp136 * (_tmp740 + _tmp748) + _tmp737);
  _res(1, 1) =
      _tmp497 *
          (-_tmp503 * (_tmp499 * (-_tmp497 * _tmp879 - _tmp506 * _tmp850 - _tmp587 * _tmp761) -
                       _tmp505 * _tmp850) -
           _tmp588 * _tmp879) +
      _tmp502 * _tmp850 - _tmp591 * (_tmp590 * _tmp752 + _tmp761);
  _res(2, 1) =
      _tmp651 * (-_tmp641 * _tmp887 -
                 _tmp657 * (_tmp653 * (-_tmp639 * _tmp888 - _tmp649 * _tmp880 - _tmp652 * _tmp887) -
                            _tmp655 * _tmp885)) -
      _tmp660 * (_tmp659 * (_tmp740 + _tmp792) + _tmp880) + _tmp661 * _tmp888;
  _res(3, 1) =
      _tmp679 * (-_tmp697 * _tmp891 -
                 _tmp705 * (_tmp681 * (-_tmp698 * _tmp890 - _tmp699 * _tmp891 - _tmp703 * _tmp889) -
                            _tmp704 * _tmp890)) +
      _tmp683 * _tmp890 - _tmp708 * (_tmp707 * (_tmp743 + _tmp750) + _tmp889);
  _res(0, 2) = _tmp109 * _tmp916 - _tmp137 * (_tmp136 * (_tmp923 + _tmp926) + _tmp916);
  _res(1, 2) =
      _tmp1023 * _tmp502 +
      _tmp497 *
          (-_tmp1051 * _tmp588 -
           _tmp503 * (-_tmp1023 * _tmp505 +
                      _tmp499 * (-_tmp1023 * _tmp506 - _tmp1025 * _tmp587 - _tmp1051 * _tmp497))) -
      _tmp591 * (_tmp1007 * _tmp590 + _tmp1025);
  _res(2, 2) =
      _tmp1058 * _tmp661 +
      _tmp651 *
          (-_tmp1057 * _tmp641 -
           _tmp657 * (-_tmp1055 * _tmp655 +
                      _tmp653 * (-_tmp1057 * _tmp652 - _tmp1058 * _tmp639 - _tmp1059 * _tmp649))) -
      _tmp660 * (_tmp1059 + _tmp659 * (_tmp1006 + _tmp926));
  _res(3, 2) =
      _tmp1060 * _tmp683 +
      _tmp679 *
          (-_tmp1061 * _tmp697 -
           _tmp705 * (-_tmp1060 * _tmp704 +
                      _tmp681 * (-_tmp1060 * _tmp698 - _tmp1061 * _tmp699 - _tmp1062 * _tmp703))) -
      _tmp708 * (_tmp1062 + _tmp707 * (_tmp923 + _tmp987));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
