// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost1_wrt_DeltaRot_Nl11
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost1WrtDeltarotNl11(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot, const Scalar p_init0,
    const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x, const Scalar rot_init_y,
    const Scalar rot_init_z, const Scalar rot_init_w, const Scalar epsilon) {
  // Total ops: 3475

  // Unused inputs
  (void)p_init2;
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();

  // Intermediate terms (1022)
  const Scalar _tmp0 = _DeltaRot[2] * rot_init_y;
  const Scalar _tmp1 = _DeltaRot[1] * rot_init_z;
  const Scalar _tmp2 = _DeltaRot[0] * rot_init_w;
  const Scalar _tmp3 = _DeltaRot[3] * rot_init_x;
  const Scalar _tmp4 = _tmp0 - _tmp1 + _tmp2 + _tmp3;
  const Scalar _tmp5 = _DeltaRot[0] * rot_init_y;
  const Scalar _tmp6 = (Scalar(1) / Scalar(2)) * _tmp5;
  const Scalar _tmp7 = _DeltaRot[3] * rot_init_z;
  const Scalar _tmp8 = (Scalar(1) / Scalar(2)) * _tmp7;
  const Scalar _tmp9 = _DeltaRot[2] * rot_init_w;
  const Scalar _tmp10 = (Scalar(1) / Scalar(2)) * _tmp9;
  const Scalar _tmp11 = _DeltaRot[1] * rot_init_x;
  const Scalar _tmp12 = (Scalar(1) / Scalar(2)) * _tmp11;
  const Scalar _tmp13 = _tmp10 + _tmp12 - _tmp6 + _tmp8;
  const Scalar _tmp14 = Scalar(0.41999999999999998) * _tmp13;
  const Scalar _tmp15 = _tmp14 * _tmp4;
  const Scalar _tmp16 = _DeltaRot[1] * rot_init_y;
  const Scalar _tmp17 = _DeltaRot[2] * rot_init_z;
  const Scalar _tmp18 = _DeltaRot[3] * rot_init_w;
  const Scalar _tmp19 = _DeltaRot[0] * rot_init_x;
  const Scalar _tmp20 = -Scalar(1) / Scalar(2) * _tmp16 - Scalar(1) / Scalar(2) * _tmp17 +
                        (Scalar(1) / Scalar(2)) * _tmp18 - Scalar(1) / Scalar(2) * _tmp19;
  const Scalar _tmp21 = _DeltaRot[3] * rot_init_y;
  const Scalar _tmp22 = _DeltaRot[0] * rot_init_z;
  const Scalar _tmp23 = _DeltaRot[1] * rot_init_w;
  const Scalar _tmp24 = _DeltaRot[2] * rot_init_x;
  const Scalar _tmp25 = _tmp21 + _tmp22 + _tmp23 - _tmp24;
  const Scalar _tmp26 = Scalar(0.41999999999999998) * _tmp25;
  const Scalar _tmp27 = _tmp20 * _tmp26;
  const Scalar _tmp28 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp29 = (Scalar(1) / Scalar(2)) * _tmp1;
  const Scalar _tmp30 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp31 = (Scalar(1) / Scalar(2)) * _tmp3;
  const Scalar _tmp32 = -_tmp28 + _tmp29 - _tmp30 - _tmp31;
  const Scalar _tmp33 = _tmp11 - _tmp5 + _tmp7 + _tmp9;
  const Scalar _tmp34 = Scalar(0.41999999999999998) * _tmp33;
  const Scalar _tmp35 = _tmp32 * _tmp34;
  const Scalar _tmp36 = -_tmp35;
  const Scalar _tmp37 = (Scalar(1) / Scalar(2)) * _tmp21;
  const Scalar _tmp38 = (Scalar(1) / Scalar(2)) * _tmp22;
  const Scalar _tmp39 = (Scalar(1) / Scalar(2)) * _tmp23;
  const Scalar _tmp40 = (Scalar(1) / Scalar(2)) * _tmp24;
  const Scalar _tmp41 = -_tmp37 - _tmp38 - _tmp39 + _tmp40;
  const Scalar _tmp42 = -_tmp16 - _tmp17 + _tmp18 - _tmp19;
  const Scalar _tmp43 = Scalar(0.41999999999999998) * _tmp42;
  const Scalar _tmp44 = _tmp41 * _tmp43;
  const Scalar _tmp45 = -_tmp44;
  const Scalar _tmp46 = _tmp15 + _tmp27 + _tmp36 + _tmp45;
  const Scalar _tmp47 = Scalar(0.83999999999999997) * _tmp33;
  const Scalar _tmp48 = _tmp41 * _tmp47;
  const Scalar _tmp49 = Scalar(0.83999999999999997) * _tmp25;
  const Scalar _tmp50 = _tmp13 * _tmp49;
  const Scalar _tmp51 = _tmp48 + _tmp50;
  const Scalar _tmp52 = _tmp46 + _tmp51;
  const Scalar _tmp53 = Scalar(0.021999999999999999) * _tmp33;
  const Scalar _tmp54 = _tmp20 * _tmp53;
  const Scalar _tmp55 = Scalar(0.021999999999999999) * _tmp4;
  const Scalar _tmp56 = _tmp41 * _tmp55;
  const Scalar _tmp57 = Scalar(0.021999999999999999) * _tmp25;
  const Scalar _tmp58 = _tmp32 * _tmp57;
  const Scalar _tmp59 = Scalar(0.021999999999999999) * _tmp42;
  const Scalar _tmp60 = _tmp13 * _tmp59;
  const Scalar _tmp61 = _tmp54 + _tmp56 + _tmp58 + _tmp60;
  const Scalar _tmp62 = 2 * _tmp25;
  const Scalar _tmp63 = _tmp4 * _tmp62;
  const Scalar _tmp64 = 2 * _tmp42;
  const Scalar _tmp65 = _tmp33 * _tmp64;
  const Scalar _tmp66 = Scalar(0.20999999999999999) * _tmp63 - Scalar(0.20999999999999999) * _tmp65;
  const Scalar _tmp67 = -_tmp66;
  const Scalar _tmp68 = 2 * _tmp33 * _tmp4;
  const Scalar _tmp69 = _tmp25 * _tmp64;
  const Scalar _tmp70 = _tmp68 + _tmp69;
  const Scalar _tmp71 = -Scalar(0.010999999999999999) * _tmp70;
  const Scalar _tmp72 = -2 * std::pow(_tmp25, Scalar(2));
  const Scalar _tmp73 = 1 - 2 * std::pow(_tmp33, Scalar(2));
  const Scalar _tmp74 = Scalar(0.20999999999999999) * _tmp72 + Scalar(0.20999999999999999) * _tmp73;
  const Scalar _tmp75 = _tmp71 + _tmp74;
  const Scalar _tmp76 = _tmp67 + _tmp75;
  const Scalar _tmp77 = _tmp76 + p_init0;
  const Scalar _tmp78 = Scalar(2.5202214700000001) - _tmp77;
  const Scalar _tmp79 = 2 * _tmp78;
  const Scalar _tmp80 = -_tmp15;
  const Scalar _tmp81 = -_tmp27;
  const Scalar _tmp82 = _tmp36 + _tmp81;
  const Scalar _tmp83 = _tmp45 + _tmp80 + _tmp82;
  const Scalar _tmp84 = _tmp20 * _tmp42;
  const Scalar _tmp85 = Scalar(0.021999999999999999) * _tmp84;
  const Scalar _tmp86 = -_tmp85;
  const Scalar _tmp87 = _tmp41 * _tmp57;
  const Scalar _tmp88 = _tmp13 * _tmp53;
  const Scalar _tmp89 = _tmp32 * _tmp55;
  const Scalar _tmp90 = _tmp86 + _tmp87 + _tmp88 - _tmp89;
  const Scalar _tmp91 = -_tmp48;
  const Scalar _tmp92 = Scalar(0.83999999999999997) * _tmp20;
  const Scalar _tmp93 = _tmp4 * _tmp92;
  const Scalar _tmp94 = _tmp91 - _tmp93;
  const Scalar _tmp95 = _tmp90 + _tmp94;
  const Scalar _tmp96 = Scalar(0.20999999999999999) * _tmp63 + Scalar(0.20999999999999999) * _tmp65;
  const Scalar _tmp97 = _tmp33 * _tmp62;
  const Scalar _tmp98 = _tmp4 * _tmp64;
  const Scalar _tmp99 = _tmp97 - _tmp98;
  const Scalar _tmp100 = -Scalar(0.010999999999999999) * _tmp99;
  const Scalar _tmp101 = -2 * std::pow(_tmp4, Scalar(2));
  const Scalar _tmp102 =
      Scalar(0.20999999999999999) * _tmp101 + Scalar(0.20999999999999999) * _tmp73;
  const Scalar _tmp103 = _tmp100 - _tmp102;
  const Scalar _tmp104 = _tmp103 + _tmp96;
  const Scalar _tmp105 = _tmp104 + p_init1;
  const Scalar _tmp106 = -_tmp105 + Scalar(-8.3888750099999996);
  const Scalar _tmp107 = 2 * _tmp106;
  const Scalar _tmp108 =
      std::sqrt(Scalar(std::pow(_tmp106, Scalar(2)) + std::pow(_tmp78, Scalar(2))));
  const Scalar _tmp109 = Scalar(1.0) / (fh1);
  const Scalar _tmp110 =
      Scalar(0.5) *
      std::sinh(Scalar(0.1034955) * _tmp109 *
                (-_tmp108 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp109 * fv1))) /
      _tmp108;
  const Scalar _tmp111 = Scalar(0.043999999999999997) * _tmp25;
  const Scalar _tmp112 = _tmp111 * _tmp13;
  const Scalar _tmp113 = Scalar(0.043999999999999997) * _tmp4;
  const Scalar _tmp114 = _tmp113 * _tmp20;
  const Scalar _tmp115 = _tmp112 + _tmp114;
  const Scalar _tmp116 = _tmp14 * _tmp33;
  const Scalar _tmp117 = Scalar(0.41999999999999998) * _tmp4;
  const Scalar _tmp118 = _tmp117 * _tmp32;
  const Scalar _tmp119 = -_tmp118;
  const Scalar _tmp120 = -_tmp116 + _tmp119;
  const Scalar _tmp121 = _tmp115 + _tmp120;
  const Scalar _tmp122 = _tmp26 * _tmp41;
  const Scalar _tmp123 = Scalar(0.41999999999999998) * _tmp84;
  const Scalar _tmp124 = -_tmp123;
  const Scalar _tmp125 = -_tmp122 + _tmp124;
  const Scalar _tmp126 = _tmp117 * _tmp41;
  const Scalar _tmp127 = Scalar(0.41999999999999998) * _tmp20;
  const Scalar _tmp128 = _tmp127 * _tmp33;
  const Scalar _tmp129 = _tmp126 + _tmp128;
  const Scalar _tmp130 = _tmp125 + _tmp129;
  const Scalar _tmp131 = _tmp26 * _tmp32;
  const Scalar _tmp132 = _tmp14 * _tmp42;
  const Scalar _tmp133 = -_tmp131 - _tmp132;
  const Scalar _tmp134 = _tmp130 + _tmp133;
  const Scalar _tmp135 = _tmp121 + _tmp134;
  const Scalar _tmp136 = _tmp100 + _tmp102;
  const Scalar _tmp137 = _tmp136 + _tmp96;
  const Scalar _tmp138 = _tmp137 + p_init1;
  const Scalar _tmp139 = _tmp138 + Scalar(-4.7752063900000001);
  const Scalar _tmp140 = _tmp66 + _tmp75;
  const Scalar _tmp141 = _tmp140 + p_init0;
  const Scalar _tmp142 = _tmp141 + Scalar(-2.71799795);
  const Scalar _tmp143 = std::pow(_tmp139, Scalar(2)) + std::pow(_tmp142, Scalar(2));
  const Scalar _tmp144 = std::pow(_tmp143, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp145 = _tmp139 * _tmp144;
  const Scalar _tmp146 = -_tmp96;
  const Scalar _tmp147 = _tmp136 + _tmp146;
  const Scalar _tmp148 = _tmp147 + p_init1;
  const Scalar _tmp149 = _tmp148 + Scalar(-4.8333311099999996);
  const Scalar _tmp150 = _tmp71 - _tmp74;
  const Scalar _tmp151 = _tmp150 + _tmp66;
  const Scalar _tmp152 = _tmp151 + p_init0;
  const Scalar _tmp153 = _tmp152 + Scalar(1.79662371);
  const Scalar _tmp154 = Scalar(1.0) / (_tmp153);
  const Scalar _tmp155 = _tmp149 * _tmp154;
  const Scalar _tmp156 = _tmp142 * _tmp144;
  const Scalar _tmp157 = -_tmp145 + _tmp155 * _tmp156;
  const Scalar _tmp158 = Scalar(1.0) / (_tmp157);
  const Scalar _tmp159 = _tmp156 * _tmp158;
  const Scalar _tmp160 = Scalar(1.0) * _tmp151;
  const Scalar _tmp161 = Scalar(1.0) * _tmp147;
  const Scalar _tmp162 = -_tmp161;
  const Scalar _tmp163 = _tmp137 + _tmp162;
  const Scalar _tmp164 = Scalar(1.0) / (_tmp163);
  const Scalar _tmp165 = -_tmp140 + _tmp160;
  const Scalar _tmp166 = _tmp164 * _tmp165;
  const Scalar _tmp167 = _tmp160 + _tmp161 * _tmp166;
  const Scalar _tmp168 = 0;
  const Scalar _tmp169 = _tmp150 + _tmp67;
  const Scalar _tmp170 = _tmp169 + p_init0;
  const Scalar _tmp171 = _tmp170 + Scalar(1.9874742000000001);
  const Scalar _tmp172 = _tmp103 + _tmp146;
  const Scalar _tmp173 = _tmp172 + p_init1;
  const Scalar _tmp174 = _tmp173 + Scalar(8.3196563700000006);
  const Scalar _tmp175 = std::pow(_tmp171, Scalar(2)) + std::pow(_tmp174, Scalar(2));
  const Scalar _tmp176 = std::pow(_tmp175, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp177 =
      Scalar(0.20999999999999999) * _tmp97 + Scalar(0.20999999999999999) * _tmp98;
  const Scalar _tmp178 = -Scalar(0.010999999999999999) * _tmp101 -
                         Scalar(0.010999999999999999) * _tmp72 + Scalar(-0.010999999999999999);
  const Scalar _tmp179 =
      Scalar(0.20999999999999999) * _tmp68 - Scalar(0.20999999999999999) * _tmp69;
  const Scalar _tmp180 = _tmp178 - _tmp179;
  const Scalar _tmp181 = _tmp177 + _tmp180;
  const Scalar _tmp182 = _tmp176 * _tmp181;
  const Scalar _tmp183 = _tmp171 * _tmp182;
  const Scalar _tmp184 = -_tmp177;
  const Scalar _tmp185 = _tmp180 + _tmp184;
  const Scalar _tmp186 = _tmp171 * _tmp176;
  const Scalar _tmp187 = _tmp178 + _tmp179;
  const Scalar _tmp188 = _tmp177 + _tmp187;
  const Scalar _tmp189 = _tmp156 * _tmp181;
  const Scalar _tmp190 = -_tmp156 * _tmp188 + _tmp189;
  const Scalar _tmp191 = _tmp174 * _tmp176;
  const Scalar _tmp192 = _tmp155 * _tmp186 - _tmp191;
  const Scalar _tmp193 = _tmp158 * _tmp192;
  const Scalar _tmp194 = _tmp145 * _tmp188 - _tmp155 * _tmp189;
  const Scalar _tmp195 = -_tmp155 * _tmp183 + _tmp185 * _tmp191 - _tmp193 * _tmp194;
  const Scalar _tmp196 = -_tmp166 * _tmp195 + _tmp183 - _tmp185 * _tmp186 - _tmp190 * _tmp193;
  const Scalar _tmp197 = Scalar(1.0) / (_tmp196);
  const Scalar _tmp198 = _tmp192 * _tmp197;
  const Scalar _tmp199 = _tmp168 * _tmp198;
  const Scalar _tmp200 = _tmp168 * _tmp197;
  const Scalar _tmp201 = -_tmp159 * _tmp199 + _tmp186 * _tmp200;
  const Scalar _tmp202 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp203 = std::pow(_tmp153, Scalar(2));
  const Scalar _tmp204 = std::pow(_tmp149, Scalar(2)) + _tmp203;
  const Scalar _tmp205 = std::sqrt(_tmp204);
  const Scalar _tmp206 = _tmp154 * _tmp205;
  const Scalar _tmp207 = _tmp202 * _tmp206;
  const Scalar _tmp208 = _tmp77 + Scalar(-2.5202214700000001);
  const Scalar _tmp209 = _tmp105 + Scalar(8.3888750099999996);
  const Scalar _tmp210 = std::pow(_tmp208, Scalar(2)) + std::pow(_tmp209, Scalar(2));
  const Scalar _tmp211 = std::pow(_tmp210, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp212 = _tmp208 * _tmp211;
  const Scalar _tmp213 = _tmp212 * fh1;
  const Scalar _tmp214 = _tmp158 * _tmp190;
  const Scalar _tmp215 = _tmp155 * _tmp158;
  const Scalar _tmp216 = _tmp155 * _tmp181;
  const Scalar _tmp217 = _tmp194 * _tmp215 + _tmp216;
  const Scalar _tmp218 = _tmp155 * _tmp214 - _tmp166 * _tmp217 - _tmp181;
  const Scalar _tmp219 = Scalar(1.0) / (_tmp205);
  const Scalar _tmp220 = _tmp151 * _tmp219;
  const Scalar _tmp221 = _tmp147 * _tmp219;
  const Scalar _tmp222 = _tmp149 * _tmp220 - _tmp153 * _tmp221;
  const Scalar _tmp223 = _tmp206 * _tmp222;
  const Scalar _tmp224 = _tmp137 * _tmp156 - _tmp140 * _tmp145 + _tmp156 * _tmp223;
  const Scalar _tmp225 = _tmp172 * _tmp176;
  const Scalar _tmp226 =
      -_tmp169 * _tmp191 + _tmp171 * _tmp225 + _tmp186 * _tmp223 - _tmp193 * _tmp224;
  const Scalar _tmp227 = _tmp197 * _tmp226;
  const Scalar _tmp228 = _tmp215 * _tmp224 - _tmp218 * _tmp227 - _tmp223;
  const Scalar _tmp229 = Scalar(1.0) / (_tmp226);
  const Scalar _tmp230 = _tmp196 * _tmp229;
  const Scalar _tmp231 = _tmp228 * _tmp230;
  const Scalar _tmp232 = _tmp218 + _tmp231;
  const Scalar _tmp233 = _tmp197 * _tmp232;
  const Scalar _tmp234 = -_tmp155 - _tmp192 * _tmp233;
  const Scalar _tmp235 = _tmp159 * _tmp234 + _tmp186 * _tmp233 + Scalar(1.0);
  const Scalar _tmp236 = _tmp206 * _tmp235;
  const Scalar _tmp237 = _tmp209 * _tmp211;
  const Scalar _tmp238 = _tmp237 * fh1;
  const Scalar _tmp239 = Scalar(1.0) * _tmp158;
  const Scalar _tmp240 = _tmp158 * _tmp194;
  const Scalar _tmp241 = Scalar(1.0) * _tmp164;
  const Scalar _tmp242 = _tmp165 * _tmp241;
  const Scalar _tmp243 = -_tmp190 * _tmp239 + _tmp240 * _tmp242;
  const Scalar _tmp244 = _tmp197 * _tmp243;
  const Scalar _tmp245 = -_tmp224 * _tmp239 - _tmp226 * _tmp244;
  const Scalar _tmp246 = _tmp230 * _tmp245;
  const Scalar _tmp247 = _tmp243 + _tmp246;
  const Scalar _tmp248 = _tmp197 * _tmp247;
  const Scalar _tmp249 = -_tmp198 * _tmp247 + Scalar(1.0);
  const Scalar _tmp250 = _tmp159 * _tmp249 + _tmp186 * _tmp248;
  const Scalar _tmp251 = _tmp206 * _tmp250;
  const Scalar _tmp252 = fh1 * (-_tmp104 * _tmp212 + _tmp237 * _tmp76);
  const Scalar _tmp253 = Scalar(1.0) * _tmp229;
  const Scalar _tmp254 = _tmp193 * _tmp253;
  const Scalar _tmp255 = -_tmp156 * _tmp254 + _tmp186 * _tmp253;
  const Scalar _tmp256 = _tmp206 * _tmp255;
  const Scalar _tmp257 =
      -_tmp201 * _tmp207 - _tmp213 * _tmp236 - _tmp238 * _tmp251 - _tmp252 * _tmp256;
  const Scalar _tmp258 = std::pow(_tmp257, Scalar(-2));
  const Scalar _tmp259 = -_tmp87;
  const Scalar _tmp260 = _tmp259 + _tmp85 - _tmp88 + _tmp89;
  const Scalar _tmp261 = _tmp260 + _tmp94;
  const Scalar _tmp262 = _tmp261 + _tmp83;
  const Scalar _tmp263 = 2 * _tmp149;
  const Scalar _tmp264 = -_tmp56;
  const Scalar _tmp265 = -_tmp54;
  const Scalar _tmp266 = _tmp264 + _tmp265 - _tmp58 - _tmp60;
  const Scalar _tmp267 = _tmp266 + _tmp52;
  const Scalar _tmp268 = 2 * _tmp153;
  const Scalar _tmp269 = _tmp262 * _tmp263 + _tmp267 * _tmp268;
  const Scalar _tmp270 = (Scalar(1) / Scalar(2)) * _tmp154 * _tmp219;
  const Scalar _tmp271 = _tmp238 * _tmp250;
  const Scalar _tmp272 = _tmp270 * _tmp271;
  const Scalar _tmp273 = _tmp35 + _tmp44 + _tmp80 + _tmp81;
  const Scalar _tmp274 = -_tmp50 + _tmp91;
  const Scalar _tmp275 = _tmp266 + _tmp274;
  const Scalar _tmp276 = _tmp273 + _tmp275;
  const Scalar _tmp277 = 2 * _tmp208;
  const Scalar _tmp278 = _tmp27 + _tmp35;
  const Scalar _tmp279 = _tmp15 + _tmp278 + _tmp44;
  const Scalar _tmp280 = _tmp48 + _tmp93;
  const Scalar _tmp281 = _tmp260 + _tmp280;
  const Scalar _tmp282 = _tmp279 + _tmp281;
  const Scalar _tmp283 = 2 * _tmp209;
  const Scalar _tmp284 = _tmp276 * _tmp277 + _tmp282 * _tmp283;
  const Scalar _tmp285 = std::pow(_tmp210, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp286 = (Scalar(1) / Scalar(2)) * _tmp285;
  const Scalar _tmp287 = _tmp284 * _tmp286;
  const Scalar _tmp288 = _tmp208 * fh1;
  const Scalar _tmp289 = _tmp287 * _tmp288;
  const Scalar _tmp290 = _tmp201 * _tmp202;
  const Scalar _tmp291 = _tmp270 * _tmp290;
  const Scalar _tmp292 = _tmp281 + _tmp83;
  const Scalar _tmp293 = 2 * _tmp174;
  const Scalar _tmp294 = _tmp266 + _tmp273 + _tmp51;
  const Scalar _tmp295 = 2 * _tmp171;
  const Scalar _tmp296 = _tmp292 * _tmp293 + _tmp294 * _tmp295;
  const Scalar _tmp297 = std::pow(_tmp175, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp298 = (Scalar(1) / Scalar(2)) * _tmp297;
  const Scalar _tmp299 = _tmp174 * _tmp298;
  const Scalar _tmp300 = _tmp296 * _tmp299;
  const Scalar _tmp301 = Scalar(1.0) / (_tmp203);
  const Scalar _tmp302 = _tmp205 * _tmp301;
  const Scalar _tmp303 = _tmp222 * _tmp302;
  const Scalar _tmp304 = _tmp267 * _tmp303;
  const Scalar _tmp305 = _tmp176 * _tmp292;
  const Scalar _tmp306 = _tmp171 * _tmp298;
  const Scalar _tmp307 = _tmp296 * _tmp306;
  const Scalar _tmp308 = _tmp222 * _tmp270;
  const Scalar _tmp309 = _tmp269 * _tmp308;
  const Scalar _tmp310 = _tmp275 + _tmp46;
  const Scalar _tmp311 = 2 * _tmp142;
  const Scalar _tmp312 = _tmp261 + _tmp279;
  const Scalar _tmp313 = 2 * _tmp139;
  const Scalar _tmp314 = _tmp310 * _tmp311 + _tmp312 * _tmp313;
  const Scalar _tmp315 = std::pow(_tmp143, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp316 = (Scalar(1) / Scalar(2)) * _tmp315;
  const Scalar _tmp317 = _tmp142 * _tmp316;
  const Scalar _tmp318 = _tmp155 * _tmp317;
  const Scalar _tmp319 = _tmp144 * _tmp310;
  const Scalar _tmp320 = _tmp144 * _tmp312;
  const Scalar _tmp321 = _tmp139 * _tmp316;
  const Scalar _tmp322 = _tmp314 * _tmp321;
  const Scalar _tmp323 = _tmp149 * _tmp301;
  const Scalar _tmp324 = _tmp267 * _tmp323;
  const Scalar _tmp325 = _tmp154 * _tmp262;
  const Scalar _tmp326 = _tmp155 * _tmp319 - _tmp156 * _tmp324 + _tmp156 * _tmp325 -
                         _tmp314 * _tmp318 - _tmp320 + _tmp322;
  const Scalar _tmp327 = std::pow(_tmp157, Scalar(-2));
  const Scalar _tmp328 = _tmp192 * _tmp327;
  const Scalar _tmp329 = _tmp326 * _tmp328;
  const Scalar _tmp330 = _tmp149 * _tmp151;
  const Scalar _tmp331 = (Scalar(1) / Scalar(2)) / (_tmp204 * std::sqrt(_tmp204));
  const Scalar _tmp332 = _tmp269 * _tmp331;
  const Scalar _tmp333 = _tmp147 * _tmp153;
  const Scalar _tmp334 = _tmp149 * _tmp219;
  const Scalar _tmp335 = _tmp153 * _tmp219;
  const Scalar _tmp336 = _tmp206 * (_tmp220 * _tmp262 - _tmp221 * _tmp267 - _tmp262 * _tmp335 +
                                    _tmp267 * _tmp334 - _tmp330 * _tmp332 + _tmp332 * _tmp333);
  const Scalar _tmp337 = _tmp223 * _tmp317;
  const Scalar _tmp338 = _tmp137 * _tmp317;
  const Scalar _tmp339 = _tmp137 * _tmp319 - _tmp140 * _tmp320 + _tmp140 * _tmp322 +
                         _tmp142 * _tmp320 - _tmp145 * _tmp310 - _tmp156 * _tmp304 +
                         _tmp156 * _tmp309 + _tmp156 * _tmp336 + _tmp223 * _tmp319 -
                         _tmp314 * _tmp337 - _tmp314 * _tmp338;
  const Scalar _tmp340 = _tmp176 * _tmp294;
  const Scalar _tmp341 = -_tmp155 * _tmp307 + _tmp155 * _tmp340 - _tmp186 * _tmp324 +
                         _tmp186 * _tmp325 + _tmp300 - _tmp305;
  const Scalar _tmp342 = _tmp158 * _tmp341;
  const Scalar _tmp343 = _tmp169 * _tmp300 - _tmp169 * _tmp305 + _tmp171 * _tmp305 -
                         _tmp172 * _tmp307 - _tmp186 * _tmp304 + _tmp186 * _tmp309 +
                         _tmp186 * _tmp336 - _tmp191 * _tmp294 - _tmp193 * _tmp339 -
                         _tmp223 * _tmp307 + _tmp223 * _tmp340 + _tmp224 * _tmp329 -
                         _tmp224 * _tmp342 + _tmp225 * _tmp294;
  const Scalar _tmp344 = std::pow(_tmp226, Scalar(-2));
  const Scalar _tmp345 = Scalar(1.0) * _tmp344;
  const Scalar _tmp346 = _tmp343 * _tmp345;
  const Scalar _tmp347 = Scalar(0.5) * _tmp229;
  const Scalar _tmp348 = _tmp171 * _tmp297 * _tmp347;
  const Scalar _tmp349 = _tmp142 * _tmp193 * _tmp315 * _tmp347;
  const Scalar _tmp350 = _tmp156 * _tmp253;
  const Scalar _tmp351 = _tmp192 * _tmp239 * _tmp344;
  const Scalar _tmp352 = _tmp343 * _tmp351;
  const Scalar _tmp353 = _tmp206 * _tmp252;
  const Scalar _tmp354 = _tmp156 * _tmp200;
  const Scalar _tmp355 = _tmp131 + _tmp132;
  const Scalar _tmp356 = -_tmp126 - _tmp128;
  const Scalar _tmp357 = _tmp122 + _tmp356;
  const Scalar _tmp358 = _tmp118 + _tmp123;
  const Scalar _tmp359 = _tmp115 + _tmp116 + _tmp358;
  const Scalar _tmp360 = _tmp355 + _tmp357 + _tmp359;
  const Scalar _tmp361 = _tmp122 + _tmp129;
  const Scalar _tmp362 = _tmp133 + _tmp359 + _tmp361;
  const Scalar _tmp363 = _tmp188 * _tmp317;
  const Scalar _tmp364 = _tmp181 * _tmp317;
  const Scalar _tmp365 = _tmp156 * _tmp360 - _tmp156 * _tmp362 + _tmp181 * _tmp319 -
                         _tmp188 * _tmp319 + _tmp314 * _tmp363 - _tmp314 * _tmp364;
  const Scalar _tmp366 = _tmp190 * _tmp326;
  const Scalar _tmp367 = std::pow(_tmp163, Scalar(-2));
  const Scalar _tmp368 = _tmp32 * _tmp47;
  const Scalar _tmp369 = Scalar(0.83999999999999997) * _tmp42;
  const Scalar _tmp370 = _tmp369 * _tmp41;
  const Scalar _tmp371 = Scalar(0.83999999999999997) * _tmp4;
  const Scalar _tmp372 = _tmp25 * _tmp92;
  const Scalar _tmp373 = _tmp13 * _tmp371 + _tmp372;
  const Scalar _tmp374 = _tmp367 * (_tmp368 + _tmp370 + _tmp373);
  const Scalar _tmp375 = _tmp165 * _tmp195;
  const Scalar _tmp376 = _tmp176 * _tmp185;
  const Scalar _tmp377 = _tmp125 + _tmp356;
  const Scalar _tmp378 = _tmp121 + _tmp355 + _tmp377;
  const Scalar _tmp379 = _tmp216 * _tmp317;
  const Scalar _tmp380 = _tmp155 * _tmp360;
  const Scalar _tmp381 = _tmp145 * _tmp362 - _tmp156 * _tmp380 + _tmp188 * _tmp320 -
                         _tmp188 * _tmp322 + _tmp189 * _tmp324 - _tmp189 * _tmp325 -
                         _tmp216 * _tmp319 + _tmp314 * _tmp379;
  const Scalar _tmp382 = _tmp182 * _tmp294;
  const Scalar _tmp383 = _tmp181 * _tmp325;
  const Scalar _tmp384 = -_tmp155 * _tmp382 + _tmp183 * _tmp324 - _tmp185 * _tmp300 +
                         _tmp185 * _tmp305 - _tmp186 * _tmp380 - _tmp186 * _tmp383 +
                         _tmp191 * _tmp378 - _tmp193 * _tmp381 + _tmp194 * _tmp329 -
                         _tmp194 * _tmp342 + _tmp216 * _tmp307;
  const Scalar _tmp385 = Scalar(1.6799999999999999) * _tmp33;
  const Scalar _tmp386 = _tmp385 * _tmp41;
  const Scalar _tmp387 = Scalar(1.6799999999999999) * _tmp25;
  const Scalar _tmp388 = _tmp13 * _tmp387 + _tmp386;
  const Scalar _tmp389 = _tmp164 * _tmp388;
  const Scalar _tmp390 = -_tmp166 * _tmp384 - _tmp181 * _tmp307 + _tmp185 * _tmp307 +
                         _tmp186 * _tmp360 - _tmp186 * _tmp378 - _tmp190 * _tmp342 -
                         _tmp193 * _tmp365 - _tmp195 * _tmp389 - _tmp294 * _tmp376 +
                         _tmp328 * _tmp366 + _tmp374 * _tmp375 + _tmp382;
  const Scalar _tmp391 = std::pow(_tmp196, Scalar(-2));
  const Scalar _tmp392 = _tmp168 * _tmp391;
  const Scalar _tmp393 = _tmp390 * _tmp392;
  const Scalar _tmp394 = _tmp156 * _tmp193;
  const Scalar _tmp395 = _tmp158 * _tmp168;
  const Scalar _tmp396 = _tmp198 * _tmp395;
  const Scalar _tmp397 = _tmp317 * _tmp396;
  const Scalar _tmp398 = _tmp156 * _tmp327;
  const Scalar _tmp399 = _tmp199 * _tmp398;
  const Scalar _tmp400 = _tmp104 * _tmp208;
  const Scalar _tmp401 = _tmp211 * _tmp76;
  const Scalar _tmp402 = _tmp209 * _tmp76;
  const Scalar _tmp403 = _tmp104 * _tmp211;
  const Scalar _tmp404 = fh1 * (-_tmp212 * _tmp282 + _tmp237 * _tmp276 - _tmp276 * _tmp403 +
                                _tmp282 * _tmp401 + _tmp287 * _tmp400 - _tmp287 * _tmp402);
  const Scalar _tmp405 = _tmp249 * _tmp398;
  const Scalar _tmp406 = _tmp158 * _tmp249;
  const Scalar _tmp407 = _tmp317 * _tmp406;
  const Scalar _tmp408 = _tmp247 * _tmp391;
  const Scalar _tmp409 = _tmp390 * _tmp408;
  const Scalar _tmp410 = _tmp196 * _tmp344;
  const Scalar _tmp411 = _tmp245 * _tmp410;
  const Scalar _tmp412 = _tmp343 * _tmp411;
  const Scalar _tmp413 = _tmp240 * _tmp241;
  const Scalar _tmp414 = _tmp194 * _tmp239;
  const Scalar _tmp415 = _tmp165 * _tmp414;
  const Scalar _tmp416 = Scalar(1.0) * _tmp327;
  const Scalar _tmp417 = _tmp158 * _tmp242;
  const Scalar _tmp418 = _tmp326 * _tmp327;
  const Scalar _tmp419 = _tmp194 * _tmp242;
  const Scalar _tmp420 = -_tmp239 * _tmp365 + _tmp366 * _tmp416 - _tmp374 * _tmp415 +
                         _tmp381 * _tmp417 + _tmp388 * _tmp413 - _tmp418 * _tmp419;
  const Scalar _tmp421 = _tmp224 * _tmp416;
  const Scalar _tmp422 = _tmp226 * _tmp391;
  const Scalar _tmp423 = _tmp243 * _tmp422;
  const Scalar _tmp424 = _tmp230 * (-_tmp227 * _tmp420 - _tmp239 * _tmp339 - _tmp244 * _tmp343 +
                                    _tmp326 * _tmp421 + _tmp390 * _tmp423);
  const Scalar _tmp425 = _tmp229 * _tmp390;
  const Scalar _tmp426 = _tmp245 * _tmp425;
  const Scalar _tmp427 = -_tmp412 + _tmp420 + _tmp424 + _tmp426;
  const Scalar _tmp428 = _tmp192 * _tmp409 - _tmp198 * _tmp427 - _tmp248 * _tmp341;
  const Scalar _tmp429 = _tmp186 * _tmp197;
  const Scalar _tmp430 = _tmp206 * _tmp238;
  const Scalar _tmp431 = _tmp209 * fh1;
  const Scalar _tmp432 = _tmp287 * _tmp431;
  const Scalar _tmp433 = _tmp267 * _tmp302;
  const Scalar _tmp434 = _tmp213 * _tmp235;
  const Scalar _tmp435 = _tmp211 * fh1;
  const Scalar _tmp436 = _tmp276 * _tmp435;
  const Scalar _tmp437 = _tmp270 * _tmp434;
  const Scalar _tmp438 = _tmp232 * _tmp391;
  const Scalar _tmp439 = _tmp390 * _tmp438;
  const Scalar _tmp440 = _tmp158 * _tmp234;
  const Scalar _tmp441 = _tmp317 * _tmp440;
  const Scalar _tmp442 = _tmp228 * _tmp425;
  const Scalar _tmp443 = _tmp228 * _tmp410;
  const Scalar _tmp444 = _tmp343 * _tmp443;
  const Scalar _tmp445 = _tmp155 * _tmp327;
  const Scalar _tmp446 = _tmp165 * _tmp217;
  const Scalar _tmp447 = _tmp194 * _tmp445;
  const Scalar _tmp448 = -_tmp181 * _tmp324 + _tmp215 * _tmp381 - _tmp240 * _tmp324 +
                         _tmp240 * _tmp325 - _tmp326 * _tmp447 + _tmp380 + _tmp383;
  const Scalar _tmp449 = -_tmp112 - _tmp114 + _tmp120 + _tmp134 - _tmp166 * _tmp448 -
                         _tmp214 * _tmp324 + _tmp214 * _tmp325 + _tmp215 * _tmp365 -
                         _tmp217 * _tmp389 - _tmp366 * _tmp445 + _tmp374 * _tmp446;
  const Scalar _tmp450 = _tmp197 * _tmp218;
  const Scalar _tmp451 = _tmp158 * _tmp224;
  const Scalar _tmp452 = _tmp218 * _tmp422;
  const Scalar _tmp453 = _tmp224 * _tmp445;
  const Scalar _tmp454 = _tmp230 * (_tmp215 * _tmp339 - _tmp227 * _tmp449 + _tmp304 - _tmp309 -
                                    _tmp324 * _tmp451 + _tmp325 * _tmp451 - _tmp326 * _tmp453 -
                                    _tmp336 - _tmp343 * _tmp450 + _tmp390 * _tmp452);
  const Scalar _tmp455 = _tmp442 - _tmp444 + _tmp449 + _tmp454;
  const Scalar _tmp456 =
      _tmp192 * _tmp439 - _tmp198 * _tmp455 - _tmp233 * _tmp341 + _tmp324 - _tmp325;
  const Scalar _tmp457 = _tmp234 * _tmp398;
  const Scalar _tmp458 = _tmp206 * _tmp213;
  const Scalar _tmp459 = _tmp252 * _tmp255;
  const Scalar _tmp460 = _tmp282 * _tmp435;
  const Scalar _tmp461 = _tmp290 * _tmp302;
  const Scalar _tmp462 = _tmp270 * _tmp459;
  const Scalar _tmp463 =
      -_tmp207 * (-_tmp186 * _tmp393 - _tmp200 * _tmp307 + _tmp200 * _tmp340 + _tmp314 * _tmp397 -
                  _tmp319 * _tmp396 + _tmp326 * _tmp399 - _tmp342 * _tmp354 + _tmp393 * _tmp394) +
      _tmp236 * _tmp289 - _tmp236 * _tmp436 + _tmp251 * _tmp432 - _tmp251 * _tmp460 -
      _tmp256 * _tmp404 + _tmp267 * _tmp461 - _tmp269 * _tmp272 - _tmp269 * _tmp291 -
      _tmp269 * _tmp437 - _tmp269 * _tmp462 + _tmp271 * _tmp433 -
      _tmp353 * (_tmp156 * _tmp352 - _tmp186 * _tmp346 + _tmp253 * _tmp340 - _tmp254 * _tmp319 -
                 _tmp296 * _tmp348 + _tmp314 * _tmp349 + _tmp329 * _tmp350 - _tmp342 * _tmp350) -
      _tmp430 * (_tmp159 * _tmp428 - _tmp186 * _tmp409 - _tmp248 * _tmp307 + _tmp248 * _tmp340 -
                 _tmp314 * _tmp407 + _tmp319 * _tmp406 - _tmp326 * _tmp405 + _tmp427 * _tmp429) +
      _tmp433 * _tmp434 + _tmp433 * _tmp459 -
      _tmp458 * (_tmp159 * _tmp456 - _tmp186 * _tmp439 - _tmp233 * _tmp307 + _tmp233 * _tmp340 -
                 _tmp314 * _tmp441 + _tmp319 * _tmp440 - _tmp326 * _tmp457 + _tmp429 * _tmp455);
  const Scalar _tmp464 = _tmp258 * _tmp463;
  const Scalar _tmp465 = Scalar(6.59232) * _tmp41;
  const Scalar _tmp466 = _tmp4 * _tmp465;
  const Scalar _tmp467 = Scalar(6.59232) * _tmp20;
  const Scalar _tmp468 = _tmp33 * _tmp467;
  const Scalar _tmp469 = Scalar(6.59232) * _tmp32;
  const Scalar _tmp470 = _tmp184 + _tmp187;
  const Scalar _tmp471 = _tmp470 * fh1;
  const Scalar _tmp472 = _tmp211 * _tmp471;
  const Scalar _tmp473 = Scalar(6.59232) * _tmp42;
  const Scalar _tmp474 = _tmp208 * _tmp471;
  const Scalar _tmp475 = _tmp13 * _tmp473 + _tmp135 * _tmp213 + _tmp25 * _tmp469 +
                         _tmp276 * _tmp472 + _tmp276 * fv1 - _tmp287 * _tmp474 + _tmp466 + _tmp468;
  const Scalar _tmp476 = _tmp162 + _tmp172;
  const Scalar _tmp477 = _tmp166 * _tmp476;
  const Scalar _tmp478 = _tmp160 - _tmp169 - _tmp477;
  const Scalar _tmp479 = Scalar(1.0) / (_tmp478);
  const Scalar _tmp480 = Scalar(1.0) * _tmp479;
  const Scalar _tmp481 = _tmp164 * _tmp480;
  const Scalar _tmp482 = Scalar(1.0) * _tmp476 * _tmp481 - Scalar(1.0) * _tmp480;
  const Scalar _tmp483 = _tmp161 * _tmp165;
  const Scalar _tmp484 = _tmp161 * _tmp389 + _tmp242 * _tmp262 + _tmp267 - _tmp374 * _tmp483;
  const Scalar _tmp485 = Scalar(1.6799999999999999) * _tmp4;
  const Scalar _tmp486 = _tmp20 * _tmp485 + _tmp386;
  const Scalar _tmp487 = _tmp167 * _tmp479;
  const Scalar _tmp488 = _tmp389 * _tmp476;
  const Scalar _tmp489 = _tmp165 * _tmp476;
  const Scalar _tmp490 = _tmp374 * _tmp489;
  const Scalar _tmp491 = _tmp166 * _tmp486;
  const Scalar _tmp492 = -_tmp368 - _tmp370 + _tmp373 - _tmp488 + _tmp490 - _tmp491;
  const Scalar _tmp493 = std::pow(_tmp478, Scalar(-2));
  const Scalar _tmp494 = _tmp167 * _tmp493;
  const Scalar _tmp495 = _tmp476 * _tmp494;
  const Scalar _tmp496 = _tmp476 * _tmp479;
  const Scalar _tmp497 = _tmp280 + _tmp90;
  const Scalar _tmp498 = _tmp279 + _tmp497;
  const Scalar _tmp499 = _tmp195 * _tmp393 - _tmp200 * _tmp384 - _tmp484 * _tmp496 -
                         _tmp486 * _tmp487 + _tmp492 * _tmp495 + _tmp498;
  const Scalar _tmp500 = _tmp195 * _tmp197;
  const Scalar _tmp501 = _tmp162 - _tmp167 * _tmp496 - _tmp168 * _tmp500;
  const Scalar _tmp502 = Scalar(1.0) * _tmp374;
  const Scalar _tmp503 = Scalar(1.0) * _tmp493;
  const Scalar _tmp504 = _tmp492 * _tmp503;
  const Scalar _tmp505 = Scalar(1.0) * _tmp202;
  const Scalar _tmp506 = _tmp25 * _tmp465;
  const Scalar _tmp507 = Scalar(6.59232) * _tmp33;
  const Scalar _tmp508 = _tmp209 * _tmp471;
  const Scalar _tmp509 = Scalar(6.59232) * _tmp84;
  const Scalar _tmp510 = -_tmp13 * _tmp507 - _tmp135 * _tmp238 - _tmp282 * _tmp472 - _tmp282 * fv1 +
                         _tmp287 * _tmp508 + _tmp4 * _tmp469 - _tmp506 + _tmp509;
  const Scalar _tmp511 = _tmp166 * _tmp480;
  const Scalar _tmp512 = _tmp477 * _tmp480 + Scalar(1.0);
  const Scalar _tmp513 = -Scalar(1.0) * _tmp241 * _tmp512 + Scalar(1.0) * _tmp511;
  const Scalar _tmp514 = Scalar(0.5) * _tmp285;
  const Scalar _tmp515 = _tmp217 + _tmp231 * _tmp496 - _tmp232 * _tmp500;
  const Scalar _tmp516 = _tmp231 * _tmp480 - _tmp241 * _tmp515;
  const Scalar _tmp517 = _tmp288 * _tmp516;
  const Scalar _tmp518 = _tmp514 * _tmp517;
  const Scalar _tmp519 = Scalar(1.0) * _tmp516;
  const Scalar _tmp520 = _tmp230 * _tmp480;
  const Scalar _tmp521 = -_tmp195 * _tmp253 + _tmp476 * _tmp520;
  const Scalar _tmp522 = -Scalar(1.0) * _tmp241 * _tmp521 + Scalar(1.0) * _tmp520;
  const Scalar _tmp523 = _tmp246 * _tmp496 - _tmp247 * _tmp500 - _tmp414;
  const Scalar _tmp524 = -_tmp241 * _tmp523 + _tmp246 * _tmp480;
  const Scalar _tmp525 = _tmp431 * _tmp524;
  const Scalar _tmp526 = _tmp514 * _tmp525;
  const Scalar _tmp527 = _tmp479 * _tmp486;
  const Scalar _tmp528 = _tmp476 * _tmp493;
  const Scalar _tmp529 = _tmp231 * _tmp528;
  const Scalar _tmp530 = _tmp195 * _tmp439 + _tmp231 * _tmp527 - _tmp233 * _tmp384 +
                         _tmp442 * _tmp496 - _tmp444 * _tmp496 + _tmp448 + _tmp454 * _tmp496 -
                         _tmp455 * _tmp500 - _tmp492 * _tmp529;
  const Scalar _tmp531 = Scalar(1.0) * _tmp213;
  const Scalar _tmp532 = _tmp194 * _tmp416;
  const Scalar _tmp533 = _tmp246 * _tmp528;
  const Scalar _tmp534 = _tmp195 * _tmp409 - _tmp239 * _tmp381 + _tmp246 * _tmp527 -
                         _tmp248 * _tmp384 + _tmp326 * _tmp532 - _tmp412 * _tmp496 +
                         _tmp424 * _tmp496 + _tmp426 * _tmp496 - _tmp427 * _tmp500 -
                         _tmp492 * _tmp533;
  const Scalar _tmp535 = Scalar(1.0) * _tmp238;
  const Scalar _tmp536 = Scalar(1.0) * _tmp524;
  const Scalar _tmp537 = _tmp241 * _tmp528;
  const Scalar _tmp538 = _tmp492 * _tmp537;
  const Scalar _tmp539 = _tmp476 * _tmp480;
  const Scalar _tmp540 = _tmp213 * _tmp470 + Scalar(3.29616) * _tmp70 + _tmp76 * fv1;
  const Scalar _tmp541 = Scalar(1.0) * _tmp540;
  const Scalar _tmp542 = _tmp242 * _tmp493;
  const Scalar _tmp543 = _tmp492 * _tmp542;
  const Scalar _tmp544 =
      -_tmp476 * _tmp543 + _tmp480 * _tmp488 - _tmp480 * _tmp490 + _tmp480 * _tmp491;
  const Scalar _tmp545 = _tmp165 * _tmp480;
  const Scalar _tmp546 = _tmp374 * _tmp545;
  const Scalar _tmp547 = _tmp374 * _tmp512;
  const Scalar _tmp548 = -_tmp104 * fv1 - _tmp237 * _tmp471 - Scalar(3.29616) * _tmp99;
  const Scalar _tmp549 = Scalar(1.0) * _tmp548;
  const Scalar _tmp550 = _tmp425 * _tmp480;
  const Scalar _tmp551 = _tmp230 * _tmp504;
  const Scalar _tmp552 = _tmp410 * _tmp480;
  const Scalar _tmp553 = _tmp343 * _tmp552;
  const Scalar _tmp554 = _tmp195 * _tmp345;
  const Scalar _tmp555 = _tmp410 * _tmp539;
  const Scalar _tmp556 = -_tmp253 * _tmp384 + _tmp343 * _tmp554 - _tmp343 * _tmp555 +
                         _tmp476 * _tmp550 - _tmp476 * _tmp551 + _tmp486 * _tmp520;
  const Scalar _tmp557 = Scalar(1.0) * _tmp252;
  const Scalar _tmp558 = Scalar(1.0) / (_tmp257);
  const Scalar _tmp559 =
      _tmp213 * _tmp519 + _tmp238 * _tmp536 + _tmp252 * _tmp522 + _tmp482 * _tmp540 +
      _tmp505 * (-_tmp167 * _tmp480 - _tmp241 * _tmp501 + Scalar(1.0)) + _tmp513 * _tmp548;
  const Scalar _tmp560 =
      std::pow(Scalar(_tmp258 * std::pow(_tmp559, Scalar(2)) + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp561 =
      _tmp560 *
      (-_tmp464 * _tmp559 +
       _tmp558 *
           (-_tmp284 * _tmp518 - _tmp284 * _tmp526 + _tmp404 * _tmp522 + _tmp436 * _tmp519 +
            _tmp460 * _tmp536 + _tmp475 * _tmp482 +
            _tmp505 *
                (_tmp167 * _tmp504 - _tmp241 * _tmp499 - _tmp480 * _tmp484 + _tmp501 * _tmp502) +
            _tmp510 * _tmp513 +
            _tmp531 * (-_tmp231 * _tmp504 - _tmp241 * _tmp530 + _tmp442 * _tmp480 -
                       _tmp444 * _tmp480 + _tmp454 * _tmp480 + _tmp502 * _tmp515) +
            _tmp535 * (-_tmp241 * _tmp534 - _tmp246 * _tmp504 - _tmp412 * _tmp480 +
                       _tmp424 * _tmp480 + _tmp426 * _tmp480 + _tmp502 * _tmp523) +
            _tmp541 * (-_tmp374 * _tmp539 + _tmp481 * _tmp486 + _tmp504 - _tmp538) +
            _tmp549 * (-_tmp241 * _tmp544 + _tmp389 * _tmp480 - _tmp543 - _tmp546 +
                       Scalar(1.0) * _tmp547) +
            _tmp557 * (-_tmp241 * _tmp556 + _tmp502 * _tmp521 + _tmp550 - _tmp551 - _tmp553)));
  const Scalar _tmp562 = std::asinh(_tmp558 * _tmp559);
  const Scalar _tmp563 = Scalar(1.0) * _tmp562;
  const Scalar _tmp564 = Scalar(1.0) * std::sinh(_tmp563);
  const Scalar _tmp565 = -_tmp152 + Scalar(-1.79662371);
  const Scalar _tmp566 = Scalar(4.8333311099999996) - _tmp148;
  const Scalar _tmp567 =
      std::sqrt(Scalar(std::pow(_tmp565, Scalar(2)) + std::pow(_tmp566, Scalar(2))));
  const Scalar _tmp568 = Scalar(9.6622558468725703) * _tmp257;
  const Scalar _tmp569 = -_tmp562 * _tmp568 - _tmp567;
  const Scalar _tmp570 = Scalar(0.1034955) * _tmp558;
  const Scalar _tmp571 = _tmp569 * _tmp570;
  const Scalar _tmp572 = std::sinh(_tmp571);
  const Scalar _tmp573 = _tmp273 + _tmp61;
  const Scalar _tmp574 = 2 * _tmp565;
  const Scalar _tmp575 = 2 * _tmp566;
  const Scalar _tmp576 = (Scalar(1) / Scalar(2)) / _tmp567;
  const Scalar _tmp577 = Scalar(9.6622558468725703) * _tmp562;
  const Scalar _tmp578 = Scalar(0.1034955) * _tmp569;
  const Scalar _tmp579 = Scalar(8.3700199099999999) * _tmp558 +
                         Scalar(9.6622558468725703) * std::cosh(_tmp563) -
                         Scalar(9.6622558468725703) * std::cosh(_tmp571);
  const Scalar _tmp580 = Scalar(2.71799795) - _tmp141;
  const Scalar _tmp581 = 2 * _tmp580;
  const Scalar _tmp582 = Scalar(4.7752063900000001) - _tmp138;
  const Scalar _tmp583 = 2 * _tmp582;
  const Scalar _tmp584 =
      std::sqrt(Scalar(std::pow(_tmp580, Scalar(2)) + std::pow(_tmp582, Scalar(2))));
  const Scalar _tmp585 = (Scalar(1) / Scalar(2)) / _tmp584;
  const Scalar _tmp586 = _tmp252 * _tmp253;
  const Scalar _tmp587 = _tmp202 * _tmp395;
  const Scalar _tmp588 =
      -_tmp193 * _tmp586 - _tmp198 * _tmp587 + _tmp213 * _tmp440 + _tmp238 * _tmp406;
  const Scalar _tmp589 = Scalar(1.0) / (_tmp588);
  const Scalar _tmp590 = _tmp480 * _tmp540;
  const Scalar _tmp591 = _tmp164 * _tmp476;
  const Scalar _tmp592 = _tmp164 * _tmp548;
  const Scalar _tmp593 = _tmp164 * _tmp252;
  const Scalar _tmp594 = _tmp164 * _tmp202;
  const Scalar _tmp595 = _tmp164 * _tmp515;
  const Scalar _tmp596 = _tmp164 * _tmp523;
  const Scalar _tmp597 = _tmp213 * _tmp595 + _tmp238 * _tmp596 + _tmp501 * _tmp594 +
                         _tmp512 * _tmp592 + _tmp521 * _tmp593 - _tmp590 * _tmp591;
  const Scalar _tmp598 = std::asinh(_tmp589 * _tmp597);
  const Scalar _tmp599 = _tmp213 * _tmp234;
  const Scalar _tmp600 = _tmp253 * _tmp404;
  const Scalar _tmp601 = _tmp200 * _tmp202;
  const Scalar _tmp602 = _tmp158 * _tmp213;
  const Scalar _tmp603 = _tmp202 * _tmp392;
  const Scalar _tmp604 = _tmp390 * _tmp603;
  const Scalar _tmp605 = _tmp238 * _tmp249;
  const Scalar _tmp606 = _tmp158 * _tmp238;
  const Scalar _tmp607 = _tmp199 * _tmp202;
  const Scalar _tmp608 = -_tmp193 * _tmp600 + _tmp193 * _tmp604 + _tmp252 * _tmp352 -
                         _tmp289 * _tmp440 + _tmp329 * _tmp586 - _tmp342 * _tmp586 -
                         _tmp342 * _tmp601 - _tmp406 * _tmp432 + _tmp406 * _tmp460 -
                         _tmp418 * _tmp599 - _tmp418 * _tmp605 + _tmp418 * _tmp607 +
                         _tmp428 * _tmp606 + _tmp436 * _tmp440 + _tmp456 * _tmp602;
  const Scalar _tmp609 = Scalar(9.6622558468725703) * _tmp608;
  const Scalar _tmp610 = Scalar(9.6622558468725703) * _tmp588;
  const Scalar _tmp611 = std::pow(_tmp588, Scalar(-2));
  const Scalar _tmp612 =
      std::pow(Scalar(std::pow(_tmp597, Scalar(2)) * _tmp611 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp613 = _tmp476 * _tmp590;
  const Scalar _tmp614 = _tmp202 * _tmp501;
  const Scalar _tmp615 = _tmp213 * _tmp515;
  const Scalar _tmp616 = _tmp164 * _tmp512;
  const Scalar _tmp617 = _tmp238 * _tmp523;
  const Scalar _tmp618 = _tmp252 * _tmp521;
  const Scalar _tmp619 = _tmp164 * _tmp238;
  const Scalar _tmp620 = _tmp164 * _tmp590;
  const Scalar _tmp621 = _tmp475 * _tmp480;
  const Scalar _tmp622 = _tmp164 * _tmp521;
  const Scalar _tmp623 = _tmp288 * _tmp595;
  const Scalar _tmp624 = _tmp164 * _tmp213;
  const Scalar _tmp625 = _tmp608 * _tmp611;
  const Scalar _tmp626 =
      _tmp612 *
      (_tmp589 * (-_tmp287 * _tmp623 + _tmp374 * _tmp613 - _tmp374 * _tmp614 - _tmp374 * _tmp615 -
                  _tmp374 * _tmp617 - _tmp374 * _tmp618 + _tmp404 * _tmp622 - _tmp432 * _tmp596 +
                  _tmp436 * _tmp595 + _tmp460 * _tmp596 - _tmp486 * _tmp620 + _tmp499 * _tmp594 +
                  _tmp510 * _tmp616 + _tmp530 * _tmp624 + _tmp534 * _tmp619 + _tmp538 * _tmp540 +
                  _tmp544 * _tmp592 - _tmp547 * _tmp548 + _tmp556 * _tmp593 - _tmp591 * _tmp621) -
       _tmp597 * _tmp625);
  const Scalar _tmp627 = Scalar(0.1034955) * _tmp589;
  const Scalar _tmp628 = Scalar(9.6622558468725703) * _tmp598;
  const Scalar _tmp629 = -_tmp584 - _tmp588 * _tmp628;
  const Scalar _tmp630 = Scalar(0.1034955) * _tmp629;
  const Scalar _tmp631 = _tmp627 * _tmp629;
  const Scalar _tmp632 = std::sinh(_tmp631);
  const Scalar _tmp633 = Scalar(1.0) * _tmp598;
  const Scalar _tmp634 = Scalar(1.0) * std::sinh(_tmp633);
  const Scalar _tmp635 =
      Scalar(0.86565325453551001) * _tmp589 - std::cosh(_tmp631) + std::cosh(_tmp633);
  const Scalar _tmp636 = _tmp197 * _tmp238;
  const Scalar _tmp637 = _tmp197 * _tmp213;
  const Scalar _tmp638 = -_tmp213 * _tmp439 - _tmp233 * _tmp289 + _tmp233 * _tmp436 -
                         _tmp238 * _tmp409 - _tmp248 * _tmp432 + _tmp248 * _tmp460 -
                         _tmp252 * _tmp346 + _tmp427 * _tmp636 + _tmp455 * _tmp637 + _tmp600 -
                         _tmp604;
  const Scalar _tmp639 = _tmp213 * _tmp233 + _tmp238 * _tmp248 + _tmp586 + _tmp601;
  const Scalar _tmp640 = Scalar(1.0) / (_tmp639);
  const Scalar _tmp641 = _tmp231 * _tmp479;
  const Scalar _tmp642 = _tmp238 * _tmp479;
  const Scalar _tmp643 = _tmp202 * _tmp479;
  const Scalar _tmp644 = _tmp167 * _tmp643 - _tmp213 * _tmp641 - _tmp246 * _tmp642 -
                         _tmp252 * _tmp520 - _tmp545 * _tmp592 + _tmp590;
  const Scalar _tmp645 = std::asinh(_tmp640 * _tmp644);
  const Scalar _tmp646 = Scalar(9.6622558468725703) * _tmp645;
  const Scalar _tmp647 = -_tmp170 + Scalar(-1.9874742000000001);
  const Scalar _tmp648 = -_tmp173 + Scalar(-8.3196563700000006);
  const Scalar _tmp649 =
      std::sqrt(Scalar(std::pow(_tmp647, Scalar(2)) + std::pow(_tmp648, Scalar(2))));
  const Scalar _tmp650 = -_tmp639 * _tmp646 - _tmp649;
  const Scalar _tmp651 = Scalar(0.1034955) * _tmp640;
  const Scalar _tmp652 = _tmp650 * _tmp651;
  const Scalar _tmp653 = Scalar(1.0) * _tmp645;
  const Scalar _tmp654 = Scalar(8.4718465800000011) * _tmp640 -
                         Scalar(9.6622558468725703) * std::cosh(_tmp652) +
                         Scalar(9.6622558468725703) * std::cosh(_tmp653);
  const Scalar _tmp655 = _tmp213 * _tmp479;
  const Scalar _tmp656 = _tmp202 * _tmp494;
  const Scalar _tmp657 = _tmp246 * _tmp479;
  const Scalar _tmp658 = _tmp213 * _tmp231;
  const Scalar _tmp659 = _tmp492 * _tmp493;
  const Scalar _tmp660 = _tmp238 * _tmp246;
  const Scalar _tmp661 = _tmp480 * _tmp592;
  const Scalar _tmp662 = std::pow(_tmp639, Scalar(-2));
  const Scalar _tmp663 = _tmp644 * _tmp662;
  const Scalar _tmp664 =
      -_tmp638 * _tmp663 +
      _tmp640 * (-_tmp252 * _tmp550 + _tmp252 * _tmp551 + _tmp252 * _tmp553 + _tmp289 * _tmp641 -
                 _tmp388 * _tmp661 - _tmp404 * _tmp520 + _tmp412 * _tmp642 - _tmp424 * _tmp642 -
                 _tmp426 * _tmp642 + _tmp432 * _tmp657 - _tmp436 * _tmp641 - _tmp442 * _tmp655 +
                 _tmp444 * _tmp655 - _tmp454 * _tmp655 - _tmp460 * _tmp657 + _tmp484 * _tmp643 -
                 _tmp492 * _tmp656 - _tmp504 * _tmp540 - _tmp510 * _tmp511 + _tmp543 * _tmp548 +
                 _tmp546 * _tmp548 + _tmp621 + _tmp658 * _tmp659 + _tmp659 * _tmp660);
  const Scalar _tmp665 =
      std::pow(Scalar(std::pow(_tmp644, Scalar(2)) * _tmp662 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp666 = Scalar(1.0) * _tmp665 * std::sinh(_tmp653);
  const Scalar _tmp667 = Scalar(0.1034955) * _tmp650 * _tmp662;
  const Scalar _tmp668 = 2 * _tmp647;
  const Scalar _tmp669 = 2 * _tmp648;
  const Scalar _tmp670 = (Scalar(1) / Scalar(2)) / _tmp649;
  const Scalar _tmp671 = Scalar(9.6622558468725703) * _tmp639;
  const Scalar _tmp672 = _tmp665 * _tmp671;
  const Scalar _tmp673 = std::sinh(_tmp652);
  const Scalar _tmp674 = Scalar(0.87679799772039002) * _tmp662;
  const Scalar _tmp675 = _tmp28 - _tmp29 + _tmp30 + _tmp31;
  const Scalar _tmp676 = _tmp47 * _tmp675;
  const Scalar _tmp677 = _tmp372 + _tmp676;
  const Scalar _tmp678 = -_tmp10 - _tmp12 + _tmp6 - _tmp8;
  const Scalar _tmp679 = _tmp26 * _tmp678;
  const Scalar _tmp680 = _tmp127 * _tmp4;
  const Scalar _tmp681 = _tmp679 + _tmp680;
  const Scalar _tmp682 = _tmp34 * _tmp41;
  const Scalar _tmp683 = _tmp43 * _tmp675;
  const Scalar _tmp684 = -_tmp682 - _tmp683;
  const Scalar _tmp685 = _tmp681 + _tmp684;
  const Scalar _tmp686 = _tmp53 * _tmp678;
  const Scalar _tmp687 = _tmp55 * _tmp675;
  const Scalar _tmp688 = _tmp686 + _tmp687 + _tmp85 + _tmp87;
  const Scalar _tmp689 = _tmp685 + _tmp688;
  const Scalar _tmp690 = -_tmp676;
  const Scalar _tmp691 = _tmp371 * _tmp678;
  const Scalar _tmp692 = _tmp690 - _tmp691;
  const Scalar _tmp693 = _tmp57 * _tmp675;
  const Scalar _tmp694 = _tmp59 * _tmp678;
  const Scalar _tmp695 = _tmp264 + _tmp54 + _tmp693 - _tmp694;
  const Scalar _tmp696 = -_tmp679;
  const Scalar _tmp697 = -_tmp680;
  const Scalar _tmp698 = _tmp696 + _tmp697;
  const Scalar _tmp699 = _tmp684 + _tmp698;
  const Scalar _tmp700 = _tmp695 + _tmp699;
  const Scalar _tmp701 = _tmp113 * _tmp678;
  const Scalar _tmp702 = _tmp111 * _tmp20;
  const Scalar _tmp703 = _tmp701 + _tmp702;
  const Scalar _tmp704 = Scalar(0.41999999999999998) * _tmp678;
  const Scalar _tmp705 = _tmp33 * _tmp704;
  const Scalar _tmp706 = _tmp117 * _tmp675;
  const Scalar _tmp707 = _tmp705 + _tmp706;
  const Scalar _tmp708 = _tmp703 + _tmp707;
  const Scalar _tmp709 = _tmp26 * _tmp675;
  const Scalar _tmp710 = _tmp42 * _tmp704;
  const Scalar _tmp711 = -_tmp709 - _tmp710;
  const Scalar _tmp712 = _tmp377 + _tmp711;
  const Scalar _tmp713 = _tmp708 + _tmp712;
  const Scalar _tmp714 = _tmp682 + _tmp683;
  const Scalar _tmp715 = _tmp698 + _tmp714;
  const Scalar _tmp716 = _tmp259 - _tmp686 - _tmp687 + _tmp86;
  const Scalar _tmp717 = -_tmp372 + _tmp690;
  const Scalar _tmp718 = _tmp716 + _tmp717;
  const Scalar _tmp719 = _tmp715 + _tmp718;
  const Scalar _tmp720 = _tmp435 * _tmp719;
  const Scalar _tmp721 = _tmp681 + _tmp714;
  const Scalar _tmp722 = _tmp676 + _tmp691;
  const Scalar _tmp723 = _tmp721 + _tmp722;
  const Scalar _tmp724 = _tmp265 + _tmp56 - _tmp693 + _tmp694;
  const Scalar _tmp725 = _tmp723 + _tmp724;
  const Scalar _tmp726 = _tmp277 * _tmp719 + _tmp283 * _tmp725;
  const Scalar _tmp727 = _tmp286 * _tmp726;
  const Scalar _tmp728 = _tmp288 * _tmp727;
  const Scalar _tmp729 = _tmp699 + _tmp724;
  const Scalar _tmp730 = _tmp692 + _tmp729;
  const Scalar _tmp731 = _tmp677 + _tmp716;
  const Scalar _tmp732 = _tmp685 + _tmp731;
  const Scalar _tmp733 = _tmp263 * _tmp730 + _tmp268 * _tmp732;
  const Scalar _tmp734 = _tmp435 * _tmp725;
  const Scalar _tmp735 = _tmp715 + _tmp731;
  const Scalar _tmp736 = _tmp176 * _tmp735;
  const Scalar _tmp737 = _tmp369 * _tmp675;
  const Scalar _tmp738 = _tmp49 * _tmp678 + _tmp93;
  const Scalar _tmp739 = _tmp48 + _tmp737 + _tmp738;
  const Scalar _tmp740 = _tmp367 * _tmp739;
  const Scalar _tmp741 = _tmp154 * _tmp730;
  const Scalar _tmp742 = _tmp323 * _tmp732;
  const Scalar _tmp743 = _tmp722 + _tmp729;
  const Scalar _tmp744 = _tmp293 * _tmp743 + _tmp295 * _tmp735;
  const Scalar _tmp745 = _tmp299 * _tmp744;
  const Scalar _tmp746 = _tmp306 * _tmp744;
  const Scalar _tmp747 = _tmp176 * _tmp743;
  const Scalar _tmp748 = _tmp155 * _tmp736 - _tmp155 * _tmp746 + _tmp186 * _tmp741 -
                         _tmp186 * _tmp742 + _tmp745 - _tmp747;
  const Scalar _tmp749 = _tmp158 * _tmp748;
  const Scalar _tmp750 = _tmp685 + _tmp718;
  const Scalar _tmp751 = _tmp144 * _tmp750;
  const Scalar _tmp752 = _tmp692 + _tmp721;
  const Scalar _tmp753 = _tmp724 + _tmp752;
  const Scalar _tmp754 = _tmp311 * _tmp750 + _tmp313 * _tmp753;
  const Scalar _tmp755 = _tmp321 * _tmp754;
  const Scalar _tmp756 = _tmp144 * _tmp753;
  const Scalar _tmp757 = _tmp155 * _tmp751 + _tmp156 * _tmp741 - _tmp156 * _tmp742 -
                         _tmp318 * _tmp754 + _tmp755 - _tmp756;
  const Scalar _tmp758 = _tmp328 * _tmp757;
  const Scalar _tmp759 = _tmp182 * _tmp735;
  const Scalar _tmp760 = _tmp709 + _tmp710;
  const Scalar _tmp761 = -_tmp705;
  const Scalar _tmp762 = _tmp123 + _tmp703 - _tmp706 + _tmp761;
  const Scalar _tmp763 = _tmp361 + _tmp760 + _tmp762;
  const Scalar _tmp764 = _tmp156 * _tmp763;
  const Scalar _tmp765 = _tmp181 * _tmp751;
  const Scalar _tmp766 = _tmp130 + _tmp708 + _tmp760;
  const Scalar _tmp767 = _tmp145 * _tmp766 - _tmp155 * _tmp764 - _tmp155 * _tmp765 -
                         _tmp188 * _tmp755 + _tmp188 * _tmp756 - _tmp189 * _tmp741 +
                         _tmp189 * _tmp742 + _tmp379 * _tmp754;
  const Scalar _tmp768 = _tmp186 * _tmp763;
  const Scalar _tmp769 = _tmp357 + _tmp711 + _tmp762;
  const Scalar _tmp770 = -_tmp155 * _tmp759 - _tmp155 * _tmp768 - _tmp183 * _tmp741 +
                         _tmp183 * _tmp742 - _tmp185 * _tmp745 + _tmp185 * _tmp747 +
                         _tmp191 * _tmp769 - _tmp193 * _tmp767 - _tmp194 * _tmp749 +
                         _tmp194 * _tmp758 + _tmp216 * _tmp746;
  const Scalar _tmp771 = -_tmp156 * _tmp766 - _tmp188 * _tmp751 + _tmp363 * _tmp754 -
                         _tmp364 * _tmp754 + _tmp764 + _tmp765;
  const Scalar _tmp772 = _tmp385 * _tmp675;
  const Scalar _tmp773 = _tmp20 * _tmp387 + _tmp772;
  const Scalar _tmp774 = _tmp164 * _tmp773;
  const Scalar _tmp775 = -_tmp166 * _tmp770 - _tmp181 * _tmp746 + _tmp185 * _tmp746 -
                         _tmp186 * _tmp769 - _tmp190 * _tmp749 + _tmp190 * _tmp758 -
                         _tmp193 * _tmp771 - _tmp195 * _tmp774 + _tmp375 * _tmp740 -
                         _tmp376 * _tmp735 + _tmp759 + _tmp768;
  const Scalar _tmp776 = _tmp186 * _tmp775;
  const Scalar _tmp777 = _tmp228 * _tmp229;
  const Scalar _tmp778 = _tmp775 * _tmp777;
  const Scalar _tmp779 = _tmp190 * _tmp757;
  const Scalar _tmp780 = _tmp155 * _tmp763 + _tmp181 * _tmp741 - _tmp181 * _tmp742 +
                         _tmp215 * _tmp767 + _tmp240 * _tmp741 - _tmp240 * _tmp742 -
                         _tmp447 * _tmp757;
  const Scalar _tmp781 = -_tmp166 * _tmp780 + _tmp214 * _tmp741 - _tmp214 * _tmp742 +
                         _tmp215 * _tmp771 - _tmp217 * _tmp774 - _tmp445 * _tmp779 +
                         _tmp446 * _tmp740 - _tmp701 - _tmp702 + _tmp707 + _tmp712;
  const Scalar _tmp782 = _tmp331 * _tmp733;
  const Scalar _tmp783 = _tmp206 * (_tmp220 * _tmp730 - _tmp221 * _tmp732 - _tmp330 * _tmp782 +
                                    _tmp333 * _tmp782 + _tmp334 * _tmp732 - _tmp335 * _tmp730);
  const Scalar _tmp784 = _tmp308 * _tmp733;
  const Scalar _tmp785 = _tmp303 * _tmp732;
  const Scalar _tmp786 = _tmp137 * _tmp751 + _tmp140 * _tmp755 - _tmp140 * _tmp756 +
                         _tmp142 * _tmp756 - _tmp145 * _tmp750 + _tmp156 * _tmp783 +
                         _tmp156 * _tmp784 - _tmp156 * _tmp785 + _tmp223 * _tmp751 -
                         _tmp337 * _tmp754 - _tmp338 * _tmp754;
  const Scalar _tmp787 = _tmp169 * _tmp745 - _tmp169 * _tmp747 + _tmp171 * _tmp747 -
                         _tmp172 * _tmp746 + _tmp186 * _tmp783 + _tmp186 * _tmp784 -
                         _tmp186 * _tmp785 - _tmp191 * _tmp735 - _tmp193 * _tmp786 +
                         _tmp223 * _tmp736 - _tmp223 * _tmp746 - _tmp224 * _tmp749 +
                         _tmp224 * _tmp758 + _tmp225 * _tmp735;
  const Scalar _tmp788 = _tmp230 * (_tmp215 * _tmp786 - _tmp227 * _tmp781 - _tmp450 * _tmp787 +
                                    _tmp451 * _tmp741 - _tmp451 * _tmp742 + _tmp452 * _tmp775 -
                                    _tmp453 * _tmp757 - _tmp783 - _tmp784 + _tmp785);
  const Scalar _tmp789 = _tmp443 * _tmp787;
  const Scalar _tmp790 = _tmp778 + _tmp781 + _tmp788 - _tmp789;
  const Scalar _tmp791 = _tmp192 * _tmp775;
  const Scalar _tmp792 = _tmp197 * _tmp748;
  const Scalar _tmp793 =
      -_tmp198 * _tmp790 - _tmp232 * _tmp792 + _tmp438 * _tmp791 - _tmp741 + _tmp742;
  const Scalar _tmp794 = _tmp431 * _tmp727;
  const Scalar _tmp795 = _tmp392 * _tmp394;
  const Scalar _tmp796 = _tmp345 * _tmp787;
  const Scalar _tmp797 = _tmp351 * _tmp787;
  const Scalar _tmp798 = _tmp302 * _tmp732;
  const Scalar _tmp799 = fh1 * (-_tmp212 * _tmp725 + _tmp237 * _tmp719 + _tmp400 * _tmp727 +
                                _tmp401 * _tmp725 - _tmp402 * _tmp727 - _tmp403 * _tmp719);
  const Scalar _tmp800 = _tmp229 * _tmp245;
  const Scalar _tmp801 = _tmp775 * _tmp800;
  const Scalar _tmp802 = _tmp411 * _tmp787;
  const Scalar _tmp803 = _tmp327 * _tmp757;
  const Scalar _tmp804 = -_tmp239 * _tmp771 + _tmp413 * _tmp773 - _tmp415 * _tmp740 +
                         _tmp416 * _tmp779 + _tmp417 * _tmp767 - _tmp419 * _tmp803;
  const Scalar _tmp805 = _tmp230 * (-_tmp227 * _tmp804 - _tmp239 * _tmp786 - _tmp244 * _tmp787 +
                                    _tmp421 * _tmp757 + _tmp423 * _tmp775);
  const Scalar _tmp806 = _tmp801 - _tmp802 + _tmp804 + _tmp805;
  const Scalar _tmp807 = -_tmp198 * _tmp806 - _tmp247 * _tmp792 + _tmp408 * _tmp791;
  const Scalar _tmp808 =
      -_tmp207 * (-_tmp159 * _tmp168 * _tmp792 + _tmp200 * _tmp736 - _tmp200 * _tmp746 -
                  _tmp392 * _tmp776 - _tmp396 * _tmp751 + _tmp397 * _tmp754 + _tmp399 * _tmp757 +
                  _tmp775 * _tmp795) -
      _tmp236 * _tmp720 + _tmp236 * _tmp728 - _tmp251 * _tmp734 + _tmp251 * _tmp794 -
      _tmp256 * _tmp799 + _tmp271 * _tmp798 - _tmp272 * _tmp733 + _tmp290 * _tmp798 -
      _tmp291 * _tmp733 -
      _tmp353 * (_tmp156 * _tmp797 - _tmp186 * _tmp796 + _tmp253 * _tmp736 - _tmp254 * _tmp751 -
                 _tmp348 * _tmp744 + _tmp349 * _tmp754 - _tmp350 * _tmp749 + _tmp350 * _tmp758) -
      _tmp430 * (_tmp159 * _tmp807 + _tmp248 * _tmp736 - _tmp248 * _tmp746 - _tmp405 * _tmp757 +
                 _tmp406 * _tmp751 - _tmp407 * _tmp754 - _tmp408 * _tmp776 + _tmp429 * _tmp806) +
      _tmp434 * _tmp798 - _tmp437 * _tmp733 -
      _tmp458 * (_tmp159 * _tmp793 + _tmp233 * _tmp736 - _tmp233 * _tmp746 + _tmp429 * _tmp790 -
                 _tmp438 * _tmp776 + _tmp440 * _tmp751 - _tmp441 * _tmp754 - _tmp457 * _tmp757) +
      _tmp459 * _tmp798 - _tmp462 * _tmp733;
  const Scalar _tmp809 = _tmp258 * _tmp808;
  const Scalar _tmp810 = _tmp489 * _tmp740;
  const Scalar _tmp811 = _tmp476 * _tmp774;
  const Scalar _tmp812 = _tmp485 * _tmp678 + _tmp772;
  const Scalar _tmp813 = _tmp166 * _tmp812;
  const Scalar _tmp814 = -_tmp737 + _tmp738 + _tmp810 - _tmp811 - _tmp813 + _tmp91;
  const Scalar _tmp815 = _tmp537 * _tmp814;
  const Scalar _tmp816 = _tmp503 * _tmp814;
  const Scalar _tmp817 = Scalar(6.59232) * _tmp675;
  const Scalar _tmp818 = _tmp213 * _tmp713 + _tmp4 * _tmp817 + _tmp472 * _tmp719 -
                         _tmp474 * _tmp727 + _tmp506 + _tmp507 * _tmp678 + _tmp509 + _tmp719 * fv1;
  const Scalar _tmp819 = _tmp479 * _tmp812;
  const Scalar _tmp820 = _tmp195 * _tmp775;
  const Scalar _tmp821 = -_tmp239 * _tmp767 + _tmp246 * _tmp819 - _tmp248 * _tmp770 +
                         _tmp408 * _tmp820 + _tmp496 * _tmp801 - _tmp496 * _tmp802 +
                         _tmp496 * _tmp805 - _tmp500 * _tmp806 + _tmp532 * _tmp757 -
                         _tmp533 * _tmp814;
  const Scalar _tmp822 = Scalar(1.0) * _tmp367;
  const Scalar _tmp823 = _tmp739 * _tmp822;
  const Scalar _tmp824 = _tmp161 * _tmp774 + _tmp242 * _tmp730 - _tmp483 * _tmp740 + _tmp732;
  const Scalar _tmp825 = _tmp494 * _tmp814;
  const Scalar _tmp826 = _tmp695 + _tmp723;
  const Scalar _tmp827 = -_tmp200 * _tmp770 + _tmp392 * _tmp820 + _tmp476 * _tmp825 -
                         _tmp487 * _tmp812 - _tmp496 * _tmp824 + _tmp826;
  const Scalar _tmp828 = _tmp545 * _tmp740;
  const Scalar _tmp829 = _tmp542 * _tmp814;
  const Scalar _tmp830 =
      -_tmp476 * _tmp829 - _tmp480 * _tmp810 + _tmp480 * _tmp811 + _tmp480 * _tmp813;
  const Scalar _tmp831 = -_tmp238 * _tmp713 - _tmp25 * _tmp817 + _tmp466 - _tmp468 -
                         _tmp472 * _tmp725 + _tmp473 * _tmp678 + _tmp508 * _tmp727 - _tmp725 * fv1;
  const Scalar _tmp832 = _tmp552 * _tmp787;
  const Scalar _tmp833 = _tmp229 * _tmp480;
  const Scalar _tmp834 = _tmp775 * _tmp833;
  const Scalar _tmp835 = _tmp230 * _tmp816;
  const Scalar _tmp836 = -_tmp253 * _tmp770 + _tmp476 * _tmp834 - _tmp476 * _tmp835 +
                         _tmp520 * _tmp812 + _tmp554 * _tmp787 - _tmp555 * _tmp787;
  const Scalar _tmp837 = _tmp231 * _tmp819 - _tmp233 * _tmp770 + _tmp438 * _tmp820 +
                         _tmp496 * _tmp778 + _tmp496 * _tmp788 - _tmp496 * _tmp789 -
                         _tmp500 * _tmp790 - _tmp529 * _tmp814 + _tmp780;
  const Scalar _tmp838 =
      _tmp560 *
      (_tmp558 *
           (_tmp482 * _tmp818 +
            _tmp505 *
                (_tmp167 * _tmp816 - _tmp241 * _tmp827 - _tmp480 * _tmp824 + _tmp501 * _tmp823) +
            _tmp513 * _tmp831 - _tmp518 * _tmp726 + _tmp519 * _tmp720 + _tmp522 * _tmp799 -
            _tmp526 * _tmp726 +
            _tmp531 * (-_tmp231 * _tmp816 - _tmp241 * _tmp837 + _tmp480 * _tmp778 +
                       _tmp480 * _tmp788 - _tmp480 * _tmp789 + _tmp515 * _tmp823) +
            _tmp535 * (-_tmp241 * _tmp821 - _tmp246 * _tmp816 + _tmp480 * _tmp801 -
                       _tmp480 * _tmp802 + _tmp480 * _tmp805 + _tmp523 * _tmp823) +
            _tmp536 * _tmp734 +
            _tmp541 * (_tmp481 * _tmp812 - _tmp539 * _tmp740 - _tmp815 + _tmp816) +
            _tmp549 *
                (-_tmp241 * _tmp830 + _tmp480 * _tmp774 + _tmp512 * _tmp823 - _tmp828 - _tmp829) +
            _tmp557 * (-_tmp241 * _tmp836 + _tmp521 * _tmp823 - _tmp832 + _tmp834 - _tmp835)) -
       _tmp559 * _tmp809);
  const Scalar _tmp839 = _tmp688 + _tmp715;
  const Scalar _tmp840 = _tmp253 * _tmp799;
  const Scalar _tmp841 = _tmp603 * _tmp775;
  const Scalar _tmp842 = _tmp327 * _tmp607;
  const Scalar _tmp843 = -_tmp193 * _tmp840 + _tmp193 * _tmp841 + _tmp252 * _tmp797 +
                         _tmp406 * _tmp734 - _tmp406 * _tmp794 + _tmp440 * _tmp720 -
                         _tmp440 * _tmp728 - _tmp586 * _tmp749 + _tmp586 * _tmp758 -
                         _tmp587 * _tmp792 - _tmp599 * _tmp803 + _tmp602 * _tmp793 -
                         _tmp605 * _tmp803 + _tmp606 * _tmp807 + _tmp757 * _tmp842;
  const Scalar _tmp844 = Scalar(9.6622558468725703) * _tmp635;
  const Scalar _tmp845 = Scalar(0.86565325453551001) * _tmp611;
  const Scalar _tmp846 = _tmp597 * _tmp611;
  const Scalar _tmp847 = _tmp512 * _tmp548;
  const Scalar _tmp848 = _tmp480 * _tmp818;
  const Scalar _tmp849 =
      _tmp612 *
      (_tmp589 * (_tmp540 * _tmp815 - _tmp591 * _tmp848 + _tmp592 * _tmp830 + _tmp593 * _tmp836 +
                  _tmp594 * _tmp827 + _tmp595 * _tmp720 + _tmp596 * _tmp734 - _tmp596 * _tmp794 +
                  _tmp613 * _tmp740 - _tmp614 * _tmp740 - _tmp615 * _tmp740 + _tmp616 * _tmp831 -
                  _tmp617 * _tmp740 - _tmp618 * _tmp740 + _tmp619 * _tmp821 - _tmp620 * _tmp812 +
                  _tmp622 * _tmp799 - _tmp623 * _tmp727 + _tmp624 * _tmp837 - _tmp740 * _tmp847) -
       _tmp843 * _tmp846);
  const Scalar _tmp850 = _tmp611 * _tmp630;
  const Scalar _tmp851 = _tmp238 * _tmp408;
  const Scalar _tmp852 = _tmp213 * _tmp438;
  const Scalar _tmp853 = _tmp233 * _tmp720 - _tmp233 * _tmp728 + _tmp248 * _tmp734 -
                         _tmp248 * _tmp794 - _tmp252 * _tmp796 + _tmp636 * _tmp806 +
                         _tmp637 * _tmp790 - _tmp775 * _tmp851 - _tmp775 * _tmp852 + _tmp840 -
                         _tmp841;
  const Scalar _tmp854 = _tmp493 * _tmp814;
  const Scalar _tmp855 =
      _tmp640 * (-_tmp202 * _tmp825 + _tmp252 * _tmp832 - _tmp252 * _tmp834 + _tmp252 * _tmp835 -
                 _tmp511 * _tmp831 - _tmp520 * _tmp799 - _tmp540 * _tmp816 + _tmp548 * _tmp828 +
                 _tmp548 * _tmp829 - _tmp641 * _tmp720 + _tmp641 * _tmp728 - _tmp642 * _tmp801 +
                 _tmp642 * _tmp802 - _tmp642 * _tmp805 + _tmp643 * _tmp824 - _tmp655 * _tmp778 -
                 _tmp655 * _tmp788 + _tmp655 * _tmp789 - _tmp657 * _tmp734 + _tmp657 * _tmp794 +
                 _tmp658 * _tmp854 + _tmp660 * _tmp854 - _tmp661 * _tmp773 + _tmp848) -
      _tmp663 * _tmp853;
  const Scalar _tmp856 = _tmp20 * _tmp47;
  const Scalar _tmp857 = Scalar(0.83999999999999997) * _tmp32;
  const Scalar _tmp858 = _tmp25 * _tmp857;
  const Scalar _tmp859 = _tmp856 + _tmp858;
  const Scalar _tmp860 = _tmp37 + _tmp38 + _tmp39 - _tmp40;
  const Scalar _tmp861 = _tmp26 * _tmp860;
  const Scalar _tmp862 = _tmp124 + _tmp761;
  const Scalar _tmp863 = _tmp118 + _tmp861 + _tmp862;
  const Scalar _tmp864 = _tmp859 + _tmp863;
  const Scalar _tmp865 = _tmp53 * _tmp860;
  const Scalar _tmp866 = _tmp57 * _tmp678;
  const Scalar _tmp867 = _tmp20 * _tmp55;
  const Scalar _tmp868 = _tmp32 * _tmp59;
  const Scalar _tmp869 = _tmp865 + _tmp866 + _tmp867 + _tmp868;
  const Scalar _tmp870 = _tmp55 * _tmp678;
  const Scalar _tmp871 = _tmp20 * _tmp57;
  const Scalar _tmp872 = _tmp32 * _tmp53;
  const Scalar _tmp873 = _tmp59 * _tmp860;
  const Scalar _tmp874 = -_tmp870 + _tmp871 + _tmp872 - _tmp873;
  const Scalar _tmp875 = Scalar(0.83999999999999997) * _tmp860;
  const Scalar _tmp876 = _tmp4 * _tmp875;
  const Scalar _tmp877 = -_tmp856;
  const Scalar _tmp878 = -_tmp876 + _tmp877;
  const Scalar _tmp879 = _tmp874 + _tmp878;
  const Scalar _tmp880 = _tmp119 - _tmp861;
  const Scalar _tmp881 = _tmp862 + _tmp880;
  const Scalar _tmp882 = _tmp4 * _tmp704;
  const Scalar _tmp883 = -_tmp882;
  const Scalar _tmp884 = _tmp43 * _tmp860;
  const Scalar _tmp885 = -_tmp884;
  const Scalar _tmp886 = _tmp113 * _tmp860;
  const Scalar _tmp887 = _tmp111 * _tmp32;
  const Scalar _tmp888 = _tmp886 + _tmp887;
  const Scalar _tmp889 = _tmp82 + _tmp883 + _tmp885 + _tmp888;
  const Scalar _tmp890 = _tmp34 * _tmp860;
  const Scalar _tmp891 = _tmp32 * _tmp43;
  const Scalar _tmp892 = _tmp680 + _tmp696 + _tmp890 - _tmp891;
  const Scalar _tmp893 = _tmp889 + _tmp892;
  const Scalar _tmp894 = -_tmp865 - _tmp866 - _tmp867 - _tmp868;
  const Scalar _tmp895 = _tmp864 + _tmp894;
  const Scalar _tmp896 = _tmp302 * _tmp895;
  const Scalar _tmp897 = _tmp870 - _tmp871 - _tmp872 + _tmp873;
  const Scalar _tmp898 = _tmp881 + _tmp897;
  const Scalar _tmp899 = _tmp878 + _tmp898;
  const Scalar _tmp900 = _tmp263 * _tmp899 + _tmp268 * _tmp895;
  const Scalar _tmp901 = _tmp856 + _tmp876;
  const Scalar _tmp902 = _tmp358 + _tmp705 + _tmp861;
  const Scalar _tmp903 = _tmp901 + _tmp902;
  const Scalar _tmp904 = _tmp897 + _tmp903;
  const Scalar _tmp905 = _tmp435 * _tmp904;
  const Scalar _tmp906 = _tmp898 + _tmp901;
  const Scalar _tmp907 = _tmp123 + _tmp705 + _tmp880;
  const Scalar _tmp908 = _tmp859 + _tmp907;
  const Scalar _tmp909 = _tmp894 + _tmp908;
  const Scalar _tmp910 = _tmp293 * _tmp906 + _tmp295 * _tmp909;
  const Scalar _tmp911 = _tmp306 * _tmp910;
  const Scalar _tmp912 = _tmp176 * _tmp906;
  const Scalar _tmp913 = _tmp331 * _tmp900;
  const Scalar _tmp914 = _tmp206 * (_tmp220 * _tmp899 - _tmp221 * _tmp895 - _tmp330 * _tmp913 +
                                    _tmp333 * _tmp913 + _tmp334 * _tmp895 - _tmp335 * _tmp899);
  const Scalar _tmp915 = _tmp176 * _tmp909;
  const Scalar _tmp916 = _tmp154 * _tmp899;
  const Scalar _tmp917 = _tmp323 * _tmp895;
  const Scalar _tmp918 = -_tmp858 + _tmp877;
  const Scalar _tmp919 = _tmp894 + _tmp918;
  const Scalar _tmp920 = _tmp863 + _tmp919;
  const Scalar _tmp921 = _tmp144 * _tmp920;
  const Scalar _tmp922 = _tmp878 + _tmp897 + _tmp902;
  const Scalar _tmp923 = _tmp311 * _tmp920 + _tmp313 * _tmp922;
  const Scalar _tmp924 = _tmp321 * _tmp923;
  const Scalar _tmp925 = _tmp144 * _tmp922;
  const Scalar _tmp926 = _tmp155 * _tmp921 + _tmp156 * _tmp916 - _tmp156 * _tmp917 -
                         _tmp318 * _tmp923 + _tmp924 - _tmp925;
  const Scalar _tmp927 = _tmp328 * _tmp926;
  const Scalar _tmp928 = _tmp308 * _tmp900;
  const Scalar _tmp929 = _tmp303 * _tmp895;
  const Scalar _tmp930 = _tmp137 * _tmp921 + _tmp140 * _tmp924 - _tmp140 * _tmp925 +
                         _tmp142 * _tmp925 - _tmp145 * _tmp920 + _tmp156 * _tmp914 +
                         _tmp156 * _tmp928 - _tmp156 * _tmp929 + _tmp223 * _tmp921 -
                         _tmp337 * _tmp923 - _tmp338 * _tmp923;
  const Scalar _tmp931 = _tmp299 * _tmp910;
  const Scalar _tmp932 = -_tmp155 * _tmp911 + _tmp155 * _tmp915 + _tmp186 * _tmp916 -
                         _tmp186 * _tmp917 - _tmp912 + _tmp931;
  const Scalar _tmp933 = _tmp158 * _tmp932;
  const Scalar _tmp934 = -_tmp169 * _tmp912 + _tmp169 * _tmp931 + _tmp171 * _tmp912 -
                         _tmp172 * _tmp911 + _tmp186 * _tmp914 + _tmp186 * _tmp928 -
                         _tmp186 * _tmp929 - _tmp191 * _tmp909 - _tmp193 * _tmp930 -
                         _tmp223 * _tmp911 + _tmp223 * _tmp915 + _tmp224 * _tmp927 -
                         _tmp224 * _tmp933 + _tmp225 * _tmp909;
  const Scalar _tmp935 = _tmp411 * _tmp934;
  const Scalar _tmp936 = _tmp182 * _tmp909;
  const Scalar _tmp937 = _tmp679 + _tmp697 - _tmp890 + _tmp891;
  const Scalar _tmp938 = _tmp889 + _tmp937;
  const Scalar _tmp939 = _tmp278 + _tmp882 + _tmp884 + _tmp888;
  const Scalar _tmp940 = _tmp937 + _tmp939;
  const Scalar _tmp941 = _tmp47 * _tmp678;
  const Scalar _tmp942 = Scalar(0.83999999999999997) * _tmp84;
  const Scalar _tmp943 = _tmp25 * _tmp875 + _tmp4 * _tmp857;
  const Scalar _tmp944 = _tmp941 + _tmp942 + _tmp943;
  const Scalar _tmp945 = _tmp367 * _tmp944;
  const Scalar _tmp946 = _tmp20 * _tmp385;
  const Scalar _tmp947 = _tmp32 * _tmp387 + _tmp946;
  const Scalar _tmp948 = _tmp164 * _tmp947;
  const Scalar _tmp949 = _tmp156 * _tmp940;
  const Scalar _tmp950 = _tmp892 + _tmp939;
  const Scalar _tmp951 = _tmp181 * _tmp921;
  const Scalar _tmp952 = -_tmp156 * _tmp950 - _tmp188 * _tmp921 + _tmp363 * _tmp923 -
                         _tmp364 * _tmp923 + _tmp949 + _tmp951;
  const Scalar _tmp953 = _tmp155 * _tmp940;
  const Scalar _tmp954 = _tmp145 * _tmp950 - _tmp155 * _tmp949 - _tmp155 * _tmp951 -
                         _tmp188 * _tmp924 + _tmp188 * _tmp925 - _tmp189 * _tmp916 +
                         _tmp189 * _tmp917 + _tmp379 * _tmp923;
  const Scalar _tmp955 = -_tmp155 * _tmp936 - _tmp183 * _tmp916 + _tmp183 * _tmp917 +
                         _tmp185 * _tmp912 - _tmp185 * _tmp931 - _tmp186 * _tmp953 +
                         _tmp191 * _tmp938 - _tmp193 * _tmp954 + _tmp194 * _tmp927 -
                         _tmp194 * _tmp933 + _tmp216 * _tmp911;
  const Scalar _tmp956 = -_tmp166 * _tmp955 - _tmp181 * _tmp911 + _tmp185 * _tmp911 -
                         _tmp186 * _tmp938 + _tmp186 * _tmp940 + _tmp190 * _tmp927 -
                         _tmp190 * _tmp933 - _tmp193 * _tmp952 - _tmp195 * _tmp948 +
                         _tmp375 * _tmp945 - _tmp376 * _tmp909 + _tmp936;
  const Scalar _tmp957 = _tmp800 * _tmp956;
  const Scalar _tmp958 = _tmp416 * _tmp926;
  const Scalar _tmp959 = _tmp327 * _tmp926;
  const Scalar _tmp960 = _tmp190 * _tmp958 - _tmp239 * _tmp952 + _tmp413 * _tmp947 -
                         _tmp415 * _tmp945 + _tmp417 * _tmp954 - _tmp419 * _tmp959;
  const Scalar _tmp961 = _tmp197 * _tmp934;
  const Scalar _tmp962 = _tmp422 * _tmp956;
  const Scalar _tmp963 = _tmp230 * (_tmp224 * _tmp958 - _tmp227 * _tmp960 - _tmp239 * _tmp930 -
                                    _tmp243 * _tmp961 + _tmp243 * _tmp962);
  const Scalar _tmp964 = -_tmp935 + _tmp957 + _tmp960 + _tmp963;
  const Scalar _tmp965 = _tmp192 * _tmp956;
  const Scalar _tmp966 = -_tmp198 * _tmp964 - _tmp248 * _tmp932 + _tmp408 * _tmp965;
  const Scalar _tmp967 = _tmp186 * _tmp956;
  const Scalar _tmp968 = _tmp907 + _tmp919;
  const Scalar _tmp969 = _tmp277 * _tmp968 + _tmp283 * _tmp904;
  const Scalar _tmp970 = _tmp286 * _tmp969;
  const Scalar _tmp971 = _tmp288 * _tmp970;
  const Scalar _tmp972 = _tmp435 * _tmp968;
  const Scalar _tmp973 = fh1 * (-_tmp212 * _tmp904 + _tmp237 * _tmp968 + _tmp400 * _tmp970 +
                                _tmp401 * _tmp904 - _tmp402 * _tmp970 - _tmp403 * _tmp968);
  const Scalar _tmp974 = _tmp431 * _tmp970;
  const Scalar _tmp975 = _tmp777 * _tmp956;
  const Scalar _tmp976 = _tmp443 * _tmp934;
  const Scalar _tmp977 = _tmp181 * _tmp916 - _tmp181 * _tmp917 + _tmp215 * _tmp954 +
                         _tmp240 * _tmp916 - _tmp240 * _tmp917 - _tmp447 * _tmp926 + _tmp953;
  const Scalar _tmp978 = -_tmp166 * _tmp977 - _tmp190 * _tmp445 * _tmp926 + _tmp214 * _tmp916 -
                         _tmp214 * _tmp917 + _tmp215 * _tmp952 - _tmp217 * _tmp948 +
                         _tmp446 * _tmp945 + _tmp82 + _tmp883 + _tmp885 - _tmp886 - _tmp887 +
                         _tmp892;
  const Scalar _tmp979 = _tmp230 * (_tmp215 * _tmp930 - _tmp218 * _tmp961 + _tmp218 * _tmp962 -
                                    _tmp227 * _tmp978 + _tmp451 * _tmp916 - _tmp451 * _tmp917 -
                                    _tmp453 * _tmp926 - _tmp914 - _tmp928 + _tmp929);
  const Scalar _tmp980 = _tmp975 - _tmp976 + _tmp978 + _tmp979;
  const Scalar _tmp981 =
      -_tmp198 * _tmp980 - _tmp233 * _tmp932 + _tmp438 * _tmp965 - _tmp916 + _tmp917;
  const Scalar _tmp982 = _tmp351 * _tmp934;
  const Scalar _tmp983 = _tmp345 * _tmp934;
  const Scalar _tmp984 =
      -_tmp207 * (-_tmp200 * _tmp911 + _tmp200 * _tmp915 - _tmp354 * _tmp933 - _tmp392 * _tmp967 -
                  _tmp396 * _tmp921 + _tmp397 * _tmp923 + _tmp399 * _tmp926 + _tmp795 * _tmp956) +
      _tmp236 * _tmp971 - _tmp236 * _tmp972 - _tmp251 * _tmp905 + _tmp251 * _tmp974 -
      _tmp256 * _tmp973 + _tmp271 * _tmp896 - _tmp272 * _tmp900 - _tmp291 * _tmp900 -
      _tmp353 * (_tmp156 * _tmp982 - _tmp186 * _tmp983 + _tmp253 * _tmp915 - _tmp254 * _tmp921 -
                 _tmp348 * _tmp910 + _tmp349 * _tmp923 + _tmp350 * _tmp927 - _tmp350 * _tmp933) -
      _tmp430 * (_tmp159 * _tmp966 - _tmp248 * _tmp911 + _tmp248 * _tmp915 - _tmp405 * _tmp926 +
                 _tmp406 * _tmp921 - _tmp407 * _tmp923 - _tmp408 * _tmp967 + _tmp429 * _tmp964) +
      _tmp434 * _tmp896 - _tmp437 * _tmp900 -
      _tmp458 * (_tmp159 * _tmp981 - _tmp233 * _tmp911 + _tmp233 * _tmp915 + _tmp429 * _tmp980 -
                 _tmp438 * _tmp967 + _tmp440 * _tmp921 - _tmp441 * _tmp923 - _tmp457 * _tmp926) +
      _tmp459 * _tmp896 + _tmp461 * _tmp895 - _tmp462 * _tmp900;
  const Scalar _tmp985 = _tmp258 * _tmp984;
  const Scalar _tmp986 = _tmp476 * _tmp948;
  const Scalar _tmp987 = _tmp489 * _tmp945;
  const Scalar _tmp988 = _tmp485 * _tmp860 + _tmp946;
  const Scalar _tmp989 = _tmp166 * _tmp988;
  const Scalar _tmp990 = -_tmp941 - _tmp942 + _tmp943 - _tmp986 + _tmp987 - _tmp989;
  const Scalar _tmp991 = _tmp503 * _tmp990;
  const Scalar _tmp992 = _tmp822 * _tmp944;
  const Scalar _tmp993 = _tmp195 * _tmp956;
  const Scalar _tmp994 = _tmp479 * _tmp988;
  const Scalar _tmp995 = _tmp231 * _tmp994 - _tmp233 * _tmp955 + _tmp438 * _tmp993 +
                         _tmp496 * _tmp975 - _tmp496 * _tmp976 + _tmp496 * _tmp979 -
                         _tmp500 * _tmp980 - _tmp529 * _tmp990 + _tmp977;
  const Scalar _tmp996 = _tmp537 * _tmp990;
  const Scalar _tmp997 = _tmp161 * _tmp948 + _tmp242 * _tmp899 - _tmp483 * _tmp945 + _tmp895;
  const Scalar _tmp998 = _tmp874 + _tmp903;
  const Scalar _tmp999 = -_tmp200 * _tmp955 + _tmp392 * _tmp993 - _tmp487 * _tmp988 +
                         _tmp495 * _tmp990 - _tmp496 * _tmp997 + _tmp998;
  const Scalar _tmp1000 = _tmp833 * _tmp956;
  const Scalar _tmp1001 = _tmp230 * _tmp991;
  const Scalar _tmp1002 = _tmp1000 * _tmp476 - _tmp1001 * _tmp476 - _tmp253 * _tmp955 +
                          _tmp520 * _tmp988 + _tmp554 * _tmp934 - _tmp555 * _tmp934;
  const Scalar _tmp1003 = _tmp552 * _tmp934;
  const Scalar _tmp1004 = _tmp514 * _tmp969;
  const Scalar _tmp1005 = Scalar(6.59232) * _tmp678;
  const Scalar _tmp1006 = _tmp1005 * _tmp25 + _tmp213 * _tmp893 + _tmp32 * _tmp473 +
                          _tmp4 * _tmp467 + _tmp472 * _tmp968 - _tmp474 * _tmp970 +
                          _tmp507 * _tmp860 + _tmp968 * fv1;
  const Scalar _tmp1007 = _tmp545 * _tmp945;
  const Scalar _tmp1008 = _tmp542 * _tmp990;
  const Scalar _tmp1009 =
      -_tmp1008 * _tmp476 + _tmp480 * _tmp986 - _tmp480 * _tmp987 + _tmp480 * _tmp989;
  const Scalar _tmp1010 = _tmp1005 * _tmp4 - _tmp238 * _tmp893 - _tmp25 * _tmp467 -
                          _tmp33 * _tmp469 - _tmp472 * _tmp904 + _tmp473 * _tmp860 +
                          _tmp508 * _tmp970 - _tmp904 * fv1;
  const Scalar _tmp1011 = _tmp194 * _tmp958 - _tmp239 * _tmp954 + _tmp246 * _tmp994 -
                          _tmp248 * _tmp955 + _tmp408 * _tmp993 - _tmp496 * _tmp935 +
                          _tmp496 * _tmp957 + _tmp496 * _tmp963 - _tmp500 * _tmp964 -
                          _tmp533 * _tmp990;
  const Scalar _tmp1012 =
      _tmp560 *
      (_tmp558 *
           (-_tmp1004 * _tmp517 - _tmp1004 * _tmp525 + _tmp1006 * _tmp482 + _tmp1010 * _tmp513 +
            _tmp505 *
                (_tmp167 * _tmp991 - _tmp241 * _tmp999 - _tmp480 * _tmp997 + _tmp501 * _tmp992) +
            _tmp519 * _tmp972 + _tmp522 * _tmp973 +
            _tmp531 * (-_tmp231 * _tmp991 - _tmp241 * _tmp995 + _tmp480 * _tmp975 -
                       _tmp480 * _tmp976 + _tmp480 * _tmp979 + _tmp515 * _tmp992) +
            _tmp535 * (-_tmp1011 * _tmp241 - _tmp246 * _tmp991 - _tmp480 * _tmp935 +
                       _tmp480 * _tmp957 + _tmp480 * _tmp963 + _tmp523 * _tmp992) +
            _tmp536 * _tmp905 +
            _tmp541 * (_tmp481 * _tmp988 - _tmp539 * _tmp945 + _tmp991 - _tmp996) +
            _tmp549 * (-_tmp1007 - _tmp1008 - _tmp1009 * _tmp241 + _tmp480 * _tmp948 +
                       _tmp512 * _tmp992) +
            _tmp557 * (_tmp1000 - _tmp1001 - _tmp1002 * _tmp241 - _tmp1003 + _tmp521 * _tmp992)) -
       _tmp559 * _tmp985);
  const Scalar _tmp1013 = _tmp869 + _tmp918;
  const Scalar _tmp1014 = _tmp603 * _tmp956;
  const Scalar _tmp1015 = _tmp253 * _tmp973;
  const Scalar _tmp1016 = _tmp1014 * _tmp193 - _tmp1015 * _tmp193 + _tmp252 * _tmp982 +
                          _tmp406 * _tmp905 - _tmp406 * _tmp974 - _tmp440 * _tmp971 +
                          _tmp440 * _tmp972 + _tmp586 * _tmp927 - _tmp586 * _tmp933 -
                          _tmp599 * _tmp959 - _tmp601 * _tmp933 + _tmp602 * _tmp981 -
                          _tmp605 * _tmp959 + _tmp606 * _tmp966 + _tmp842 * _tmp926;
  const Scalar _tmp1017 = _tmp1006 * _tmp480;
  const Scalar _tmp1018 =
      _tmp612 *
      (-_tmp1016 * _tmp846 +
       _tmp589 *
           (_tmp1002 * _tmp593 + _tmp1009 * _tmp592 + _tmp1010 * _tmp616 + _tmp1011 * _tmp619 -
            _tmp1017 * _tmp591 + _tmp540 * _tmp996 + _tmp594 * _tmp999 + _tmp595 * _tmp972 +
            _tmp596 * _tmp905 - _tmp596 * _tmp974 + _tmp613 * _tmp945 - _tmp614 * _tmp945 -
            _tmp615 * _tmp945 - _tmp617 * _tmp945 - _tmp618 * _tmp945 - _tmp620 * _tmp988 +
            _tmp622 * _tmp973 - _tmp623 * _tmp970 + _tmp624 * _tmp995 - _tmp847 * _tmp945));
  const Scalar _tmp1019 = -_tmp1014 + _tmp1015 - _tmp233 * _tmp971 + _tmp233 * _tmp972 +
                          _tmp248 * _tmp905 - _tmp248 * _tmp974 - _tmp252 * _tmp983 +
                          _tmp636 * _tmp964 + _tmp637 * _tmp980 - _tmp851 * _tmp956 -
                          _tmp852 * _tmp956;
  const Scalar _tmp1020 = _tmp493 * _tmp990;
  const Scalar _tmp1021 =
      -_tmp1019 * _tmp663 +
      _tmp640 *
          (-_tmp1000 * _tmp252 + _tmp1001 * _tmp252 + _tmp1003 * _tmp252 + _tmp1007 * _tmp548 +
           _tmp1008 * _tmp548 - _tmp1010 * _tmp511 + _tmp1017 + _tmp1020 * _tmp658 +
           _tmp1020 * _tmp660 - _tmp520 * _tmp973 - _tmp540 * _tmp991 + _tmp641 * _tmp971 -
           _tmp641 * _tmp972 + _tmp642 * _tmp935 - _tmp642 * _tmp957 - _tmp642 * _tmp963 +
           _tmp643 * _tmp997 - _tmp655 * _tmp975 + _tmp655 * _tmp976 - _tmp655 * _tmp979 -
           _tmp656 * _tmp990 - _tmp657 * _tmp905 + _tmp657 * _tmp974 - _tmp661 * _tmp947);

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = -_tmp110 * (_tmp107 * (_tmp83 + _tmp95) + _tmp79 * (_tmp52 + _tmp61)) + _tmp135;
  _res(1, 0) =
      _tmp360 - _tmp463 * _tmp579 -
      _tmp568 *
          (-Scalar(0.86625939559540499) * _tmp464 + _tmp561 * _tmp564 -
           _tmp572 * (-_tmp464 * _tmp578 +
                      _tmp570 * (-_tmp463 * _tmp577 - _tmp561 * _tmp568 -
                                 _tmp576 * (_tmp498 * _tmp575 + _tmp574 * (_tmp274 + _tmp573)))));
  _res(2, 0) =
      _tmp362 - _tmp609 * _tmp635 -
      _tmp610 *
          (-Scalar(0.86565325453551001) * _tmp625 + _tmp626 * _tmp634 -
           _tmp632 * (-_tmp625 * _tmp630 + _tmp627 * (-_tmp585 * (_tmp581 * (_tmp51 + _tmp573) +
                                                                  _tmp583 * (_tmp497 + _tmp83)) -
                                                      _tmp598 * _tmp609 - _tmp610 * _tmp626)));
  _res(3, 0) = _tmp378 - _tmp638 * _tmp654 -
               _tmp671 * (-_tmp638 * _tmp674 + _tmp664 * _tmp666 -
                          _tmp673 * (-_tmp638 * _tmp667 +
                                     _tmp651 * (-_tmp638 * _tmp646 - _tmp664 * _tmp672 -
                                                _tmp670 * (_tmp668 * (_tmp274 + _tmp46 + _tmp61) +
                                                           _tmp669 * (_tmp279 + _tmp95)))));
  _res(0, 1) = -_tmp110 * (_tmp107 * (_tmp692 + _tmp700) + _tmp79 * (_tmp677 + _tmp689)) + _tmp713;
  _res(1, 1) =
      -_tmp568 *
          (_tmp564 * _tmp838 -
           _tmp572 * (_tmp570 * (-_tmp568 * _tmp838 -
                                 _tmp576 * (_tmp574 * (_tmp717 + _tmp839) + _tmp575 * _tmp826) -
                                 _tmp577 * _tmp808) -
                      _tmp578 * _tmp809) -
           Scalar(0.86625939559540499) * _tmp809) -
      _tmp579 * _tmp808 + _tmp763;
  _res(2, 1) = -_tmp610 * (-_tmp632 * (_tmp627 * (-_tmp585 * (_tmp581 * (_tmp677 + _tmp839) +
                                                              _tmp583 * (_tmp700 + _tmp722)) -
                                                  _tmp610 * _tmp849 - _tmp628 * _tmp843) -
                                       _tmp843 * _tmp850) +
                           _tmp634 * _tmp849 - _tmp843 * _tmp845) +
               _tmp766 - _tmp843 * _tmp844;
  _res(3, 1) = -_tmp654 * _tmp853 -
               _tmp671 * (_tmp666 * _tmp855 -
                          _tmp673 * (_tmp651 * (-_tmp646 * _tmp853 -
                                                _tmp670 * (_tmp668 * (_tmp689 + _tmp717) +
                                                           _tmp669 * (_tmp695 + _tmp752)) -
                                                _tmp672 * _tmp855) -
                                     _tmp667 * _tmp853) -
                          _tmp674 * _tmp853) +
               _tmp769;
  _res(0, 2) = -_tmp110 * (_tmp107 * (_tmp879 + _tmp881) + _tmp79 * (_tmp864 + _tmp869)) + _tmp893;
  _res(1, 2) =
      -_tmp568 *
          (_tmp1012 * _tmp564 -
           _tmp572 * (_tmp570 * (-_tmp1012 * _tmp568 -
                                 _tmp576 * (_tmp574 * (_tmp1013 + _tmp907) + _tmp575 * _tmp998) -
                                 _tmp577 * _tmp984) -
                      _tmp578 * _tmp985) -
           Scalar(0.86625939559540499) * _tmp985) -
      _tmp579 * _tmp984 + _tmp940;
  _res(2, 2) =
      -_tmp1016 * _tmp844 -
      _tmp610 * (-_tmp1016 * _tmp845 + _tmp1018 * _tmp634 -
                 _tmp632 * (-_tmp1016 * _tmp850 +
                            _tmp627 * (-_tmp1016 * _tmp628 - _tmp1018 * _tmp610 -
                                       _tmp585 * (_tmp581 * (_tmp869 + _tmp908) +
                                                  _tmp583 * (_tmp874 + _tmp881 + _tmp901))))) +
      _tmp950;
  _res(3, 2) = -_tmp1019 * _tmp654 -
               _tmp671 * (-_tmp1019 * _tmp674 + _tmp1021 * _tmp666 -
                          _tmp673 * (-_tmp1019 * _tmp667 +
                                     _tmp651 * (-_tmp1019 * _tmp646 - _tmp1021 * _tmp672 -
                                                _tmp670 * (_tmp668 * (_tmp1013 + _tmp863) +
                                                           _tmp669 * (_tmp879 + _tmp902))))) +
               _tmp938;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
