// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost1_wrt_fh1_Nl13
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost1WrtFh1Nl13(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot, const Scalar p_init0,
    const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x, const Scalar rot_init_y,
    const Scalar rot_init_z, const Scalar rot_init_w, const Scalar epsilon) {
  // Total ops: 652

  // Unused inputs
  (void)p_init2;
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();

  // Intermediate terms (209)
  const Scalar _tmp0 = std::pow(fh1, Scalar(-2));
  const Scalar _tmp1 = _DeltaRot[0] * rot_init_z + _DeltaRot[1] * rot_init_w -
                       _DeltaRot[2] * rot_init_x + _DeltaRot[3] * rot_init_y;
  const Scalar _tmp2 = -2 * std::pow(_tmp1, Scalar(2));
  const Scalar _tmp3 = -_DeltaRot[0] * rot_init_y + _DeltaRot[1] * rot_init_x +
                       _DeltaRot[2] * rot_init_w + _DeltaRot[3] * rot_init_z;
  const Scalar _tmp4 = 1 - 2 * std::pow(_tmp3, Scalar(2));
  const Scalar _tmp5 = Scalar(0.20999999999999999) * _tmp2 + Scalar(0.20999999999999999) * _tmp4;
  const Scalar _tmp6 = _DeltaRot[0] * rot_init_w - _DeltaRot[1] * rot_init_z +
                       _DeltaRot[2] * rot_init_y + _DeltaRot[3] * rot_init_x;
  const Scalar _tmp7 = 2 * _tmp3 * _tmp6;
  const Scalar _tmp8 = -2 * _DeltaRot[0] * rot_init_x - 2 * _DeltaRot[1] * rot_init_y -
                       2 * _DeltaRot[2] * rot_init_z + 2 * _DeltaRot[3] * rot_init_w;
  const Scalar _tmp9 = _tmp1 * _tmp8;
  const Scalar _tmp10 = _tmp7 + _tmp9;
  const Scalar _tmp11 = -Scalar(0.010999999999999999) * _tmp10;
  const Scalar _tmp12 = 2 * _tmp1;
  const Scalar _tmp13 = _tmp12 * _tmp6;
  const Scalar _tmp14 = _tmp3 * _tmp8;
  const Scalar _tmp15 = Scalar(0.20999999999999999) * _tmp13 - Scalar(0.20999999999999999) * _tmp14;
  const Scalar _tmp16 = _tmp11 + _tmp15;
  const Scalar _tmp17 = _tmp16 + _tmp5;
  const Scalar _tmp18 = _tmp17 + p_init0;
  const Scalar _tmp19 = Scalar(0.20999999999999999) * _tmp13 + Scalar(0.20999999999999999) * _tmp14;
  const Scalar _tmp20 = _tmp12 * _tmp3;
  const Scalar _tmp21 = _tmp6 * _tmp8;
  const Scalar _tmp22 = _tmp20 - _tmp21;
  const Scalar _tmp23 = -Scalar(0.010999999999999999) * _tmp22;
  const Scalar _tmp24 = -2 * std::pow(_tmp6, Scalar(2));
  const Scalar _tmp25 = Scalar(0.20999999999999999) * _tmp24 + Scalar(0.20999999999999999) * _tmp4;
  const Scalar _tmp26 = _tmp23 + _tmp25;
  const Scalar _tmp27 = _tmp19 + _tmp26;
  const Scalar _tmp28 = _tmp27 + p_init1;
  const Scalar _tmp29 = Scalar(1.0) / (fh1);
  const Scalar _tmp30 = _tmp29 * fv1;
  const Scalar _tmp31 = std::asinh(_tmp30);
  const Scalar _tmp32 = Scalar(9.6622558468725703) * _tmp31;
  const Scalar _tmp33 =
      -_tmp32 * fh1 -
      Scalar(4.7752063900000001) *
          std::sqrt(
              Scalar(Scalar(0.32397683292140877) *
                         std::pow(Scalar(1 - Scalar(0.36791786395571047) * _tmp18), Scalar(2)) +
                     std::pow(Scalar(1 - Scalar(0.20941503221602112) * _tmp28), Scalar(2))));
  const Scalar _tmp34 = Scalar(0.1034955) * _tmp29;
  const Scalar _tmp35 = _tmp33 * _tmp34;
  const Scalar _tmp36 =
      std::pow(Scalar(_tmp0 * std::pow(fv1, Scalar(2)) + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp37 = Scalar(1.0) * _tmp31;
  const Scalar _tmp38 = -_tmp19;
  const Scalar _tmp39 = _tmp23 - _tmp25;
  const Scalar _tmp40 = _tmp38 + _tmp39;
  const Scalar _tmp41 = _tmp40 + p_init1;
  const Scalar _tmp42 = _tmp41 + Scalar(8.3196563700000006);
  const Scalar _tmp43 = -_tmp5;
  const Scalar _tmp44 = _tmp11 - _tmp15;
  const Scalar _tmp45 = _tmp43 + _tmp44;
  const Scalar _tmp46 = _tmp45 + p_init0;
  const Scalar _tmp47 = _tmp46 + Scalar(1.9874742000000001);
  const Scalar _tmp48 =
      std::sqrt(Scalar(std::pow(_tmp42, Scalar(2)) + std::pow(_tmp47, Scalar(2))));
  const Scalar _tmp49 = Scalar(1.0) / (_tmp48);
  const Scalar _tmp50 = Scalar(1.0) / (_tmp47);
  const Scalar _tmp51 = _tmp48 * _tmp50;
  const Scalar _tmp52 = _tmp51 * (-_tmp40 * _tmp47 * _tmp49 + _tmp42 * _tmp45 * _tmp49);
  const Scalar _tmp53 = _tmp42 * _tmp50;
  const Scalar _tmp54 = _tmp26 + _tmp38;
  const Scalar _tmp55 = _tmp54 + p_init1;
  const Scalar _tmp56 = _tmp55 + Scalar(-4.8333311099999996);
  const Scalar _tmp57 = _tmp16 + _tmp43;
  const Scalar _tmp58 = _tmp57 + p_init0;
  const Scalar _tmp59 = _tmp58 + Scalar(1.79662371);
  const Scalar _tmp60 = std::pow(Scalar(std::pow(_tmp56, Scalar(2)) + std::pow(_tmp59, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp61 = _tmp59 * _tmp60;
  const Scalar _tmp62 = _tmp56 * _tmp60;
  const Scalar _tmp63 = Scalar(1.0) / (_tmp53 * _tmp61 - _tmp62);
  const Scalar _tmp64 = _tmp63 * (_tmp52 * _tmp61 + _tmp54 * _tmp61 - _tmp57 * _tmp62);
  const Scalar _tmp65 = Scalar(0.20999999999999999) * _tmp7 - Scalar(0.20999999999999999) * _tmp9;
  const Scalar _tmp66 = -_tmp65;
  const Scalar _tmp67 = -Scalar(0.010999999999999999) * _tmp2 -
                        Scalar(0.010999999999999999) * _tmp24 + Scalar(-0.010999999999999999);
  const Scalar _tmp68 = Scalar(0.20999999999999999) * _tmp20 + Scalar(0.20999999999999999) * _tmp21;
  const Scalar _tmp69 = _tmp67 + _tmp68;
  const Scalar _tmp70 = _tmp66 + _tmp69;
  const Scalar _tmp71 = _tmp67 - _tmp68;
  const Scalar _tmp72 = _tmp66 + _tmp71;
  const Scalar _tmp73 = _tmp61 * _tmp72;
  const Scalar _tmp74 = _tmp63 * (-_tmp53 * _tmp73 + _tmp62 * _tmp70);
  const Scalar _tmp75 = _tmp53 * _tmp72 + _tmp53 * _tmp74;
  const Scalar _tmp76 = Scalar(1.0) * _tmp40;
  const Scalar _tmp77 = -_tmp76;
  const Scalar _tmp78 = Scalar(1.0) / (_tmp54 + _tmp77);
  const Scalar _tmp79 = Scalar(1.0) * _tmp45;
  const Scalar _tmp80 = -_tmp57 + _tmp79;
  const Scalar _tmp81 = _tmp78 * _tmp80;
  const Scalar _tmp82 = _tmp63 * (-_tmp61 * _tmp70 + _tmp73);
  const Scalar _tmp83 = _tmp53 * _tmp82 - _tmp72 - _tmp75 * _tmp81;
  const Scalar _tmp84 = _tmp44 + _tmp5;
  const Scalar _tmp85 = _tmp84 + p_init0;
  const Scalar _tmp86 = _tmp85 + Scalar(-2.5202214700000001);
  const Scalar _tmp87 = _tmp19 + _tmp39;
  const Scalar _tmp88 = _tmp87 + p_init1;
  const Scalar _tmp89 = _tmp88 + Scalar(8.3888750099999996);
  const Scalar _tmp90 = std::pow(Scalar(std::pow(_tmp86, Scalar(2)) + std::pow(_tmp89, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp91 = _tmp89 * _tmp90;
  const Scalar _tmp92 = _tmp86 * _tmp90;
  const Scalar _tmp93 = _tmp53 * _tmp92 - _tmp91;
  const Scalar _tmp94 = _tmp65 + _tmp71;
  const Scalar _tmp95 = _tmp72 * _tmp92;
  const Scalar _tmp96 = -_tmp53 * _tmp95 - _tmp74 * _tmp93 + _tmp91 * _tmp94;
  const Scalar _tmp97 = -_tmp81 * _tmp96 - _tmp82 * _tmp93 - _tmp92 * _tmp94 + _tmp95;
  const Scalar _tmp98 = Scalar(1.0) / (_tmp97);
  const Scalar _tmp99 = _tmp52 * _tmp92 - _tmp64 * _tmp93 - _tmp84 * _tmp91 + _tmp87 * _tmp92;
  const Scalar _tmp100 = _tmp98 * _tmp99;
  const Scalar _tmp101 = Scalar(1.0) / (_tmp99);
  const Scalar _tmp102 = _tmp101 * _tmp97;
  const Scalar _tmp103 = _tmp102 * (-_tmp100 * _tmp83 - _tmp52 + _tmp53 * _tmp64);
  const Scalar _tmp104 = _tmp77 + _tmp87;
  const Scalar _tmp105 = _tmp104 * _tmp81;
  const Scalar _tmp106 = Scalar(1.0) / (-_tmp105 + _tmp79 - _tmp84);
  const Scalar _tmp107 = _tmp104 * _tmp106;
  const Scalar _tmp108 = _tmp98 * (_tmp103 + _tmp83);
  const Scalar _tmp109 = _tmp103 * _tmp107 - _tmp108 * _tmp96 + _tmp75;
  const Scalar _tmp110 = Scalar(1.0) * _tmp78;
  const Scalar _tmp111 = Scalar(1.0) * _tmp106;
  const Scalar _tmp112 = _tmp18 + Scalar(-2.71799795);
  const Scalar _tmp113 = _tmp28 + Scalar(-4.7752063900000001);
  const Scalar _tmp114 =
      std::pow(Scalar(std::pow(_tmp112, Scalar(2)) + std::pow(_tmp113, Scalar(2))),
               Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp115 = _tmp112 * _tmp114;
  const Scalar _tmp116 = Scalar(1.0) * _tmp115 * (_tmp103 * _tmp111 - _tmp109 * _tmp110);
  const Scalar _tmp117 = _tmp113 * _tmp114;
  const Scalar _tmp118 = -_tmp115 * _tmp27 + _tmp117 * _tmp17;
  const Scalar _tmp119 = Scalar(1.0) * _tmp101;
  const Scalar _tmp120 = _tmp102 * _tmp111;
  const Scalar _tmp121 = _tmp104 * _tmp120 - _tmp119 * _tmp96;
  const Scalar _tmp122 = Scalar(1.0) * _tmp118 * (-_tmp110 * _tmp121 + _tmp120);
  const Scalar _tmp123 = _tmp65 + _tmp69;
  const Scalar _tmp124 = _tmp123 * fh1;
  const Scalar _tmp125 = Scalar(3.29616) * _tmp10 + _tmp115 * _tmp124 + _tmp17 * fv1;
  const Scalar _tmp126 = _tmp104 * _tmp78;
  const Scalar _tmp127 = _tmp111 * _tmp126;
  const Scalar _tmp128 = -Scalar(1.0) * _tmp111 + Scalar(1.0) * _tmp127;
  const Scalar _tmp129 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp130 = _tmp76 * _tmp81 + _tmp79;
  const Scalar _tmp131 = 0;
  const Scalar _tmp132 = _tmp106 * _tmp130;
  const Scalar _tmp133 = -_tmp104 * _tmp132 - _tmp131 * _tmp96 + _tmp77;
  const Scalar _tmp134 = -_tmp117 * _tmp124 - Scalar(3.29616) * _tmp22 - _tmp27 * fv1;
  const Scalar _tmp135 = _tmp105 * _tmp111 + Scalar(1.0);
  const Scalar _tmp136 = _tmp111 * _tmp81;
  const Scalar _tmp137 = -Scalar(1.0) * _tmp110 * _tmp135 + Scalar(1.0) * _tmp136;
  const Scalar _tmp138 = _tmp110 * _tmp74 * _tmp80 - Scalar(1.0) * _tmp82;
  const Scalar _tmp139 = _tmp102 * (-_tmp100 * _tmp138 - Scalar(1.0) * _tmp64);
  const Scalar _tmp140 = _tmp98 * (_tmp138 + _tmp139);
  const Scalar _tmp141 = _tmp107 * _tmp139 - _tmp140 * _tmp96 - Scalar(1.0) * _tmp74;
  const Scalar _tmp142 = Scalar(1.0) * _tmp117 * (-_tmp110 * _tmp141 + _tmp111 * _tmp139);
  const Scalar _tmp143 =
      _tmp116 * fh1 + _tmp122 * fh1 + _tmp125 * _tmp128 +
      Scalar(1.0) * _tmp129 * (-_tmp110 * _tmp133 - _tmp111 * _tmp130 + Scalar(1.0)) +
      _tmp134 * _tmp137 + _tmp142 * fh1;
  const Scalar _tmp144 = _tmp63 * (-_tmp140 * _tmp93 + Scalar(1.0));
  const Scalar _tmp145 = _tmp117 * _tmp51 * (_tmp140 * _tmp92 + _tmp144 * _tmp61);
  const Scalar _tmp146 = _tmp63 * (-_tmp108 * _tmp93 - _tmp53);
  const Scalar _tmp147 = _tmp115 * _tmp51 * (_tmp108 * _tmp92 + _tmp146 * _tmp61 + Scalar(1.0));
  const Scalar _tmp148 = _tmp63 * _tmp93;
  const Scalar _tmp149 = _tmp148 * _tmp61;
  const Scalar _tmp150 = _tmp118 * _tmp51 * (-_tmp119 * _tmp149 + _tmp119 * _tmp92);
  const Scalar _tmp151 = -_tmp129 * _tmp51 * (-_tmp131 * _tmp149 + _tmp131 * _tmp92) -
                         _tmp145 * fh1 - _tmp147 * fh1 - _tmp150 * fh1;
  const Scalar _tmp152 = Scalar(1.0) / (_tmp151);
  const Scalar _tmp153 = std::asinh(_tmp143 * _tmp152);
  const Scalar _tmp154 = Scalar(1.0) * _tmp153;
  const Scalar _tmp155 = Scalar(9.6622558468725703) * _tmp151;
  const Scalar _tmp156 =
      -_tmp153 * _tmp155 -
      Scalar(8.3196563700000006) *
          std::sqrt(
              Scalar(std::pow(Scalar(-Scalar(0.12019727204189803) * _tmp41 - 1), Scalar(2)) +
                     Scalar(0.057067943376852184) *
                         std::pow(Scalar(-Scalar(0.50315118556004401) * _tmp46 - 1), Scalar(2))));
  const Scalar _tmp157 = Scalar(0.1034955) * _tmp152;
  const Scalar _tmp158 = _tmp156 * _tmp157;
  const Scalar _tmp159 = -_tmp145 - _tmp147 - _tmp150;
  const Scalar _tmp160 = Scalar(9.6622558468725703) * _tmp159;
  const Scalar _tmp161 = std::pow(_tmp151, Scalar(-2));
  const Scalar _tmp162 = _tmp159 * _tmp161;
  const Scalar _tmp163 = _tmp115 * _tmp123;
  const Scalar _tmp164 = _tmp117 * _tmp123;
  const Scalar _tmp165 = (-_tmp143 * _tmp162 + _tmp152 * (_tmp116 + _tmp122 + _tmp128 * _tmp163 -
                                                          _tmp137 * _tmp164 + _tmp142)) /
                         std::sqrt(Scalar(std::pow(_tmp143, Scalar(2)) * _tmp161 + 1));
  const Scalar _tmp166 = _tmp118 * _tmp119;
  const Scalar _tmp167 = _tmp166 * fh1;
  const Scalar _tmp168 = _tmp115 * _tmp146;
  const Scalar _tmp169 = _tmp117 * _tmp144;
  const Scalar _tmp170 = _tmp129 * _tmp131;
  const Scalar _tmp171 = -_tmp148 * _tmp167 - _tmp148 * _tmp170 + _tmp168 * fh1 + _tmp169 * fh1;
  const Scalar _tmp172 = std::pow(_tmp171, Scalar(-2));
  const Scalar _tmp173 = -_tmp148 * _tmp166 + _tmp168 + _tmp169;
  const Scalar _tmp174 = _tmp172 * _tmp173;
  const Scalar _tmp175 = _tmp109 * _tmp115 * _tmp78;
  const Scalar _tmp176 = _tmp111 * _tmp125;
  const Scalar _tmp177 = _tmp135 * _tmp78;
  const Scalar _tmp178 = _tmp117 * _tmp141 * _tmp78;
  const Scalar _tmp179 = _tmp118 * _tmp121 * _tmp78;
  const Scalar _tmp180 = -_tmp126 * _tmp176 + _tmp129 * _tmp133 * _tmp78 + _tmp134 * _tmp177 +
                         _tmp175 * fh1 + _tmp178 * fh1 + _tmp179 * fh1;
  const Scalar _tmp181 = Scalar(1.0) / (_tmp171);
  const Scalar _tmp182 = std::asinh(_tmp180 * _tmp181);
  const Scalar _tmp183 = Scalar(1.0) * _tmp182;
  const Scalar _tmp184 = (-_tmp174 * _tmp180 + _tmp181 * (-_tmp127 * _tmp163 - _tmp164 * _tmp177 +
                                                          _tmp175 + _tmp178 + _tmp179)) /
                         std::sqrt(Scalar(_tmp172 * std::pow(_tmp180, Scalar(2)) + 1));
  const Scalar _tmp185 = Scalar(9.6622558468725703) * _tmp171;
  const Scalar _tmp186 =
      -_tmp182 * _tmp185 -
      Scalar(4.8333311099999996) *
          std::sqrt(
              Scalar(std::pow(Scalar(1 - Scalar(0.20689664689659551) * _tmp55), Scalar(2)) +
                     Scalar(0.13817235445745474) *
                         std::pow(Scalar(-Scalar(0.55659957866191134) * _tmp58 - 1), Scalar(2))));
  const Scalar _tmp187 = Scalar(0.1034955) * _tmp181;
  const Scalar _tmp188 = _tmp186 * _tmp187;
  const Scalar _tmp189 = Scalar(9.6622558468725703) * _tmp173;
  const Scalar _tmp190 = _tmp108 * _tmp115;
  const Scalar _tmp191 = _tmp117 * _tmp140;
  const Scalar _tmp192 = _tmp167 + _tmp170 + _tmp190 * fh1 + _tmp191 * fh1;
  const Scalar _tmp193 = Scalar(1.0) / (_tmp192);
  const Scalar _tmp194 = _tmp106 * _tmp117 * _tmp139;
  const Scalar _tmp195 = _tmp118 * _tmp120;
  const Scalar _tmp196 = _tmp103 * _tmp106 * _tmp115;
  const Scalar _tmp197 = _tmp129 * _tmp132 - _tmp134 * _tmp136 + _tmp176 - _tmp194 * fh1 -
                         _tmp195 * fh1 - _tmp196 * fh1;
  const Scalar _tmp198 = std::asinh(_tmp193 * _tmp197);
  const Scalar _tmp199 = _tmp166 + _tmp190 + _tmp191;
  const Scalar _tmp200 = Scalar(9.6622558468725703) * _tmp199;
  const Scalar _tmp201 = Scalar(9.6622558468725703) * _tmp192;
  const Scalar _tmp202 = std::pow(_tmp192, Scalar(-2));
  const Scalar _tmp203 = _tmp199 * _tmp202;
  const Scalar _tmp204 =
      (_tmp193 * (_tmp111 * _tmp163 + _tmp136 * _tmp164 - _tmp194 - _tmp195 - _tmp196) -
       _tmp197 * _tmp203) /
      std::sqrt(Scalar(std::pow(_tmp197, Scalar(2)) * _tmp202 + 1));
  const Scalar _tmp205 = Scalar(0.1034955) * _tmp193;
  const Scalar _tmp206 =
      -_tmp198 * _tmp201 -
      Scalar(8.3888750099999996) *
          std::sqrt(
              Scalar(Scalar(0.090254729040973036) *
                         std::pow(Scalar(1 - Scalar(0.39679052492160538) * _tmp85), Scalar(2)) +
                     std::pow(Scalar(-Scalar(0.11920549523123722) * _tmp88 - 1), Scalar(2))));
  const Scalar _tmp207 = _tmp205 * _tmp206;
  const Scalar _tmp208 = Scalar(1.0) * _tmp198;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) = -Scalar(8.3641632200000018) * _tmp29 -
               Scalar(9.6622558468725703) * fh1 *
                   (-Scalar(1.0) * _tmp0 * _tmp36 * fv1 * std::sinh(_tmp37) -
                    Scalar(0.86565325453551001) * _tmp0 -
                    (-Scalar(0.1034955) * _tmp0 * _tmp33 +
                     _tmp34 * (Scalar(9.6622558468725703) * _tmp30 * _tmp36 - _tmp32)) *
                        std::sinh(_tmp35)) +
               Scalar(9.6622558468725703) * std::cosh(_tmp35) -
               Scalar(9.6622558468725703) * std::cosh(_tmp37);
  _res(1, 0) =
      -_tmp155 *
          (-Scalar(0.87679799772039002) * _tmp162 + Scalar(1.0) * _tmp165 * std::sinh(_tmp154) -
           (-Scalar(0.1034955) * _tmp156 * _tmp162 +
            _tmp157 * (-_tmp153 * _tmp160 - _tmp155 * _tmp165)) *
               std::sinh(_tmp158)) -
      _tmp160 * (Scalar(0.87679799772039002) * _tmp152 + std::cosh(_tmp154) - std::cosh(_tmp158));
  _res(2, 0) =
      -_tmp185 *
          (-Scalar(0.86625939559540499) * _tmp174 + Scalar(1.0) * _tmp184 * std::sinh(_tmp183) -
           (-Scalar(0.1034955) * _tmp174 * _tmp186 +
            _tmp187 * (-_tmp182 * _tmp189 - _tmp184 * _tmp185)) *
               std::sinh(_tmp188)) -
      _tmp189 * (Scalar(0.86625939559540499) * _tmp181 + std::cosh(_tmp183) - std::cosh(_tmp188));
  _res(3, 0) =
      -_tmp200 * (Scalar(0.87653584775870996) * _tmp193 - std::cosh(_tmp207) + std::cosh(_tmp208)) -
      _tmp201 *
          (-Scalar(0.87653584775870996) * _tmp203 + Scalar(1.0) * _tmp204 * std::sinh(_tmp208) -
           (-Scalar(0.1034955) * _tmp203 * _tmp206 +
            _tmp205 * (-_tmp198 * _tmp200 - _tmp201 * _tmp204)) *
               std::sinh(_tmp207));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
