// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost1_wrt_fh1_Nl21
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     p_init0: Scalar
 *     p_init1: Scalar
 *     p_init2: Scalar
 *     rot_init_x: Scalar
 *     rot_init_y: Scalar
 *     rot_init_z: Scalar
 *     rot_init_w: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix41
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 1> IkResidualFuncCost1WrtFh1Nl21(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot, const Scalar p_init0,
    const Scalar p_init1, const Scalar p_init2, const Scalar rot_init_x, const Scalar rot_init_y,
    const Scalar rot_init_z, const Scalar rot_init_w, const Scalar epsilon) {
  // Total ops: 651

  // Unused inputs
  (void)p_init2;
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();

  // Intermediate terms (211)
  const Scalar _tmp0 = Scalar(1.0) / (fh1);
  const Scalar _tmp1 = _DeltaRot[0] * rot_init_z + _DeltaRot[1] * rot_init_w -
                       _DeltaRot[2] * rot_init_x + _DeltaRot[3] * rot_init_y;
  const Scalar _tmp2 = -2 * std::pow(_tmp1, Scalar(2));
  const Scalar _tmp3 = -_DeltaRot[0] * rot_init_y + _DeltaRot[1] * rot_init_x +
                       _DeltaRot[2] * rot_init_w + _DeltaRot[3] * rot_init_z;
  const Scalar _tmp4 = 1 - 2 * std::pow(_tmp3, Scalar(2));
  const Scalar _tmp5 = Scalar(0.20999999999999999) * _tmp2 + Scalar(0.20999999999999999) * _tmp4;
  const Scalar _tmp6 = -_tmp5;
  const Scalar _tmp7 = _DeltaRot[0] * rot_init_w - _DeltaRot[1] * rot_init_z +
                       _DeltaRot[2] * rot_init_y + _DeltaRot[3] * rot_init_x;
  const Scalar _tmp8 = 2 * _tmp3 * _tmp7;
  const Scalar _tmp9 = -2 * _DeltaRot[0] * rot_init_x - 2 * _DeltaRot[1] * rot_init_y -
                       2 * _DeltaRot[2] * rot_init_z + 2 * _DeltaRot[3] * rot_init_w;
  const Scalar _tmp10 = _tmp1 * _tmp9;
  const Scalar _tmp11 = _tmp10 + _tmp8;
  const Scalar _tmp12 = -Scalar(0.010999999999999999) * _tmp11;
  const Scalar _tmp13 = 2 * _tmp1;
  const Scalar _tmp14 = _tmp13 * _tmp7;
  const Scalar _tmp15 = _tmp3 * _tmp9;
  const Scalar _tmp16 = Scalar(0.20999999999999999) * _tmp14 - Scalar(0.20999999999999999) * _tmp15;
  const Scalar _tmp17 = _tmp12 + _tmp16;
  const Scalar _tmp18 = _tmp17 + _tmp6;
  const Scalar _tmp19 = _tmp18 + p_init0;
  const Scalar _tmp20 = -2 * std::pow(_tmp7, Scalar(2));
  const Scalar _tmp21 = Scalar(0.20999999999999999) * _tmp20 + Scalar(0.20999999999999999) * _tmp4;
  const Scalar _tmp22 = Scalar(0.20999999999999999) * _tmp14 + Scalar(0.20999999999999999) * _tmp15;
  const Scalar _tmp23 = _tmp13 * _tmp3;
  const Scalar _tmp24 = _tmp7 * _tmp9;
  const Scalar _tmp25 = _tmp23 - _tmp24;
  const Scalar _tmp26 = -Scalar(0.010999999999999999) * _tmp25;
  const Scalar _tmp27 = -_tmp22 + _tmp26;
  const Scalar _tmp28 = _tmp21 + _tmp27;
  const Scalar _tmp29 = _tmp28 + p_init1;
  const Scalar _tmp30 = _tmp0 * fv1;
  const Scalar _tmp31 = std::asinh(_tmp30);
  const Scalar _tmp32 = Scalar(9.6622558468725703) * _tmp31;
  const Scalar _tmp33 =
      -_tmp32 * fh1 -
      Scalar(4.8333311099999996) *
          std::sqrt(
              Scalar(std::pow(Scalar(1 - Scalar(0.20689664689659551) * _tmp29), Scalar(2)) +
                     Scalar(0.13817235445745474) *
                         std::pow(Scalar(-Scalar(0.55659957866191134) * _tmp19 - 1), Scalar(2))));
  const Scalar _tmp34 = Scalar(0.1034955) * _tmp0;
  const Scalar _tmp35 = _tmp33 * _tmp34;
  const Scalar _tmp36 = std::pow(fh1, Scalar(-2));
  const Scalar _tmp37 =
      std::pow(Scalar(_tmp36 * std::pow(fv1, Scalar(2)) + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp38 = Scalar(1.0) * _tmp31;
  const Scalar _tmp39 = _tmp29 + Scalar(-4.8333311099999996);
  const Scalar _tmp40 = _tmp19 + Scalar(1.79662371);
  const Scalar _tmp41 = std::pow(Scalar(std::pow(_tmp39, Scalar(2)) + std::pow(_tmp40, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp42 = _tmp39 * _tmp41;
  const Scalar _tmp43 = _tmp40 * _tmp41;
  const Scalar _tmp44 = _tmp18 * _tmp42 - _tmp28 * _tmp43;
  const Scalar _tmp45 = _tmp12 - _tmp16;
  const Scalar _tmp46 = _tmp45 + _tmp5;
  const Scalar _tmp47 = _tmp46 + p_init0;
  const Scalar _tmp48 = _tmp47 + Scalar(-2.5202214700000001);
  const Scalar _tmp49 = -_tmp21;
  const Scalar _tmp50 = _tmp22 + _tmp26;
  const Scalar _tmp51 = _tmp49 + _tmp50;
  const Scalar _tmp52 = _tmp51 + p_init1;
  const Scalar _tmp53 = _tmp52 + Scalar(8.3888750099999996);
  const Scalar _tmp54 =
      std::sqrt(Scalar(std::pow(_tmp48, Scalar(2)) + std::pow(_tmp53, Scalar(2))));
  const Scalar _tmp55 = Scalar(1.0) / (_tmp54);
  const Scalar _tmp56 = Scalar(1.0) / (_tmp48);
  const Scalar _tmp57 = _tmp54 * _tmp56;
  const Scalar _tmp58 = _tmp57 * (_tmp46 * _tmp53 * _tmp55 - _tmp48 * _tmp51 * _tmp55);
  const Scalar _tmp59 = _tmp17 + _tmp5;
  const Scalar _tmp60 = _tmp59 + p_init0;
  const Scalar _tmp61 = _tmp60 + Scalar(-2.71799795);
  const Scalar _tmp62 = _tmp21 + _tmp50;
  const Scalar _tmp63 = _tmp62 + p_init1;
  const Scalar _tmp64 = _tmp63 + Scalar(-4.7752063900000001);
  const Scalar _tmp65 = std::pow(Scalar(std::pow(_tmp61, Scalar(2)) + std::pow(_tmp64, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp66 = _tmp61 * _tmp65;
  const Scalar _tmp67 = _tmp64 * _tmp65;
  const Scalar _tmp68 = _tmp58 * _tmp66 - _tmp59 * _tmp67 + _tmp62 * _tmp66;
  const Scalar _tmp69 = _tmp53 * _tmp56;
  const Scalar _tmp70 = Scalar(1.0) / (_tmp66 * _tmp69 - _tmp67);
  const Scalar _tmp71 = _tmp27 + _tmp49;
  const Scalar _tmp72 = _tmp71 + p_init1;
  const Scalar _tmp73 = _tmp72 + Scalar(8.3196563700000006);
  const Scalar _tmp74 = _tmp45 + _tmp6;
  const Scalar _tmp75 = _tmp74 + p_init0;
  const Scalar _tmp76 = _tmp75 + Scalar(1.9874742000000001);
  const Scalar _tmp77 = std::pow(Scalar(std::pow(_tmp73, Scalar(2)) + std::pow(_tmp76, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp78 = _tmp73 * _tmp77;
  const Scalar _tmp79 = _tmp76 * _tmp77;
  const Scalar _tmp80 = _tmp69 * _tmp79 - _tmp78;
  const Scalar _tmp81 = _tmp70 * _tmp80;
  const Scalar _tmp82 = _tmp58 * _tmp79 - _tmp68 * _tmp81 + _tmp71 * _tmp79 - _tmp74 * _tmp78;
  const Scalar _tmp83 = Scalar(1.0) / (_tmp82);
  const Scalar _tmp84 = Scalar(1.0) * _tmp83;
  const Scalar _tmp85 = _tmp66 * _tmp81;
  const Scalar _tmp86 = _tmp44 * _tmp57 * (_tmp79 * _tmp84 - _tmp84 * _tmp85);
  const Scalar _tmp87 = -Scalar(0.20999999999999999) * _tmp10 + Scalar(0.20999999999999999) * _tmp8;
  const Scalar _tmp88 = -Scalar(0.010999999999999999) * _tmp2 -
                        Scalar(0.010999999999999999) * _tmp20 + Scalar(-0.010999999999999999);
  const Scalar _tmp89 = Scalar(0.20999999999999999) * _tmp23 + Scalar(0.20999999999999999) * _tmp24;
  const Scalar _tmp90 = _tmp88 - _tmp89;
  const Scalar _tmp91 = _tmp87 + _tmp90;
  const Scalar _tmp92 = _tmp88 + _tmp89;
  const Scalar _tmp93 = _tmp87 + _tmp92;
  const Scalar _tmp94 = _tmp66 * _tmp91;
  const Scalar _tmp95 = _tmp67 * _tmp93 - _tmp69 * _tmp94;
  const Scalar _tmp96 = _tmp69 * _tmp70;
  const Scalar _tmp97 = _tmp69 * _tmp91 + _tmp95 * _tmp96;
  const Scalar _tmp98 = Scalar(1.0) * _tmp51;
  const Scalar _tmp99 = -_tmp98;
  const Scalar _tmp100 = Scalar(1.0) / (_tmp62 + _tmp99);
  const Scalar _tmp101 = Scalar(1.0) * _tmp46;
  const Scalar _tmp102 = _tmp100 * (_tmp101 - _tmp59);
  const Scalar _tmp103 = -_tmp66 * _tmp93 + _tmp94;
  const Scalar _tmp104 = -_tmp102 * _tmp97 + _tmp103 * _tmp96 - _tmp91;
  const Scalar _tmp105 = _tmp79 * _tmp91;
  const Scalar _tmp106 = -_tmp87;
  const Scalar _tmp107 = _tmp106 + _tmp90;
  const Scalar _tmp108 = -_tmp105 * _tmp69 + _tmp107 * _tmp78 - _tmp81 * _tmp95;
  const Scalar _tmp109 = -_tmp102 * _tmp108 - _tmp103 * _tmp81 + _tmp105 - _tmp107 * _tmp79;
  const Scalar _tmp110 = Scalar(1.0) / (_tmp109);
  const Scalar _tmp111 = _tmp110 * _tmp82;
  const Scalar _tmp112 = _tmp109 * _tmp83;
  const Scalar _tmp113 = _tmp112 * (-_tmp104 * _tmp111 - _tmp58 + _tmp68 * _tmp96);
  const Scalar _tmp114 = _tmp110 * (_tmp104 + _tmp113);
  const Scalar _tmp115 = _tmp70 * (-_tmp114 * _tmp80 - _tmp69);
  const Scalar _tmp116 = _tmp43 * _tmp57 * (_tmp114 * _tmp79 + _tmp115 * _tmp66 + Scalar(1.0));
  const Scalar _tmp117 = Scalar(1.0) * _tmp70;
  const Scalar _tmp118 = _tmp117 * _tmp95;
  const Scalar _tmp119 = _tmp102 * _tmp118 - _tmp103 * _tmp117;
  const Scalar _tmp120 = _tmp112 * (-_tmp111 * _tmp119 - _tmp117 * _tmp68);
  const Scalar _tmp121 = _tmp110 * (_tmp119 + _tmp120);
  const Scalar _tmp122 = _tmp70 * (-_tmp121 * _tmp80 + Scalar(1.0));
  const Scalar _tmp123 = _tmp42 * _tmp57 * (_tmp121 * _tmp79 + _tmp122 * _tmp66);
  const Scalar _tmp124 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp125 = _tmp101 + _tmp102 * _tmp98;
  const Scalar _tmp126 = 0;
  const Scalar _tmp127 = -_tmp116 * fh1 - _tmp123 * fh1 -
                         _tmp124 * _tmp57 * (_tmp126 * _tmp79 - _tmp126 * _tmp85) - _tmp86 * fh1;
  const Scalar _tmp128 = std::pow(_tmp127, Scalar(-2));
  const Scalar _tmp129 = -_tmp116 - _tmp123 - _tmp86;
  const Scalar _tmp130 = _tmp128 * _tmp129;
  const Scalar _tmp131 = _tmp71 + _tmp99;
  const Scalar _tmp132 = _tmp102 * _tmp131;
  const Scalar _tmp133 = Scalar(1.0) / (_tmp101 - _tmp132 - _tmp74);
  const Scalar _tmp134 = _tmp125 * _tmp133;
  const Scalar _tmp135 = _tmp100 * (-_tmp108 * _tmp126 - _tmp131 * _tmp134 + _tmp99);
  const Scalar _tmp136 = Scalar(1.0) * _tmp133;
  const Scalar _tmp137 = _tmp106 + _tmp92;
  const Scalar _tmp138 = _tmp137 * fh1;
  const Scalar _tmp139 = -_tmp138 * _tmp42 - Scalar(3.29616) * _tmp25 - _tmp28 * fv1;
  const Scalar _tmp140 = _tmp102 * _tmp136;
  const Scalar _tmp141 = _tmp132 * _tmp136 + Scalar(1.0);
  const Scalar _tmp142 = Scalar(1.0) * _tmp100;
  const Scalar _tmp143 = Scalar(1.0) * _tmp140 - Scalar(1.0) * _tmp141 * _tmp142;
  const Scalar _tmp144 = _tmp131 * _tmp136;
  const Scalar _tmp145 = _tmp100 * (-_tmp108 * _tmp84 + _tmp112 * _tmp144);
  const Scalar _tmp146 = _tmp112 * _tmp136;
  const Scalar _tmp147 = Scalar(1.0) * _tmp44 * (-Scalar(1.0) * _tmp145 + _tmp146);
  const Scalar _tmp148 = Scalar(3.29616) * _tmp11 + _tmp138 * _tmp43 + _tmp18 * fv1;
  const Scalar _tmp149 = _tmp100 * _tmp144;
  const Scalar _tmp150 = -Scalar(1.0) * _tmp136 + Scalar(1.0) * _tmp149;
  const Scalar _tmp151 = _tmp131 * _tmp133;
  const Scalar _tmp152 = -_tmp108 * _tmp121 - _tmp118 + _tmp120 * _tmp151;
  const Scalar _tmp153 = Scalar(1.0) * _tmp42 * (_tmp120 * _tmp136 - _tmp142 * _tmp152);
  const Scalar _tmp154 = -_tmp108 * _tmp114 + _tmp113 * _tmp151 + _tmp97;
  const Scalar _tmp155 = Scalar(1.0) * _tmp43 * (_tmp113 * _tmp136 - _tmp142 * _tmp154);
  const Scalar _tmp156 =
      Scalar(1.0) * _tmp124 * (-_tmp125 * _tmp136 - Scalar(1.0) * _tmp135 + Scalar(1.0)) +
      _tmp139 * _tmp143 + _tmp147 * fh1 + _tmp148 * _tmp150 + _tmp153 * fh1 + _tmp155 * fh1;
  const Scalar _tmp157 = Scalar(1.0) / (_tmp127);
  const Scalar _tmp158 = std::asinh(_tmp156 * _tmp157);
  const Scalar _tmp159 = Scalar(9.6622558468725703) * _tmp127;
  const Scalar _tmp160 =
      -_tmp158 * _tmp159 -
      Scalar(8.3888750099999996) *
          std::sqrt(
              Scalar(Scalar(0.090254729040973036) *
                         std::pow(Scalar(1 - Scalar(0.39679052492160538) * _tmp47), Scalar(2)) +
                     std::pow(Scalar(-Scalar(0.11920549523123722) * _tmp52 - 1), Scalar(2))));
  const Scalar _tmp161 = Scalar(0.1034955) * _tmp157;
  const Scalar _tmp162 = _tmp160 * _tmp161;
  const Scalar _tmp163 = _tmp137 * _tmp43;
  const Scalar _tmp164 = _tmp137 * _tmp42;
  const Scalar _tmp165 = (-_tmp130 * _tmp156 + _tmp157 * (-_tmp143 * _tmp164 + _tmp147 +
                                                          _tmp150 * _tmp163 + _tmp153 + _tmp155)) /
                         std::sqrt(Scalar(_tmp128 * std::pow(_tmp156, Scalar(2)) + 1));
  const Scalar _tmp166 = Scalar(9.6622558468725703) * _tmp129;
  const Scalar _tmp167 = Scalar(1.0) * _tmp158;
  const Scalar _tmp168 = _tmp136 * _tmp148;
  const Scalar _tmp169 = _tmp100 * _tmp154 * _tmp43;
  const Scalar _tmp170 = _tmp145 * _tmp44;
  const Scalar _tmp171 = _tmp100 * _tmp152 * _tmp42;
  const Scalar _tmp172 = _tmp100 * _tmp141;
  const Scalar _tmp173 = -_tmp100 * _tmp131 * _tmp168 + _tmp124 * _tmp135 + _tmp139 * _tmp172 +
                         _tmp169 * fh1 + _tmp170 * fh1 + _tmp171 * fh1;
  const Scalar _tmp174 = _tmp122 * _tmp42;
  const Scalar _tmp175 = _tmp44 * _tmp84;
  const Scalar _tmp176 = _tmp175 * fh1;
  const Scalar _tmp177 = _tmp124 * _tmp126;
  const Scalar _tmp178 = _tmp115 * _tmp43;
  const Scalar _tmp179 = _tmp174 * fh1 - _tmp176 * _tmp81 - _tmp177 * _tmp81 + _tmp178 * fh1;
  const Scalar _tmp180 = Scalar(1.0) / (_tmp179);
  const Scalar _tmp181 = std::asinh(_tmp173 * _tmp180);
  const Scalar _tmp182 = Scalar(9.6622558468725703) * _tmp179;
  const Scalar _tmp183 =
      -_tmp181 * _tmp182 -
      Scalar(4.7752063900000001) *
          std::sqrt(
              Scalar(Scalar(0.32397683292140877) *
                         std::pow(Scalar(1 - Scalar(0.36791786395571047) * _tmp60), Scalar(2)) +
                     std::pow(Scalar(1 - Scalar(0.20941503221602112) * _tmp63), Scalar(2))));
  const Scalar _tmp184 = Scalar(0.1034955) * _tmp180;
  const Scalar _tmp185 = _tmp183 * _tmp184;
  const Scalar _tmp186 = std::pow(_tmp179, Scalar(-2));
  const Scalar _tmp187 = _tmp174 - _tmp175 * _tmp81 + _tmp178;
  const Scalar _tmp188 = _tmp186 * _tmp187;
  const Scalar _tmp189 = Scalar(9.6622558468725703) * _tmp187;
  const Scalar _tmp190 = (-_tmp173 * _tmp188 + _tmp180 * (-_tmp149 * _tmp163 - _tmp164 * _tmp172 +
                                                          _tmp169 + _tmp170 + _tmp171)) /
                         std::sqrt(Scalar(std::pow(_tmp173, Scalar(2)) * _tmp186 + 1));
  const Scalar _tmp191 = Scalar(1.0) * _tmp181;
  const Scalar _tmp192 = _tmp114 * _tmp43;
  const Scalar _tmp193 = _tmp121 * _tmp42;
  const Scalar _tmp194 = _tmp176 + _tmp177 + _tmp192 * fh1 + _tmp193 * fh1;
  const Scalar _tmp195 = std::pow(_tmp194, Scalar(-2));
  const Scalar _tmp196 = _tmp175 + _tmp192 + _tmp193;
  const Scalar _tmp197 = _tmp195 * _tmp196;
  const Scalar _tmp198 = Scalar(1.0) / (_tmp194);
  const Scalar _tmp199 = _tmp146 * _tmp44;
  const Scalar _tmp200 = _tmp113 * _tmp133 * _tmp43;
  const Scalar _tmp201 = _tmp120 * _tmp133 * _tmp42;
  const Scalar _tmp202 = _tmp124 * _tmp134 - _tmp139 * _tmp140 + _tmp168 - _tmp199 * fh1 -
                         _tmp200 * fh1 - _tmp201 * fh1;
  const Scalar _tmp203 = std::asinh(_tmp198 * _tmp202);
  const Scalar _tmp204 = Scalar(1.0) * _tmp203;
  const Scalar _tmp205 = (-_tmp197 * _tmp202 + _tmp198 * (_tmp136 * _tmp163 + _tmp140 * _tmp164 -
                                                          _tmp199 - _tmp200 - _tmp201)) /
                         std::sqrt(Scalar(_tmp195 * std::pow(_tmp202, Scalar(2)) + 1));
  const Scalar _tmp206 = Scalar(9.6622558468725703) * _tmp194;
  const Scalar _tmp207 = Scalar(9.6622558468725703) * _tmp196;
  const Scalar _tmp208 = Scalar(0.1034955) * _tmp198;
  const Scalar _tmp209 =
      -_tmp203 * _tmp206 -
      Scalar(8.3196563700000006) *
          std::sqrt(
              Scalar(std::pow(Scalar(-Scalar(0.12019727204189803) * _tmp72 - 1), Scalar(2)) +
                     Scalar(0.057067943376852184) *
                         std::pow(Scalar(-Scalar(0.50315118556004401) * _tmp75 - 1), Scalar(2))));
  const Scalar _tmp210 = _tmp208 * _tmp209;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 1> _res;

  _res(0, 0) = -Scalar(8.3700199099999999) * _tmp0 -
               Scalar(9.6622558468725703) * fh1 *
                   (-Scalar(1.0) * _tmp36 * _tmp37 * fv1 * std::sinh(_tmp38) -
                    Scalar(0.86625939559540499) * _tmp36 -
                    (-Scalar(0.1034955) * _tmp33 * _tmp36 +
                     _tmp34 * (Scalar(9.6622558468725703) * _tmp30 * _tmp37 - _tmp32)) *
                        std::sinh(_tmp35)) +
               Scalar(9.6622558468725703) * std::cosh(_tmp35) -
               Scalar(9.6622558468725703) * std::cosh(_tmp38);
  _res(1, 0) =
      -_tmp159 *
          (-Scalar(0.87653584775870996) * _tmp130 + Scalar(1.0) * _tmp165 * std::sinh(_tmp167) -
           (-Scalar(0.1034955) * _tmp130 * _tmp160 +
            _tmp161 * (-_tmp158 * _tmp166 - _tmp159 * _tmp165)) *
               std::sinh(_tmp162)) -
      _tmp166 * (Scalar(0.87653584775870996) * _tmp157 - std::cosh(_tmp162) + std::cosh(_tmp167));
  _res(2, 0) =
      -_tmp182 *
          (-Scalar(0.86565325453551001) * _tmp188 + Scalar(1.0) * _tmp190 * std::sinh(_tmp191) -
           (-Scalar(0.1034955) * _tmp183 * _tmp188 +
            _tmp184 * (-_tmp181 * _tmp189 - _tmp182 * _tmp190)) *
               std::sinh(_tmp185)) -
      _tmp189 * (Scalar(0.86565325453551001) * _tmp180 - std::cosh(_tmp185) + std::cosh(_tmp191));
  _res(3, 0) =
      -_tmp206 *
          (-Scalar(0.87679799772039002) * _tmp197 + Scalar(1.0) * _tmp205 * std::sinh(_tmp204) -
           (-Scalar(0.1034955) * _tmp197 * _tmp209 +
            _tmp208 * (-_tmp203 * _tmp207 - _tmp205 * _tmp206)) *
               std::sinh(_tmp210)) -
      _tmp207 * (Scalar(0.87679799772039002) * _tmp198 + std::cosh(_tmp204) - std::cosh(_tmp210));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
